lumapps/design-system

- demo/react/components/thumbnail/default.tsx
- demo/react/components/thumbnail/index.tsx
- demo/react/components/thumbnail/rounded.tsx
- demo/react/layout/SubNav.tsx
- src/components/thumbnail/react/Thumbnail.tsx
- src/react.index.ts
Created a React version of the thumbnail component
> feat(thumbnail): created a React version of the thumbnail component

- demo/react/components/chip/default.tsx
- demo/react/components/chip/index.tsx
- src/components/chip/react/Chip.test.tsx
- src/components/chip/react/Chip.tsx
- src/components/chip/react/__snapshots__/Chip.test.tsx.snap
- src/react.index.ts
This PR provides the react version of the `Chip` component
> feat(chip): create chip component

- demo/react/components/user-block/default.tsx
- demo/react/components/user-block/horizontal.tsx
- demo/react/components/user-block/index.tsx
- demo/react/layout/SubNav.tsx
- src/components/index.ts
- src/components/user-block/react/UserBlock.tsx
- src/core/react/constants.ts
- src/react.index.ts
Create new component to display user details
> feat(userblock): created userblock component

- demo/react/components/image-block/default.tsx
- demo/react/components/image-block/index.tsx
- src/components/image-block/react/ImageBlock.tsx
- src/components/thumbnail/react/Thumbnail.tsx
- src/react.index.ts
> feat(image-block): create imageblock skeleton

- demo/react/App.tsx
- demo/react/components/lightbox/default.tsx
- demo/react/components/lightbox/index.tsx
- demo/react/layout/SubNav.tsx
- package.json
- src/components/button/react/Button.test.tsx
- src/components/button/react/Button.tsx
- src/components/button/react/ButtonRoot.tsx
- src/components/image-block/react/ImageBlock.tsx
- src/components/lightbox/react/Lightbox.tsx
- src/components/lightbox/style/lumapps/_index.scss
- src/react.index.ts
- yarn.lock
> feat(lightbox): add component

- demo/react/components/progress/default.tsx
- demo/react/components/progress/index.tsx
- demo/react/components/progress/linear.tsx
- src/components/progress/react/Progress.tsx
- src/react.index.ts
le composant le plus simple de la lib :)
> Progress component

- src/components/thumbnail/angularjs/thumbnail.html
- src/components/thumbnail/angularjs/thumbnail_directive.js
- src/components/thumbnail/react/Thumbnail.tsx
- src/components/thumbnail/style/lumapps/_index.scss
@GuillaumeNachury et @mcastagnetti to fix on react size too.
Markup has changed.
> fix(thumbnail): correctly handle aspect ratio regarding size

- src/components/slideshow/react/Slideshow.tsx
- src/core/react/hooks/index.tsx
- src/core/react/hooks/useInterval.tsx
Simply moving the hook to its own little quiet place 🏡
> refactor: move custom hooks to their own folder

- src/components/button/react/DropdownButton.tsx
> fix(DropdownButton): fix

- demo/react/components/progress-tracker/default.tsx
- demo/react/components/progress-tracker/index.tsx
- src/components/progress-tracker/react/ProgressTracker.tsx
- src/components/progress-tracker/react/ProgressTrackerStep.tsx
- src/react.index.ts
Adds the progress tracker component
https://lumapps.gitbook.io/design-system/progress-tracker
> feat(progress-tracker): add component and demo file

- demo/react/components/chip/default.tsx
- src/components/chip/react/Chip.test.tsx
- src/components/chip/react/Chip.tsx
- src/components/chip/react/__snapshots__/Chip.test.tsx.snap
- src/components/image-block/react/ImageBlock.tsx
Apply lastest rulsets on chip component
>  feat(chip): polish chip to new standards

- demo/react/components/checkbox/default.tsx
- demo/react/components/checkbox/index.tsx
- src/components/checkbox/react/Checkbox.test.tsx
- src/components/checkbox/react/Checkbox.tsx
- src/components/checkbox/react/CheckboxHelper.test.tsx
- src/components/checkbox/react/CheckboxHelper.tsx
- src/components/checkbox/react/CheckboxLabel.test.tsx
- src/components/checkbox/react/CheckboxLabel.tsx
- src/components/checkbox/react/__snapshots__/Checkbox.test.tsx.snap
- src/components/checkbox/react/__snapshots__/CheckboxHelper.test.tsx.snap
- src/components/checkbox/react/__snapshots__/CheckboxLabel.test.tsx.snap
- src/react.index.ts
Checkbox
https://lumapps.atlassian.net/browse/LUM-2900
> feat(Checkbox): add new component

- demo/react/components/toolbar/default.tsx
- demo/react/components/toolbar/index.tsx
- package.json
- src/components/toolbar/react/Toolbar.tsx
- src/react.index.ts
Just ported the angularJS version to React.
> Created Toolbar component

- demo/react/components/expansion-panel/complex.tsx
- demo/react/components/expansion-panel/header.tsx
- demo/react/components/expansion-panel/index.tsx
- demo/react/components/expansion-panel/label.tsx
- demo/react/components/expansion-panel/trimmed.tsx
- demo/tslint.json
- src/components/drag-handle/react/DragHandle.tsx
- src/components/expansion-panel/react/ExpansionPanel.test.tsx
- src/components/expansion-panel/react/ExpansionPanel.tsx
- src/components/expansion-panel/react/__snapshots__/ExpansionPanel.test.tsx.snap
- src/components/index.ts
- src/core/react/utils.test.ts
- src/core/react/utils.ts
- src/react.index.ts
Fix https://lumapps.atlassian.net/browse/LUM-4292
> feat(expansion-panel): react component

- src/components/expansion-panel/react/ExpansionPanel.test.tsx
- src/components/expansion-panel/react/ExpansionPanel.tsx
- src/components/expansion-panel/react/__snapshots__/ExpansionPanel.test.tsx.snap
- Add default theme prop
- Better handle theme prop to ignore invalid theme value
> fix(expansion-panel): fix default theme

- demo/react/components/grid/default.tsx
- demo/react/components/grid/vertical.tsx
- src/components/grid/react/Grid.tsx
- src/components/grid/react/GridItem.tsx
- src/components/index.ts
New grid implementation with css classes and new attributes
> feat(grid): use css classes instead of attributes

- demo/angularjs/app.js
- demo/angularjs/components/editable-media/controller.js
- demo/angularjs/components/editable-media/demo.html
- demo/angularjs/layout/sub-nav/sub-nav.html
- src/angularjs.index.js
- src/components/avatar/style/lumapps/_index.scss
- src/components/editable-media/angularjs/editable-media.html
- src/components/editable-media/angularjs/editable-media_directive.js
- src/components/editable-media/style/lumapps/_index.scss
- src/components/thumbnail/style/lumapps/_index.scss
- src/core/angularjs/lumx.js
- src/core/style/lumx-theme-lumapps.scss
- src/core/style/size/lumapps/_variables.scss
> feat(editable-media): add component

- demo/react/components/side-navigation/default.tsx
- demo/react/components/side-navigation/index.tsx
- demo/react/layout/SubNav.tsx
- src/components/button/react/Button.tsx
- src/components/expansion-panel/react/ExpansionPanel.tsx
- src/components/index.ts
- src/components/side-navigation/react/SideNavigation.test.tsx
- src/components/side-navigation/react/SideNavigation.tsx
- src/components/side-navigation/react/SideNavigationItem.test.tsx
- src/components/side-navigation/react/SideNavigationItem.tsx
- src/components/side-navigation/react/__snapshots__/SideNavigation.test.tsx.snap
- src/components/side-navigation/react/__snapshots__/SideNavigationItem.test.tsx.snap
- src/core/react/utils.ts
- src/core/utils.js
- src/react.index.ts
Used for the new React demo site in development
> feat(side-navigation): add react component

- demo/react/components/expansion-panel/complex.tsx
- demo/react/components/expansion-panel/header.tsx
- demo/react/components/expansion-panel/label.tsx
- demo/react/components/expansion-panel/trimmed.tsx
- src/components/drag-handle/react/DragHandle.tsx
- src/components/expansion-panel/react/ExpansionPanel.tsx
- Fix max height not adapting to the children height changing
- Convert to fully controlled component
- Add missing props forwarding n `DragHandle` component (required for react-beautiful-dnd
> fix(react-expansion-panel): minor fixes

- demo/react/components/dropdown/default.tsx
- demo/react/components/dropdown/target.tsx
- demo/react/components/popover/default.tsx
- demo/react/components/popover/matchParentWidth.tsx
- demo/react/doc/product/components/dropdown.mdx
- src/components/button/react/ButtonGroup.tsx
- src/components/button/react/DropdownButton.tsx
- src/components/button/react/__snapshots__/DropdownButton.test.tsx.snap
- src/components/dropdown/angularjs/dropdown_directive.js
- src/components/dropdown/react/Dropdown.test.tsx
- src/components/dropdown/react/Dropdown.tsx
- src/components/dropdown/react/__snapshots__/Dropdown.test.tsx.snap
- src/components/dropdown/style/lumapps/_index.scss
- src/components/popover/react/Popover.test.tsx
- src/components/popover/react/Popover.tsx
- src/components/popover/react/__snapshots__/Popover.test.tsx.snap
- src/components/tooltip/react/Tooltip.tsx
- src/core/react/hooks/useClickAway.tsx
- src/core/react/hooks/useComputePosition.tsx
- src/global.d.ts
Need Popover to be merged before.
Missing test, check if the clickaway callback is triggerred when closeonclick is set to true. The problem is the eventlistener is on the document while in the jest context the mounted component is not attached to document so it won't bubble. 
I had some troubles to test this case and it already took me too much time so if anyone has an idea, I'll add the test.
> feat(dropdown): react component

- src/components/select/react/Select.tsx
**Problem**
The use of `useEffect` to focus on the select input when closing provoked, in some cases, the focus of all select input in the page.
**Fix**
Reworked the `useEffect` dependency to include only the `isOpen`, not the anchor.
Bonus: externalized `useEffect` and cleanup focus/blur listener
> fix(react-select): fix focus on input when closing

- demo/react/doc/product/components/progress-tracker.mdx
I just didn't manage to make the first demo block work, I let specialists do their magic :D
> docs(progress-tracker): update from angular

- src/components/text-field/react/TextField.test.tsx
- src/components/text-field/react/TextField.tsx
- src/components/text-field/react/__snapshots__/TextField.test.tsx.snap
- webpack/react/props-loader/convertPropTable.js
- webpack/react/props-loader/convertPropTable.spec.js
**The problem**
The text field style was modified to handle both input and textarea in angular but not react. 
**The fix**
Implemented textarea in React
> fix(text-field): text field React class names to handle both input and textarea

- src/components/select/react/Select.tsx
The div with class "input-chip" was wrapping every chips instead of wrapping each chip individually.
Move the div to wrap each chip.
> fix(react-select): fix chips markup

- demo/angularjs/components/radio-button/partials/default.html
- demo/angularjs/components/radio-button/partials/helper.html
- src/angularjs.index.js
- src/components/radio-button/angularjs/radio-group_directive.js
- src/components/radio-button/react/RadioGroup.test.tsx
- src/components/radio-button/react/RadioGroup.tsx
- src/components/radio-button/react/__snapshots__/RadioGroup.test.tsx.snap
- src/components/radio-button/style/lumapps/_index.scss
> feat(radio-button): add radio group component

- demo/react/doc/product/components/post-block.mdx
- src/components/post-block/react/PostBlock.tsx
Mirror of how it has been done on the ImageBlock component
> feat(post-block): add the possibility of html injection in the text prop

- demo/react/components/slider/default.tsx
- demo/react/components/slider/index.tsx
- demo/react/components/slider/nolabel.tsx
- demo/react/components/slider/precision.tsx
- demo/react/components/slider/style.css
- demo/react/components/slider/withsteps.tsx
- demo/react/doc/product/components/slider.mdx
- demo/react/layout/MainNav.tsx
- src/components/slider/react/Slider.tsx
- src/components/slider/style/lumapps/_index.scss
- src/core/react/hooks/useEventCallback.tsx
- src/core/style/lumx-theme-lumapps.scss
- src/react.index.ts
Sliders : Les Mondes parallèles
> feat(slider): react component

- CHANGELOG.react.md
- package.json
- yarn.lock
Automatically update the version in the @lumx/react CHANGELOG when bumping the version
> feat(react): automatic changelog edit on version bump

- src/components/dialog/angularjs/dialog.html
- src/components/dialog/angularjs/dialog_directive.js
- src/components/dialog/react/Dialog.tsx
- src/components/dialog/style/lumapps/_index.scss
> feat(dialog): add is loading prop support

- CHANGELOG.react.md
- src/components/progress/react/Progress.tsx
Fix stroke-width property in react progress bar.
> fix(react-progress): fix property name

- CHANGELOG.react.md
Update changelog and move text area fixes to next release
> fix(changelog): move fixes to text area to next release

- .github/pull_request_template.md
- CONTRIBUTING.md
Add a template for pull request description with a general summary and a conditional check list
-   [ ] ~(if has react) Check through the [react dev check list]~
-   [ ] ~(if has style) Request an integration review~
-   [ ] ~(if has docs) Request a doc review~
-   [x] Request a frontend review
-   [ ] ~(if fix or feature) Request a test~
> chore: add PR template

- CHANGELOG.react.md
- src/core/react/package.json
New @lumx/react v0.12.0 release 
-   [x] Request a frontend review
> Release @lumx/react v0.12.0

- CHANGELOG.react.md
- demo/react/doc/product/components/autocomplete.mdx
- src/components/autocomplete/react/Autocomplete.test.tsx
- src/components/autocomplete/react/Autocomplete.tsx
- src/components/autocomplete/react/AutocompleteMultiple.test.tsx
- src/components/autocomplete/react/AutocompleteMultiple.tsx
- src/components/autocomplete/react/__mockData__/index.js
- src/components/autocomplete/react/__snapshots__/Autocomplete.test.tsx.snap
- src/components/autocomplete/react/__snapshots__/AutocompleteMultiple.test.tsx.snap
- src/components/chip/react/Chip.tsx
- src/components/chip/react/ChipGroup.tsx
- src/components/chip/style/lumapps/_index.scss
- src/components/chip/style/lumapps/_mixins.scss
- src/components/dropdown/react/Dropdown.tsx
- src/core/constants.d.ts
- src/core/constants.js
- src/core/react/hooks/index.tsx
- src/core/react/hooks/useChipGroupNavigation.tsx
- src/core/react/hooks/useKeyboardListNavigation.tsx
- src/react.index.ts
This component was built upon the Autocomplete simple, providing the following additional features:
- Select multiple values and display them on the Text Field using the Chip component
- Delete values using the backspace or clicking on the close cross on the chip.
Side effects and additional changes introduced:
- Updated documentation and tests for the `Autocomplete` component.
- `useKeyboardListNavigation ` refactor in order to allow a more simpler maintenance, in case there is need to add a new Key code.
- Added missing `isClearable` and `chips` props from Autocomplete component, which are then passed on to the Text Field component.
- Added `isHighlighted` prop for the `Chip` component in order to allow the "focus"-like state on that component.
**Selecting multiple values**
**Delete …
> feat(autocomplete-multiple):  react component

- CHANGELOG.react.md
fix: incorrect rebase on CHANGELOG.react.md
> fix: incorrect rebase on CHANGELOG.react.md

- demo/angularjs/components/list/partials/big.html
- demo/angularjs/components/list/partials/huge.html
- demo/angularjs/components/list/partials/regular.html
- demo/angularjs/index.html
- demo/style/demo/_demo-block.scss
- demo/style/layout/_asset-block.scss
- demo/style/layout/main/_main.scss
- package.json
- src/components/button/style/lumapps/_mixins.scss
- src/components/chip/style/lumapps/_mixins.scss
- src/components/comment-block/style/lumapps/_index.scss
- src/components/dialog/angularjs/dialog_directive.js
- src/components/dialog/style/lumapps/_index.scss
- src/components/expansion-panel/style/lumapps/_index.scss
- src/components/grid/style/lumapps/_index.scss
- src/components/image-block/style/lumapps/_index.scss
- src/components/list/style/lumapps/_mixins.scss
- src/components/post-block/style/lumapps/_index.scss
- src/components/progress-tracker/style/lumapps/_index.scss
- src/components/select/style/lumapps/_index.scss
- src/components/side-navigation/style/lumapps/_index.scss
- src/components/side-navigation/style/lumapps/_mixins.scss
- src/components/slider/style/lumapps/_index.scss
- src/components/slideshow/style/lumapps/_index.scss
- src/components/switch/style/lumapps/_index.scss
- src/components/tabs/style/lumapps/_mixins.scss
- src/components/text-field/style/lumapps/_index.scss
- src/components/text-field/style/lumapps/_mixins.scss
- src/components/thumbnail/style/lumapps/_index.scss
- yarn.lock
> fix: ie11 compatibility

- CHANGELOG.react.md
- src/components/tooltip/react/Tooltip.tsx
- src/components/tooltip/react/__snapshots__/Tooltip.test.tsx.snap
- src/components/tooltip/style/lumapps/_index.scss
- src/core/react/package.json
The position calculation was incorrect.
Replace the old implementation by a Popover component, in order to standardize the position calculation.
> fix(tooltip): use Popover for tooltip component

- packages/site-demo/webpack-loader/mdx-loader/mdx-break-line.js
Fixes break line in MDX paragraph
> fix(demo): fix break line in MDX paragraph

- README.md
- package.json
- packages/lumx-react/.storybook/config.js
- packages/lumx-react/.storybook/webpack.config.js
- packages/lumx-react/package.json
- packages/lumx-react/src/components/avatar/Avatar.stories.tsx
- yarn.lock
So, Storybook for DS  !
There were several decisions taken (which we definitely need to discuss) and some small changes:
- Storybook was installed directly on the `lumx/react` package. Why ? We could have installed storybook in the root folder but:
- The idea with lerna is to manage dependencies for each package
- Since we have different technologies (react, angular), if we wanted to use storybook for angular, we would need to install `@storybook/angular`, which makes more sense to install directly in the `lumx/angularjs` package and not in the root folder
- A quick `npm script` was added to execute storybook `yarn storybook:react` which moves to the `lumx/react` and executes the storybook.
- Storybook webpack config needs to reuse all the loaders that we have on the package itself, in …
> feat(storybook): added storybook  💅🏻

- packages/site-demo/src/layout/DemoBlock.tsx
Fix error message on missing react demo 
> fix(demo): correctly show error on missing react demo

- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-react/package.json
- packages/site-demo/src/index.html.ejs
- packages/site-demo/webpack.config.js
Optimize site demo bundle by removing angular from it and loading angular via a minified file on a CDN
> Chore: optimize demo bundle size 

- packages/lumx-react/src/components/button/Button.stories.tsx
- packages/lumx-react/src/story-block/StoryBlock.jsx
- packages/lumx-react/src/story-block/decorators.js
- packages/lumx-react/src/story-block/styles.js
Added the possibility to switch between themes:
- Added a switcher to the StoryBlock component
- used render props pattern in order to pass down the theme to the story.
- With this pattern, every story will have the parameter `theme` available. …
> feat(theming): added the possibility to change between dark and light

- packages/site-demo/src/layout/DemoBlock.tsx
An error should appear when ther is a missing demo for angularjs
> fix(demo): fix error on missing angularjs demo

- packages/lumx-angularjs/src/components/expansion-panel/expansion-panel_directive.js
- packages/lumx-core/src/scss/components/expansion-panel/lumapps/_index.scss
- packages/lumx-react/src/components/expansion-panel/ExpansionPanel.tsx
- packages/lumx-react/src/components/expansion-panel/__snapshots__/ExpansionPanel.test.tsx.snap
Add hasHeaderDivider prop support.
Also add missing class if header and no label.
Need React part.
> feat(expansion-panel): add hasHeaderDivider prop

- CHANGELOG.react.md
- packages/lumx-react/src/components/dialog/Dialog.tsx
- packages/lumx-react/src/components/dropdown/Dropdown.tsx
- packages/lumx-react/src/components/lightbox/Lightbox.tsx
- packages/lumx-react/src/components/notification/Notification.tsx
- packages/lumx-react/src/components/popover/Popover.tsx
Add z-index props for every popin-like component.
> feat(zindex): handle zindex in every popin-like component

- packages/site-demo/src/layout/PropTable.tsx
- packages/site-demo/webpack-loader/mdx-loader/mdx-demo-code-extractor.js
Fix switching between React/Angularjs engine
> fix(demo): fix switch engine on PropTable

- CHANGELOG.react.md
- packages/lumx-angularjs/src/components/select/select.html
- packages/lumx-angularjs/src/components/text-field/text-field.html
- packages/lumx-angularjs/src/components/text-field/text-field_directive.js
- packages/lumx-core/src/scss/components/select/lumapps/_index.scss
- packages/lumx-core/src/scss/components/select/material/_index.scss
- packages/lumx-core/src/scss/components/text-field/lumapps/_index.scss
- packages/lumx-core/src/scss/components/text-field/lumapps/_mixins.scss
- packages/lumx-core/src/scss/components/text-field/material/_index.scss
- packages/lumx-core/src/scss/components/text-field/material/_mixins.scss
- packages/lumx-react/src/components/select/Select.tsx
- packages/lumx-react/src/components/select/__snapshots__/Select.test.tsx.snap
- packages/lumx-react/src/components/text-field/TextField.tsx
- packages/lumx-react/src/components/text-field/__snapshots__/TextField.test.tsx.snap
- packages/site-demo/content/product/components/text-field/angularjs/character-counter.html
- packages/site-demo/content/product/components/text-field/angularjs/helper.html
- packages/site-demo/content/product/components/text-field/index.mdx
- packages/site-demo/content/product/components/text-field/react/character-counter.tsx
- packages/site-demo/content/product/components/text-field/react/clearable.tsx
> feat(text-field): add maxlength prop for react

- packages/site-demo/content/product/components/side-navigation/index.mdx
Demo block call for with-icon was wrong
> docs(side-navigation): fixed demoblock call

- CHANGELOG.react.md
- packages/lumx-angularjs/src/components/expansion-panel/expansion-panel_directive.js
- packages/lumx-core/src/scss/components/expansion-panel/lumapps/_index.scss
- packages/lumx-react/src/components/expansion-panel/ExpansionPanel.tsx
- packages/lumx-react/src/components/expansion-panel/__snapshots__/ExpansionPanel.test.tsx.snap
- packages/lumx-react/src/index.ts
- packages/site-demo/content/product/components/expansion-panel/angularjs/default.html
- packages/site-demo/content/product/components/expansion-panel/angularjs/drag-handle.html
- packages/site-demo/content/product/components/expansion-panel/angularjs/examples.html
- packages/site-demo/content/product/components/expansion-panel/angularjs/trimmed.html
- packages/site-demo/content/product/components/expansion-panel/react/default.tsx
- packages/site-demo/content/product/components/expansion-panel/react/drag-handle.tsx
- packages/site-demo/content/product/components/expansion-panel/react/examples.tsx
- packages/site-demo/content/product/components/expansion-panel/react/trimmed.tsx
> feat(expansion-panel): replace variant by hasBackground prop

- CHANGELOG.react.md
- packages/lumx-angularjs/src/components/icon/icon_directive.js
- packages/lumx-core/src/scss/_components-lumapps.scss
- packages/lumx-core/src/scss/components/icon/lumapps/_index.scss
- packages/lumx-core/src/scss/components/icon/lumapps/_mixins.scss
- packages/lumx-core/src/scss/components/icon/lumapps/_variables.scss
- packages/lumx-react/src/components/icon/Icon.stories.tsx
- packages/lumx-react/src/components/icon/Icon.tsx
- packages/lumx-react/src/components/icon/__snapshots__/Icon.test.tsx.snap
- packages/lumx-react/src/index.ts
- packages/lumx-react/src/story-block/StoryBlock.jsx
> feat(icon): add has shape attribute

- CHANGELOG.react.md
- packages/lumx-angularjs/src/components/list/list-item_directive.js
- packages/lumx-angularjs/src/components/list/list_directive.js
- packages/lumx-core/src/scss/components/list/lumapps/_index.scss
- packages/lumx-core/src/scss/components/list/lumapps/_mixins.scss
- packages/lumx-core/src/scss/components/list/lumapps/_variables.scss
- packages/lumx-react/src/components/autocomplete/Autocomplete.stories.tsx
- packages/lumx-react/src/components/autocomplete/Autocomplete.test.tsx
- packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.test.tsx
- packages/lumx-react/src/components/autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/lumx-react/src/components/autocomplete/__snapshots__/AutocompleteMultiple.test.tsx.snap
- packages/lumx-react/src/components/list/List.tsx
- packages/lumx-react/src/components/list/ListItem.tsx
- packages/lumx-react/src/index.ts
- packages/lumx-react/src/utils/type.ts
- packages/site-demo/content/product/components/autocomplete/react/default.tsx
- packages/site-demo/content/product/components/autocomplete/react/multiple.tsx
- packages/site-demo/content/product/components/list/react/regular.tsx
- packages/site-demo/content/product/components/select/react/multi-select-chip.tsx
- packages/site-demo/content/product/components/select/react/multi-select-search.tsx
> feat(list): add item padding prop

- packages/lumx-react/src/components/badge/Badge.stories.tsx
- packages/lumx-react/src/components/badge/Badge.test.tsx
- packages/lumx-react/src/components/badge/Badge.tsx
- packages/lumx-react/src/components/badge/__snapshots__/Badge.test.tsx.snap
- packages/lumx-react/src/index.ts
Add Badge React version
-   [ ] Add `need: review-frontend` label
-   [ ] Check through the [react dev check list]
-   [ ] Add `need: test` label
> feat(badge): add badge in React and associated test

- CHANGELOG.md
- packages/lumx-react/src/components/message/Message.stories.tsx
- packages/lumx-react/src/components/message/Message.test.tsx
- packages/lumx-react/src/components/message/Message.tsx
- packages/lumx-react/src/components/message/__snapshots__/Message.test.tsx.snap
- packages/lumx-react/src/index.ts
Add Message component in React
-   [x] Add `need: review-frontend` label
-   [ ] Check through the [react dev check list]
-   [ ] Add `need: test` label
> feat(message): add Message component in react with tests

- packages/lumx-angularjs/src/components/image-block/image-block.html
- packages/lumx-angularjs/src/components/image-block/image-block_directive.js
- packages/lumx-core/src/scss/components/image-block/lumapps/_index.scss
- packages/lumx-react/src/components/image-block/ImageBlock.tsx
> feat(image-block): add size prop

- packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.stories.tsx
Fix remaning broken list item since breaking change
> fix(autocomplete): fix remaining clickable list item

- CHANGELOG.md
- packages/lumx-react/src/hooks/useFocus.tsx
Fix Dropdown focus trigger on close/open (Fix useFocus hook)
> fix: dropdown focus trigger only on visibillity change

- CHANGELOG.md
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-core/webpack.config.js
- packages/lumx-react/package.json
- packages/lumx-react/webpack.config.js
- packages/site-demo/package.json
- yarn.lock
> chore: move moment as externals and peer dependencies

- packages/lumx-react/src/components/select/Select.tsx
- packages/lumx-react/src/components/select/__snapshots__/Select.test.tsx.snap
- packages/lumx-react/src/components/text-field/TextField.tsx
- packages/lumx-react/src/components/text-field/__snapshots__/TextField.test.tsx.snap
> fix: do not display select and text field header if no label

- CHANGELOG.md
- packages/lumx-react/src/components/table/TableRow.tsx
> feat(table): add isClickable and isSelected missing props

- CHANGELOG.md
- packages/lumx-angularjs/src/components/table/table-row.html
- packages/lumx-angularjs/src/components/table/table-row_directive.js
- packages/lumx-core/src/scss/components/table/lumapps/_index.scss
- packages/lumx-react/src/components/table/TableRow.tsx
> feat(table-row): add isDisabled prop

- configs/ignore-not-found-export.js
- packages/lumx-react/.storybook/webpack.config.js
- packages/lumx-react/webpack.config.js
- packages/site-demo/webpack.config.js
Fix storybbok onfig (crash on `yarn storybook:react`)
> fix(storybook): fix config with tsconfig paths resolve

- CHANGELOG.md
- packages/lumx-angularjs/src/components/input-label/input-label_directive.js
- packages/lumx-angularjs/src/components/select/select.html
- packages/lumx-angularjs/src/components/select/select_directive.js
- packages/lumx-angularjs/src/components/text-field/text-field.html
- packages/lumx-angularjs/src/components/text-field/text-field_directive.js
- packages/lumx-core/src/scss/components/input-label/lumapps/_index.scss
- packages/lumx-core/src/scss/components/input-label/lumapps/_mixins.scss
- packages/lumx-react/src/components/input-label/InputLabel.tsx
- packages/lumx-react/src/components/select/Select.tsx
- packages/lumx-react/src/components/text-field/TextField.tsx
> feat: add required prop to select and text-field components

- CHANGELOG.md
- packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx
- packages/lumx-react/src/components/image-block/ImageBlock.tsx
- packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
- packages/lumx-react/src/index.ts
Add new props from Thumbnail component.
> feat(react-image-block): add new props from Thumbnail component

- CHANGELOG.md
- packages/lumx-core/src/scss/components/message/lumapps/_index.scss
- packages/lumx-core/src/scss/components/web-bookmark/lumapps/_index.scss
- packages/lumx-core/src/scss/lumx-theme-lumapps.scss
- packages/lumx-react/package.json
- packages/lumx-react/src/components/web-bookmark/WebBookmark.stories.tsx
- packages/lumx-react/src/components/web-bookmark/WebBookmark.test.tsx
- packages/lumx-react/src/components/web-bookmark/WebBookmark.tsx
- packages/lumx-react/src/components/web-bookmark/__snapshots__/WebBookmark.test.tsx.snap
- packages/lumx-react/src/index.ts
Add a new component `WebBookmark`.
Expected : 
> feat(web-bookmark): add WebBookmark React component

- CHANGELOG.md
- packages/lumx-core/src/scss/components/web-bookmark/lumapps/_index.scss
- packages/lumx-react/src/components/web-bookmark/WebBookmark.stories.tsx
- packages/lumx-react/src/components/web-bookmark/WebBookmark.tsx
- packages/lumx-react/src/components/web-bookmark/__snapshots__/WebBookmark.test.tsx.snap
> feat(web-bookmark): add size prop

- packages/lumx-angularjs/src/components/select/select_directive.js
> fix(select): do not push empty data in model or selection

- CHANGELOG.md
- packages/lumx-angularjs/src/components/list/list_directive.js
- packages/lumx-react/src/components/avatar/Avatar.stories.tsx
- packages/lumx-react/src/components/avatar/Avatar.test.tsx
- packages/lumx-react/src/components/avatar/Avatar.tsx
- packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
- packages/lumx-react/src/components/badge/Badge.stories.tsx
- packages/lumx-react/src/components/badge/Badge.test.tsx
- packages/lumx-react/src/components/badge/Badge.tsx
- packages/lumx-react/src/components/list/List.stories.tsx
- packages/lumx-react/src/components/list/List.tsx
- packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
- packages/lumx-react/src/components/user-block/UserBlock.test.tsx
- packages/lumx-react/src/components/user-block/UserBlock.tsx
- packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
- packages/lumx-react/src/index.ts
- packages/site-demo/content/product/components/post-block/react/default.tsx
- packages/site-demo/content/product/components/user-block/react/extended.tsx
- packages/site-demo/content/product/components/user-block/react/size-l.tsx
- packages/site-demo/content/product/components/user-block/react/size-m.tsx
- packages/site-demo/content/product/components/user-block/react/size-s.tsx
- packages/site-demo/content/product/components/user-block/react/vertical.tsx
Pass badge to avatar and user block and fix list item padding
Fix https://lumapps.atlassian.net/browse/LUM-7980
Fix https://lumapps.atlassian.net/browse/LUM-7981
No padding / Padding Big / Padding huge
No padding (a default padding is set) / Padding Big / Padding huge …
> Pass badge to avatar and user block and fix list item padding

- packages/lumx-react/src/components/dialog/Dialog.stories.tsx
- packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
- packages/lumx-react/src/components/flex-box/FlexBox.stories.tsx
- packages/lumx-react/src/components/flex-box/FlexBox.tsx
- packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap
- packages/lumx-react/src/components/icon/Icon.stories.tsx
- packages/site-demo/content/product/components/expansion-panel/react/examples.tsx
- packages/site-demo/content/product/components/image-block/react/default.tsx
- packages/site-demo/content/product/components/popover/react/positions.tsx
- packages/site-demo/content/product/components/post-block/react/default.tsx
- packages/site-demo/content/product/components/thumbnail/react/variants.tsx
- packages/site-demo/content/product/components/toolbar/react/back.tsx
- packages/site-demo/content/product/components/toolbar/react/media-picker.tsx
- packages/site-demo/content/product/foundations/iconography/index.mdx
- packages/site-demo/src/layout/Main.tsx
> chore: replace grid by flexbox

- packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
- packages/lumx-react/src/components/thumbnail/useFocusedImage.tsx
- packages/lumx-react/src/utils/isInternetExplorer.ts
- packages/lumx-react/src/utils/utils.test.ts
This should fix a display thumbnail problem on IE and size problem if you pass `aspectRatio` to `original` and then to an other value
> fix(thumbnail): fix internet explorer and issue if aspect ratio changes

- packages/lumx-react/src/components/autocomplete/Autocomplete.stories.tsx
- packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.stories.tsx
- packages/lumx-react/src/components/avatar/Avatar.stories.tsx
- packages/lumx-react/src/components/badge/Badge.stories.tsx
- packages/lumx-react/src/components/button/Button.stories.tsx
- packages/lumx-react/src/components/checkbox/Checkbox.stories.tsx
- packages/lumx-react/src/components/date-picker/DatePickerField.stories.tsx
- packages/lumx-react/src/components/dialog/Dialog.stories.tsx
- packages/lumx-react/src/components/flex-box/FlexBox.stories.tsx
- packages/lumx-react/src/components/icon/Icon.stories.tsx
- packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx
- packages/lumx-react/src/components/input-helper/InputHelper.stories.tsx
- packages/lumx-react/src/components/input-label/InputLabel.stories.tsx
- packages/lumx-react/src/components/link/Link.stories.tsx
- packages/lumx-react/src/components/list/List.stories.tsx
- packages/lumx-react/src/components/message/Message.stories.tsx
- packages/lumx-react/src/components/mosaic/Mosaic.stories.tsx
- packages/lumx-react/src/components/notification/Notifications.stories.tsx
- packages/lumx-react/src/components/progress-tracker/ProgressTracker.stories.tsx
- packages/lumx-react/src/components/radio-button/RadioButton.stories.tsx
- packages/lumx-react/src/components/radio-button/RadioGroup.stories.tsx
- packages/lumx-react/src/components/select/Select.stories.tsx
- packages/lumx-react/src/components/slider/Slider.stories.tsx
- packages/lumx-react/src/components/switch/Switch.stories.tsx
- packages/lumx-react/src/components/text-field/TextField.stories.tsx
- packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
- packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
- packages/lumx-react/src/components/web-bookmark/WebBookmark.stories.tsx
Prefix stories fix "LumX components"
> chore(storybook): change stories prefix

- CHANGELOG.md
- packages/lumx-react/src/components/thumbnail/FocusedImage.ts
- packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
- packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
- packages/lumx-react/src/components/thumbnail/useFocusedImage.tsx
- packages/lumx-react/src/index.ts
Add props to manage CORS and enable listening to window resizing on Thumbnail component
> feat(thumbnail): add props to manage cors and listen window's resizing

- CHANGELOG.md
- packages/lumx-react/src/components/dialog/Dialog.tsx
Added a `contentRef` prop to the dialog component.
> feat(dialog): added contentRef prop

- CHANGELOG.md
- packages/lumx-react/src/components/link/Link.test.tsx
- packages/lumx-react/src/components/link/Link.tsx
> feat(link): add link ref on Link React component

- CHANGELOG.md
- packages/lumx-core/package.json
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
feat: declare @lumx/react, @lumx/icons and @lumx/core as side-effect free
> feat: declare @lumx/react, @lumx/icons and @lumx/core as side-effect free

- CHANGELOG.md
Merged like a cowboy the #343 PR. Forgot to update the CHANGELOG on a breaking change refactoring...
> docs: add split select breaking change into CHANGELOG

- CHANGELOG.md
- packages/lumx-angularjs/src/components/dialog/dialog.html
- packages/lumx-angularjs/src/components/dialog/dialog_directive.js
- packages/lumx-core/src/scss/components/dialog/lumapps/_index.scss
- packages/lumx-react/src/components/dialog/Dialog.tsx
> feat(dialog): only use css for scrollable dialog

- .circleci/config.yml
Fix error in demo site CircleCI release worklow
Reference CircleCI documentation: https://circleci.com/docs/2.0/building-docker-images/
> fix(ci): fix demo site release workflow

- packages/lumx-react/src/components/chip/Chip.stories.tsx
- packages/lumx-react/src/components/select/SelectMultiple.stories.tsx
> Minor cleaning: move stories

- packages/lumx-react/src/utils/type.ts
- packages/site-demo/package.json
- packages/site-demo/src/layout/MainNav.tsx
- packages/site-demo/src/theme-switch/switch-dev.ts
- packages/site-demo/webpack-loader/mdx-loader/mdx-demo-code-extractor.js
- packages/site-demo/webpack.config.js
- yarn.lock
Minor fixes to make the demo site work again on IE11
1. run `yarn start`
2. Open http://localhost:4000 in IE11
3. Make sure the website works
> fix(demo): fix demo site on IE11

- CHANGELOG.md
- packages/lumx-core/src/scss/components/mosaic/lumapps/_index.scss
- packages/lumx-react/src/components/mosaic/Mosaic.tsx
- packages/lumx-react/src/components/mosaic/__snapshots__/Mosaic.test.tsx.snap
> fix(mosaic): fix layout on IE11

- CHANGELOG.md
- packages/lumx-react/src/components/dropdown/Dropdown.stories.tsx
- packages/lumx-react/src/components/dropdown/Dropdown.tsx
- packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/lumx-react/src/components/popover/Popover.tsx
> fix: various 0.25 fixes

- CHANGELOG.md
- packages/lumx-react/src/components/tooltip/Tooltip.tsx
- packages/lumx-react/src/components/tooltip/__snapshots__/Tooltip.test.tsx.snap
Rollback default tooltip position to bottom
> fix(tooltip): rollback default tooltip position to bottom

- CHANGELOG.md
- packages/lumx-react/src/components/dropdown/Dropdown.tsx
- packages/lumx-react/src/components/popover/Popover.tsx
- packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx
- packages/lumx-react/src/components/tooltip/Tooltip.test.tsx
- packages/lumx-react/src/components/tooltip/Tooltip.tsx
- packages/lumx-react/src/components/tooltip/__snapshots__/Tooltip.test.tsx.snap
- packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
Dropdown: remove limited placement
Tooltip: remove inline-block style
Popover: fix nan maxheight
> Minor fixes for tooltip, dropdown and popover

- CHANGELOG.md
- packages/lumx-react/src/components/dropdown/Dropdown.stories.tsx
- packages/lumx-react/src/components/dropdown/Dropdown.tsx
- packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/lumx-react/src/components/popover/Popover.tsx
- packages/lumx-react/src/hooks/useFocus.tsx
- packages/lumx-react/src/hooks/useInfiniteScroll.tsx
- Fixed
-   Fixed and improved `Dropdown` shrinking system.
-   Fixed unwanted scroll to the top on the screen when opening a `Dropdown`.
- Changed
-   Improved `useInfiniteScroll` to prevent conditionnal hooks.
- Added
-   Added `focusElement` prop to the `Popover` component to be able to focus on open.
Fixed https://lumapps.atlassian.net/browse/LUM-11305
Fixed https://lumapps.atlassian.net/browse/LUM-11322
Check out the [contribution guide] for general guidelines for submissions to the design …
> fix(dropdown): fix focus and shrink

- CHANGELOG.md
- packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx
- packages/lumx-react/src/components/tooltip/Tooltip.tsx
- packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
- packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
fix frozen tooltip on button changing its disabled state
> fix(tooltip): fix frozen tooltip on button changing its disabled state

- packages/site-demo/content/product/components/slider/index.mdx
- packages/site-demo/content/product/components/table/index.mdx
Add properties to the table demo and fix slider propertie title size
**Table Before**
**Table After**
> docs(table): add table properties to demo

- CHANGELOG.md
- packages/lumx-core/src/scss/components/mosaic/lumapps/_index.scss
- packages/lumx-core/src/scss/components/thumbnail/lumapps/_index.scss
> fix(mosaic): make thumbnail appear correctly on Safari (LUM-11131)

- CHANGELOG.md
- packages/lumx-react/src/components/date-picker/DatePickerField.tsx
- packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerField.test.tsx.snap
> fix(date-picker-field): use locale prop on input

- .github/workflows/commit-message-validator.yml
From now on, all the commit messages should follow the Lumapps rules :)
This rules are near to the angular commit message convention.
More information could be found here: https://github.com/lumapps/commit-message-validator
> chore(ci): add a github workflow to validate all the commit messages

- CHANGELOG.md
- packages/lumx-core/src/scss/components/text-field/lumapps/_mixins.scss
- packages/lumx-react/src/components/text-field/TextField.tsx
> fix(text-field): pass type prop to input

- CHANGELOG.md
- packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx
- packages/lumx-react/src/components/image-block/ImageBlock.tsx
Add isCrossOriginEnabled and crossOrigin missing props on ImageBlock component to forward them to Thumbnail component
> feat(lum-11310): update image block to pass CORS props

- CHANGELOG.md
- packages/lumx-core/src/scss/components/tooltip/lumapps/_index.scss
> feat(tooltip): remove anchor wrapper style

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-core/src/scss/components/thumbnail/lumapps/_index.scss
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/site-demo/package.json
- packages/yo-generators/package.json
fix(thumbnail): fix min-height issue
LUM-11751
> release 0.25.15

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/mosaic/Mosaic.tsx
- packages/site-demo/package.json
- packages/yo-generators/package.json
fix(mosaic): fix forward thumbnail props in Mosaic
[LUM-11838](https://lumapps.atlassian.net/browse/LUM-11838)
> release 0.24.10

- CHANGELOG.md
- packages/lumx-react/src/components/image-block/ImageBlock.tsx
Give ability to the users to control extra props on the Thumbnail component of the ImageBlock.
> feat(image-block): add thumbnailProps prop

- packages/site-demo/content/product/components/select/react/multi-select-search.tsx
- packages/site-demo/content/product/components/side-navigation/angularjs/controller.js
- packages/site-demo/content/product/components/uploader/angularjs/controller.js
- packages/site-demo/content/product/components/uploader/react/default.tsx
> chore(site-demo): replace deprecated icons

- packages/site-demo/content/product/components/date-picker/index.mdx
- packages/site-demo/content/product/components/date-picker/react/no-past-date-allowed.tsx
- packages/site-demo/content/product/components/date-picker/react/past-date-allowed.tsx
Update date-picker demo with real component (not images) and add prop table to it.
**Before**
****
**After**
> feat(demo-site): update datepicker demo and add prop table

- packages/site-demo/content/product/components/text-field/index.mdx
- packages/site-demo/content/product/components/text-field/react/character-counter.tsx
- packages/site-demo/content/product/components/text-field/react/clearable.tsx
- packages/site-demo/content/product/components/text-field/react/default.tsx
- packages/site-demo/content/product/components/text-field/react/helper.tsx
- packages/site-demo/content/product/components/text-field/react/invalid.tsx
- packages/site-demo/content/product/components/text-field/react/placeholder.tsx
- packages/site-demo/content/product/components/text-field/react/text-area-invalid.tsx
- packages/site-demo/content/product/components/text-field/react/text-area-valid.tsx
- packages/site-demo/content/product/components/text-field/react/text-area.tsx
- packages/site-demo/content/product/components/text-field/react/valid.tsx
> docs(textfield): updated doc

- packages/site-demo/content/product/components/select/index.mdx
- packages/site-demo/content/product/components/select/react/multi-select-chip.tsx
- packages/site-demo/content/product/components/select/react/multi-select-search.tsx
- packages/site-demo/content/product/components/select/react/multi-select.tsx
- packages/site-demo/content/product/components/select/react/select-chip.tsx
- packages/site-demo/content/product/components/select/react/single-select.tsx
- packages/site-demo/content/product/components/select/react/state-disabled.tsx
- packages/site-demo/content/product/components/select/react/state-invalid.tsx
- packages/site-demo/content/product/components/select/react/state-valid.tsx
Updated documentation texts
Beware _Lambdas_ are to be replaced by named functions as I do not have the skills to do it properly.
> docs(select): updated texts

- packages/site-demo/content/product/components/chip/index.mdx
- packages/site-demo/content/product/components/chip/react/default.tsx
- packages/site-demo/content/product/components/chip/react/filter.tsx
- packages/site-demo/content/product/components/chip/react/group.tsx
- packages/site-demo/content/product/components/chip/react/small.tsx
- add chip group doc text
- add a filter chip without icon in the demo bloc
Beware React _Lambdas_ are present in the .tsx files of this component and need to be replaced.
> docs(chip): updated doc

- packages/site-demo/content/product/components/badge/react/icon.tsx
- packages/site-demo/content/product/components/badge/react/label.tsx
- packages/site-demo/content/product/components/badge/react/thumbnail.tsx
Add Badge React component to documentation
-   [x] Add `need: review-frontend` label
-   [ ] Check through the [react dev check list]
-   [ ] Add `need: test` label
> docs(badge): implement badge react component to demo

- packages/lumx-react/src/components/link-preview/Demos.stories.tsx
- packages/site-demo/content/product/components/link-preview/index.mdx
- packages/site-demo/content/product/components/link-preview/react/default.tsx
- packages/site-demo/src/components/layout/MainNav.tsx
Added doc for the `Link preview` component
FYI:
- Properties don't load (need: dev-frontend)
- Angular demo version is not done (need: dev-frontend)
> docs(link-preview): added nav entry and doc

- CHANGELOG.md
- packages/lumx-core/src/scss/components/flex-box/lumapps/_index.scss
- packages/lumx-react/src/components/flex-box/FlexBox.tsx
> feat(flexbox): add gap property

- CHANGELOG.md
- packages/lumx-core/src/scss/components/dialog/lumapps/_index.scss
- packages/lumx-core/src/scss/components/divider/lumapps/_index.scss
- packages/lumx-core/src/scss/components/divider/lumapps/_mixins.scss
- packages/lumx-core/src/scss/components/divider/lumapps/_variables.scss
- packages/lumx-core/src/scss/components/tabs/lumapps/_index.scss
- packages/lumx-core/src/scss/core/base/lumapps/_variables.scss
- packages/site-demo/src/style/components/_design-token.scss
> feat(divider): add has divider helper

- packages/site-demo/content/product/patterns/filter-and sort/index.mdx
Fixed some typos and updated headlines orders.
> docs(filter-and-sort): fix text

- packages/site-demo/content/product/components/text-field/index.mdx
- packages/site-demo/content/product/components/text-field/react/required.tsx
Updated texts to provide more guidance on how to use sates, options and text areas
> docs(textfield): updated docs text

- packages/lumx-react/src/components/dialog/Demos.stories.tsx
- packages/lumx-react/src/components/image-block/Demos.stories.tsx
- packages/lumx-react/src/components/progress-tracker/Demos.stories.tsx
Some demo files were missing and broke the react storybook.
Imports have been removed.
> chore(stories): fix broken stories

- CHANGELOG.md
- packages/lumx-react/src/components/list/ListItem.tsx
ListItem: Move some linkProps above the spread to make them overridable
> fix(list-item): link props

- CHANGELOG.md
- packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx
- packages/lumx-react/src/components/slideshow/Slideshow.tsx
- packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx
- packages/lumx-react/src/index.ts
- packages/site-demo/content/product/components/slideshow/react/externalControls.tsx
* Export `SlideshowControls` component.
* Make `Slideshow` controllable externally
> chore(slideshow-controls): export component

- .github/workflows/chromatic.yaml
On PR:
- If it targets a release branch
- If it has the 'need: review-design' label
On commit push:
- On master branch
- On release branches
> chore(ci): run chromatic on push master or release

- CHANGELOG.md
- packages/lumx-core/src/scss/components/link/lumapps/_index.scss
- packages/lumx-core/src/scss/components/link/lumapps/_mixins.scss
- packages/lumx-react/src/components/link/Link.stories.tsx
- packages/lumx-react/src/components/link/Link.tsx
- packages/lumx-react/src/components/link/__snapshots__/Link.test.tsx.snap
- packages/site-demo/content/product/components/link/react/default.tsx
- packages/site-demo/content/product/components/link/react/implicit.tsx
- packages/site-demo/content/product/components/link/react/sizes.tsx
> [Link] Add right and left icons LUM-13298

- packages/lumx-react/.storybook/main.js
- packages/lumx-react/package.json
- yarn.lock
> chore(storybook): add source code addon

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-core/src/js/utils.ts
- packages/lumx-core/src/scss/components/popover/lumapps/_index.scss
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/dropdown/Dropdown.tsx
- packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap
- packages/lumx-react/src/components/list/List.tsx
- packages/lumx-react/src/components/list/ListItem.tsx
- packages/lumx-react/src/components/list/useInteractiveList.tsx
- packages/lumx-react/src/components/popover/Popover.stories.tsx
- packages/lumx-react/src/components/popover/Popover.tsx
- packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.tsx
- packages/site-demo/package.json
- packages/yo-generators/package.json
- yarn.lock
- chore(click-away): fix ClickAwayProvider initialization error
- fix(popover): update placement when children change
- fix(popover): fix scrollbar and arrow
- chore(list): provide event on list item selected
- chore(release): release v0.28.1
> Merge release v0.28.1 into master

- packages/site-demo/content/product/components/button/index.mdx
- packages/site-demo/content/product/components/button/react/toggle.tsx
Added doc for the toggle (`isSelected`) button use case
> docs(button): updated doc with toggle case

- CHANGELOG.md
- packages/lumx-core/src/scss/components/lightbox/lumapps/_index.scss
- packages/lumx-react/package.json
- packages/lumx-react/src/components/dialog/Dialog.tsx
- packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx
- packages/lumx-react/src/components/image-block/ImageBlock.tsx
- packages/lumx-react/src/components/lightbox/Lightbox.tsx
- packages/lumx-react/src/components/mosaic/Mosaic.stories.tsx
- packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
- packages/lumx-react/src/hooks/useDisableBodyScroll.ts
- packages/site-demo/content/product/components/image-block/react/image-block-alignment.tsx
- packages/site-demo/content/product/foundations/size/react/t-shirt-example.tsx
- yarn.lock
- fix image block align 
- remove focus trap lib
> fix/lightbox LUM-11248

- packages/site-demo/content/product/components/mosaic/index.mdx
- packages/site-demo/content/product/components/mosaic/react/four-images.tsx
- packages/site-demo/content/product/components/mosaic/react/more-images.tsx
- packages/site-demo/content/product/components/mosaic/react/three-images.tsx
- packages/site-demo/content/product/components/mosaic/react/two-images.tsx
> docs(mosaic): add documentation

- CHANGELOG.md
- packages/lumx-core/src/scss/components/switch/lumapps/_index.scss
- packages/lumx-react/src/stories/generated/Mosaic/Demos.stories.tsx
- packages/lumx-react/src/stories/generated/Mosaic/four-images.tsx
- packages/lumx-react/src/stories/generated/Mosaic/more-images.tsx
- packages/lumx-react/src/stories/generated/Mosaic/three-images.tsx
- packages/lumx-react/src/stories/generated/Mosaic/two-images.tsx
> fix(switch): prevent content to take parent full width LUM-12987

- CHANGELOG.md
- packages/lumx-angularjs/src/components/dialog/dialog_directive.js
- packages/lumx-angularjs/src/components/dropdown/dropdown_directive.js
- packages/lumx-angularjs/src/components/lightbox/lightbox_directive.js
- packages/lumx-angularjs/src/components/notification/notification_service.js
- packages/lumx-angularjs/src/components/popover/popover_directive.js
- packages/lumx-angularjs/src/lumx.js
- packages/lumx-angularjs/src/utils/depth_service.js
- packages/lumx-angularjs/src/utils/index.js
Reverts angular code in https://github.com/lumapps/design-system/pull/298
> chore(zindex): revert angular zindex system

- CHANGELOG.md
- packages/lumx-core/src/scss/components/switch/_index.scss
- packages/lumx-react/src/components/switch/Switch.stories.tsx
> fix(switch): fix content position on right alignment

- packages/site-demo/content/product/foundations/typography/index.mdx
Updated foundation > typography doc with some explanation and link to roboto font face.
> docs(typography): updated doc

- packages/site-demo/content/product/components/flex-box/index.mdx
Short doc for flexbox (link to flexbox on CSS tricks)
> docs(flexbox): added light doc

- packages/site-demo/content/product/components/table/react/default.tsx
- packages/site-demo/src/style/layout/main/_main.scss
> docs(table): update demo to fit data table use case

- CHANGELOG.md
- packages/lumx-react/src/index.ts
Fix omitted `AlertDialog` export.
> chore(alert-dialog): fix export

- CHANGELOG.md
- packages/lumx-core/src/scss/components/link/_mixins.scss
- packages/lumx-react/src/components/link/Link.stories.tsx
> fix(link): fix default style in button mode

- packages/lumx-core/src/css/material.css
- packages/lumx-core/src/scss/core/color/_functions.scss
> feat(color): use css variable for primary color

- CHANGELOG.md
- packages/lumx-core/src/scss/core/typography/_variables.scss
-   Allow `typography` to be overriden.
> fix(typography): allow font to be overriden

- packages/lumx-core/src/scss/components/avatar/_index.scss
- packages/lumx-react/src/components/avatar/Avatar.tsx
- packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
> fix(avatar): move circle shape to thumbnail wrapper

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-core/src/scss/components/avatar/_index.scss
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/avatar/Avatar.tsx
- packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
- packages/lumx-react/src/components/popover/Popover.stories.tsx
- packages/lumx-react/src/components/popover/Popover.tsx
- packages/site-demo/package.json
- packages/yo-generators/package.json
- fix(avatar): move circle shape to thumbnail wrapper
- feat(popover): add boundaryRef prop to change overflow boundary
- chore(changelog): add avatar badge fix in changelog
- chore(release): release v1.0.11
> merge v1.0.11 into master

- packages/lumx-core/src/scss/core/typography/_mixins.scss
- packages/lumx-core/src/scss/core/typography/_variables.scss
> fix(typography): use css variable for base font family

- CHANGELOG.md
- packages/lumx-react/src/components/tabs/Tabs.stories.tsx
- packages/lumx-react/src/components/tabs/state.ts
> fix(tabs): fix activeTabIndex resetting to -1 on unmount

- README.md
Add documentation for publishing package to NPM.
> chore(readme): add publishing steps

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-core/src/scss/components/link/_index.scss
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/site-demo/package.json
- packages/yo-generators/package.json
> fix(core): fix specificity of css selector for links

- .circleci/config.yml
- CHANGELOG.md
- README.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-core/src/scss/components/link/_index.scss
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/tabs/Tabs.stories.tsx
- packages/lumx-react/src/components/tabs/state.ts
- packages/lumx-react/src/hooks/useOnResize.ts
- packages/site-demo/package.json
- packages/yo-generators/package.json
- chore(ci): upgrade docker version
- fix(tabs): fix activeTabIndex resetting to -1 on unmount
- test(tabs): add story testing the tab index reset
- fix(tabs): fix synchronization of active index
- chore(release): release v1.0.12
- chore(readme): add publishing steps
- fix(thumbnail): limit resize update
- chore(release): release v1.0.13
- fix(core): fix specificity of css selector for links
- chore(release): release v1.0.14
> merge v1.0.14 into master

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/slideshow/useKeyOrSwipeNavigate.ts
- packages/site-demo/package.json
- packages/yo-generators/package.json
- yarn.lock
- Keep the slideshow swipe gesture on touch device only.
- Update lodash
> chore(slideshow): keep swipe only on touch device + update lodash

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/slideshow/useKeyOrSwipeNavigate.ts
- packages/site-demo/package.json
- packages/yo-generators/package.json
- yarn.lock
> Merge v1.0.16 into master

- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/style-dictionary/properties/core/size.json
> fix(chore): fix xxl size design token

- .github/workflows/github-actions-validator.yml 
Add required actions validator
> chore(ci): add required actions validator

- CHANGELOG.md
- packages/lumx-react/src/components/alert-dialog/AlertDialog.stories.tsx
- packages/lumx-react/src/components/alert-dialog/AlertDialog.tsx
- packages/lumx-react/src/components/alert-dialog/__snapshots__/AlertDialog.test.tsx.snap
Add more props forwarding on the AlertDialog
> chore(alert-dialog): add more props forwarding

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-core/src/scss/components/input-label/_index.scss
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/autocomplete/Autocomplete.test.tsx
- packages/lumx-react/src/components/autocomplete/Autocomplete.tsx
- packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.test.tsx
- packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.tsx
- packages/lumx-react/src/components/autocomplete/__snapshots__/Autocomplete.test.tsx.snap
- packages/lumx-react/src/components/autocomplete/__snapshots__/AutocompleteMultiple.test.tsx.snap
- packages/site-demo/package.json
- packages/yo-generators/package.json
> merge v1.0.19 into master

- CHANGELOG.md
- packages/lumx-react/src/components/icon/Icon.tsx
- packages/lumx-react/src/components/icon/__snapshots__/Icon.test.tsx.snap
> fix(icon): fix missing modifier that enable right style for svg

- CHANGELOG.md
- packages/lumx-core/src/scss/components/progress-tracker/_index.scss
> fix(progress-tracker): fix style regression

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-core/src/scss/components/progress-tracker/_index.scss
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/icon/Icon.tsx
- packages/lumx-react/src/components/icon/__snapshots__/Icon.test.tsx.snap
- packages/lumx-react/src/hooks/useDisableBodyScroll.ts
- packages/site-demo/package.json
- packages/yo-generators/package.json
- yarn.lock
- fix(icon): fix missing modifier that enable right style for svg
- fix(modal): fix unexpected scroll to top on dialog/lightbox open
- chore(release): release v1.0.20
- fix(progress-tracker): fix style regression
- chore(release): release v1.0.21
> merge v1.0.21 into master

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-core/src/scss/components/button/_index.scss
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/button/Button.stories.tsx
- packages/lumx-react/src/components/button/ButtonRoot.tsx
- packages/lumx-react/src/components/switch/Switch.tsx
- packages/lumx-react/src/components/switch/__snapshots__/Switch.test.tsx.snap
- packages/site-demo/package.json
- packages/yo-generators/package.json
- feat(switch): add role switch for screen readers behavior
- fix(icon-button): fix tooltip with `hasBackground`
- fix(icon-button): fix broder radius with `hasBackground`
- chore(release): release v1.0.22
> merge v1.0.22 into master

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/dialog/Dialog.stories.tsx
- packages/lumx-react/src/components/dialog/Dialog.tsx
- packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
- packages/lumx-react/src/components/switch/Switch.tsx
- packages/lumx-react/src/components/switch/__snapshots__/Switch.test.tsx.snap
- packages/lumx-react/src/hooks/useDelayedVisibility.tsx
- packages/site-demo/package.json
- packages/yo-generators/package.json
- fix(switch): add aria-checked attribute
- feat(dialog): add onVisibilityChange prop
- chore(release): release v1.0.23
> merge v1.0.23 into master

- CHANGELOG.md
- lerna.json
- packages/lumx-angularjs/package.json
- packages/lumx-core/package.json
- packages/lumx-icons/package.json
- packages/lumx-react/package.json
- packages/lumx-react/src/components/message/Message.stories.tsx
- packages/lumx-react/src/components/message/Message.tsx
- packages/site-demo/package.json
- packages/yo-generators/package.json
- feat(message): add icon prop to cutomize the icon
- chore(release): release v1.0.24
> merge v1.0.24 into master

- CHANGELOG.md
- packages/lumx-react/src/hooks/useDisableBodyScroll.ts
Fix a bug only present in the product, releasing an alpha version to test it
> fix(modal): fix unexpected scroll on closing

- CHANGELOG.md
- packages/lumx-core/src/scss/components/list/_index.scss
- packages/lumx-react/src/components/list/List.stories.tsx
- packages/lumx-react/src/components/list/ListItem.stories.tsx
- packages/lumx-react/src/components/list/ListItem.tsx
- packages/lumx-react/src/components/list/__snapshots__/List.test.tsx.snap
- packages/lumx-react/src/components/list/__snapshots__/ListItem.test.tsx.snap
- packages/lumx-react/src/components/list/useInteractiveList.tsx
Add disabled state on the list item
> feat(list-item): add isDisabled prop

- CHANGELOG.md
- packages/lumx-react/src/components/slideshow/useKeyNavigate.ts
Bug fix : in the slideshow, keyboard navigation was reversed (left arrow going to the next slide and right arrow to the previous one). Changed the direction.
> fix(slideshow): fix keyboard navigation

- packages/lumx-core/style-dictionary/config/gen-css-variables.js
- packages/lumx-core/style-dictionary/config/gen-scss-variables.js
- packages/lumx-core/style-dictionary/config/gen-ts-variables.js
- packages/lumx-core/style-dictionary/config/utils/_prettier-scss.js
- packages/lumx-core/style-dictionary/config/utils/_prettier-ts.js
> fix(style-dictionnary): fix calls for prettier scripts

- CHANGELOG.md
- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/src/scss/components/chip/_index.scss
- packages/lumx-core/src/scss/components/icon/_mixins.scss
- packages/lumx-core/src/scss/core/state/_mixins.scss
- packages/lumx-core/style-dictionary/properties/components/navigation.json
- packages/lumx-react/src/components/drag-handle/DragHandle.tsx
> chore(color): limit soft dark to wanted components

- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/style-dictionary/config/gen-css-variables.js
- packages/lumx-core/style-dictionary/config/gen-ts-variables.js
> chore(design-tokens): add value to TS generated tokens

- .vscode/tasks.json
- .vscode/tasks.json.old
- packages/lumx-react/src/stories/generated/List/Demos.stories.tsx
- packages/lumx-react/src/stories/generated/List/paddings.tsx
- packages/site-demo/content/product/components/list/index.mdx
- packages/site-demo/content/product/components/list/react/clickable.tsx
- packages/site-demo/content/product/components/list/react/paddings.tsx
Added minimum heights, padding and clickable states info and demos
> docs(list): updated documentations

- package.json
- packages/lumx-react/src/stories/generated/List/Demos.stories.tsx
- packages/lumx-react/src/stories/generated/List/clickable.tsx
- packages/lumx-react/storybook/story-block/StoryBlock.tsx
- packages/lumx-react/storybook/story-block/decorator.jsx
- Fix storybook dark theme switcher
- Fix injected date in storybook chromatic
> chore(storybook): fix dark theme switcher & chromatic date override

- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/style-dictionary/config/utils/_prettier-ts.js
- packages/lumx-core/style-dictionary/properties/components/text-field.json
- Fix hard coded path in style dictionary config
> chore(style-dictionary): fix hard coded path

- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/css/material.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/style-dictionary/properties/components/button.json
- packages/lumx-core/style-dictionary/properties/components/navigation.json
> chore(design-tokens): avoid css variable for border-radius property

- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/style-dictionary/properties/core/typography.json
> chore(design-tokens): change quote style font weight

- CHANGELOG.md
- packages/lumx-react/src/components/user-block/UserBlock.tsx
Add nameProps to the available props for UserBlock component
> feat(user-block): add nameProps to the available props

- packages/site-demo/content/product/components/thumbnail/index.mdx
- packages/site-demo/content/product/components/thumbnail/react/loading-error.tsx
- packages/site-demo/content/product/components/thumbnail/react/ratios.tsx
> docs(thumbnail-update): added ratio and states explanations

- CHANGELOG.md
- packages/lumx-core/src/scss/components/user-block/_index.scss
- packages/lumx-react/src/components/avatar/Avatar.stories.tsx
- packages/lumx-react/src/components/avatar/Avatar.tsx
- packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap
- packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
- packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx
- packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap
- packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
- packages/lumx-react/src/components/user-block/UserBlock.test.tsx
- packages/lumx-react/src/components/user-block/UserBlock.tsx
- packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
- packages/lumx-react/src/stories/utils/CustomLink.tsx
Improve link/button a11y on avatar and user block.
> feat(a11y): fix avatar and userblock link/button a11y

- packages/site-demo/package.json
- yarn.lock
Fix an error on the the docker build of the demo site that silently occured in CircleCI build.
> chore(site): fix demo site docker build

- CHANGELOG.md
- packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx
- packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx
- packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
- packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap
Pass in the `className` prop from `imgProps` into the `img` tag
> chore(thumbnail): add custom classname to img

- CHANGELOG.md
- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/style-dictionary/config/gen-scss-variables.js
- packages/lumx-core/style-dictionary/config/utils/_css-prefer-variable.js
- packages/lumx-core/style-dictionary/config/utils/_resolve-structure-alias.js
- packages/lumx-core/style-dictionary/properties/core/color.json
Use CSS variables in SCSS primary and secondary colors
> chore(colors): scss primary & secondary variable in CSS

- .eslintignore
- .gitattributes
- .github/pull_request_template.md
- .github/workflows/chromatic.yaml
- dev-packages/ga-remove-label/.gitignore
- dev-packages/ga-remove-label/action.yml
- dev-packages/ga-remove-label/dist/index.js
- dev-packages/ga-remove-label/index.js
- dev-packages/ga-remove-label/package.json
- package.json
- yarn.lock
- Deploy chromatic on "need: deploy-chromatic" instead of "need: review-design".
- Remove the label when the build is done.
- Add help in the PR template
> chore(chromatic): change deploy label and remove label after deploy

- CHANGELOG.md
- packages/lumx-react/src/components/slideshow/Slideshow.tsx
- packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx
- packages/lumx-react/src/components/slideshow/SlideshowControls.tsx
- packages/lumx-react/src/hooks/useFocusWithin.ts
- packages/lumx-react/src/hooks/useSlideshowControls.ts
Refactor the Slideshow controls management so that we can reuse the logic if the components Slideshow and SlideshowControls are used separately.
> chore(slideshow): create hook for slideshow controls

- packages/lumx-react/src/stories/generated/Thumbnail/Demos.stories.tsx
- packages/lumx-react/src/stories/generated/Thumbnail/error-fallback.tsx
- packages/lumx-react/src/stories/generated/Thumbnail/error.tsx
- packages/lumx-react/src/stories/generated/Thumbnail/loading-error.tsx
- packages/lumx-react/src/stories/generated/Thumbnail/loading.tsx
- packages/site-demo/content/product/components/thumbnail/index.mdx
- packages/site-demo/content/product/components/thumbnail/react/error-fallback.tsx
- packages/site-demo/content/product/components/thumbnail/react/error.tsx
- packages/site-demo/content/product/components/thumbnail/react/loading.tsx
Add more doc on thumbnail loading and error state
> chore(doc): add more doc on thumbnail loading and error state

- CHANGELOG.md
- packages/lumx-react/src/components/slideshow/Slides.tsx
- packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx
- packages/lumx-react/src/components/slideshow/Slideshow.tsx
- packages/lumx-react/src/components/slideshow/SlideshowControls.tsx
- packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap
- packages/lumx-react/src/hooks/useFocusWithin.ts
- packages/lumx-react/src/hooks/useSlideshowControls.ts
> chore(slides): fix types

- CHANGELOG.md
- packages/lumx-react/src/components/slideshow/Slides.tsx
- packages/lumx-react/src/components/slideshow/Slideshow.tsx
- packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx
- packages/lumx-react/src/components/slideshow/SlideshowItem.tsx
- packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap
- packages/lumx-react/src/hooks/useSlideshowControls.ts
- Remove slide delayed visbility for now
- Fix play button which was not working if the previous/next buttons were clicked first
> chore(slideshow): temporarily remove delayed visibility

- packages/site-demo/content/product/components/avatar/index.mdx
Add documentation on accessibility concerns on the avatar component
> docs(avatar): document accessibility concerns

- CHANGELOG.md
- packages/lumx-react/src/components/checkbox/Checkbox.tsx
- packages/lumx-react/src/components/radio-button/RadioButton.tsx
- feat(radio-button): add inputRef prop
- feat(checkbox): add inputRef prop
> feat: add inputRef on Checkbox and RadioButton

- CHANGELOG.md
- packages/lumx-core/src/scss/components/mosaic/_index.scss
SUP-1390
This PR fixes mosaics on safari.
> fix(mosaic): fix mosaics on safari

- CHANGELOG.md
- packages/lumx-core/src/scss/components/flex-box/_index.scss
- packages/lumx-react/src/components/flex-box/FlexBox.stories.tsx
- packages/lumx-react/src/components/flex-box/FlexBox.tsx
- packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap
- packages/lumx-react/src/components/index.ts
Add the 'medium' option inside the available Size map and GapSize type
> feat(size): add medium

- packages/site-demo/content/product/components/thumbnail/index.mdx
# General summary
Add documentation on accessibility concerns on the thumbnail component
> docs(thumbnail): document accessibility concerns

- packages/site-demo/content/product/components/badge/index.mdx
# General summary
Add documentation on accessibility concerns on the badge component
> docs(badge): document accessibility concerns

- CHANGELOG.md
- packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
Timers were not correctly cleared when the component was being unmounted (or updated).
https://user-images.githubusercontent.com/85614948/167909431-65a28070-a14a-4708-8572-db9a22d29075.mov
> chore(tooltip): clear pending timers when unmounted

- .docker/nginx.conf
Add gzip compression on nginx for the demo site on design.lumapps.com
> chore(demo-site): configure nginx gzip compression

- CHANGELOG.md
- packages/lumx-react/src/components/user-block/UserBlock.stories.tsx
- packages/lumx-react/src/components/user-block/UserBlock.tsx
- packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
- packages/site-demo/content/product/components/user-block/index.mdx
- packages/site-demo/content/product/components/user-block/react/extended.tsx
- packages/site-demo/content/product/components/user-block/react/size-l.tsx
- packages/site-demo/content/product/components/user-block/react/size-m.tsx
- packages/site-demo/content/product/components/user-block/react/size-s.tsx
- packages/site-demo/content/product/components/user-block/react/vertical.tsx
- fix(user-block): improve a11y keyboard navigation
- chore(demo-site): document user-block accessibility
Remove keyboard focus on the avatar to avoid redundancy with the name link/button
> fix(user-block): improve a11y keyboard nav

- packages/site-demo/content/product/components/badge/index.mdx
- packages/site-demo/content/product/components/button/index.mdx
- packages/site-demo/content/product/components/chip/index.mdx
- packages/site-demo/content/product/components/lightbox/index.mdx
- packages/site-demo/content/product/components/list/index.mdx
- packages/site-demo/content/product/components/message/index.mdx
- packages/site-demo/content/product/components/mosaic/index.mdx
- packages/site-demo/content/product/components/popover/index.mdx
- packages/site-demo/content/product/components/skeleton/index.mdx
- packages/site-demo/content/product/components/skeleton/react/typography.tsx
- packages/site-demo/content/product/components/slideshow/index.mdx
- packages/site-demo/content/product/components/text-field/index.mdx
- packages/site-demo/content/product/components/thumbnail/index.mdx
- packages/site-demo/content/product/foundations/size/index.mdx
- packages/site-demo/content/product/foundations/typography/index.mdx
- packages/site-demo/content/product/patterns/filter-and-sort/index.mdx
- packages/site-demo/content/product/patterns/form-validation/index.mdx
- packages/site-demo/content/product/patterns/loading-state/index.mdx
- packages/site-demo/content/product/patterns/pick-and-manage/index.mdx
- packages/site-demo/content/product/patterns/translation/index.mdx
- packages/site-demo/content/product/patterns/widgets-settings/index.mdx
- packages/site-demo/content/product/utilities/typography/index.mdx
- packages/site-demo/plugins/utils/cleanExcerpt.js
- chore(demo-site): fix various typo
- chore(demo-site): fix clean up page except for search
- chore(demo-site): fix typography HTML tags
> chore(demo-site): minor fixes and improvements

- packages/site-demo/content/product/components/link/index.mdx
Document link component accessibility
> chore(demo-site): document link accessibility

- packages/lumx-react/src/components/checkbox/Checkbox.tsx
- packages/lumx-react/src/components/checkbox/__snapshots__/Checkbox.test.tsx.snap
- packages/site-demo/content/product/components/checkbox/index.mdx
Add accessibility concerns to Checkbox documentation page. 
Link the helper to the checkbox, now it is read by screen readers with the label when focusing the checkbox
> docs(checkbox): add a11y documentation

- packages/lumx-react/src/components/button/Button.stories.tsx
- packages/lumx-react/src/components/button/ButtonRoot.tsx
- packages/site-demo/content/product/components/button/index.mdx
Adds some documentation about accessibility for the `<Button>` component
> docs(button): document accessibility concerns

- CHANGELOG.md
- packages/lumx-core/src/scss/components/select/_index.scss
- packages/lumx-react/src/components/select/Select.stories.tsx
- packages/lumx-react/src/components/select/Select.tsx
- packages/lumx-react/src/components/select/SelectMultiple.stories.tsx
- packages/lumx-react/src/components/select/SelectMultiple.tsx
- packages/lumx-react/src/components/select/constants.ts
Add icon props to Select and SelectMultiple
> feat(select): add icon props to Select and SelectMultiple

- CHANGELOG.md
- packages/lumx-react/package.json
Fix export of React types used in component props
> chore(build): fix export react types

- CHANGELOG.md
- packages/lumx-react/src/components/index.ts
- packages/lumx-react/src/components/link/Link.stories.tsx
- packages/lumx-react/src/components/link/Link.tsx
- fix(typography): fix TypographyCustom values
- feat(link): allow all typography variants
Example: https://5fbfb1d508c0520021560f10-jlcbrpizjx.chromatic.com/?path=/story/lumx-components-link-link--all-typography
> Typography: fix TypographyCustom values & allow all typography variants on Link

- CHANGELOG.md
- packages/lumx-react/src/components/thumbnail/useFocusPointStyle.test.ts
- packages/lumx-react/src/components/thumbnail/useFocusPointStyle.tsx
> fix(thumbnail): base shift calculation on scaledsize instead of imagesize

- CHANGELOG.md
- configs/postcss.config.js
- packages/lumx-core/package.json
- packages/lumx-core/src/scss/components/text/_index.scss
- packages/lumx-core/src/scss/lumx.scss
- packages/lumx-react/package.json
- packages/lumx-react/src/components/text/Text.stories.tsx
- packages/lumx-react/src/components/text/Text.test.tsx
- packages/lumx-react/src/components/text/Text.tsx
- packages/lumx-react/src/components/text/index.ts
- packages/lumx-react/src/index.ts
- yarn.lock
> feat(text): create text component

- packages/site-demo/content/product/components/heading/index.mdx
- packages/site-demo/content/product/components/heading/react/automatic-heading-level.tsx
- packages/site-demo/content/product/components/text/index.mdx
- packages/site-demo/plugins/lumx-mdx-preprocessor/mdx-demo-block.js
<details><summary>Text component page</summary>
</details>
<details><summary>Heading component page</summary>
</details>
> docs: document Text & Heading components

- packages/lumx-react/src/stories/generated/Dropdown/Demos.stories.tsx
- packages/lumx-react/src/stories/generated/Dropdown/selects.tsx
- packages/site-demo/content/product/components/divider/index.mdx
- packages/site-demo/content/product/components/flag/index.mdx
- packages/site-demo/content/product/components/icon/index.mdx
- packages/site-demo/content/product/components/message/index.mdx
- packages/site-demo/content/product/components/tabs/index.mdx
- packages/site-demo/content/product/components/text/index.mdx
- docs(divider): add accessibility concerns section
- docs(flag): add accessibility concerns section
- docs(icon): add accessibility concerns section
- docs(message): add accessibility concerns section
- docs(tab): add accessibility concerns section
> docs: document various component a11y concerns

- CHANGELOG.md
- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/src/scss/components/progress-tracker/_index.scss
- packages/lumx-core/src/scss/components/table/_mixins.scss
- packages/lumx-core/src/scss/components/tabs/_index.scss
- packages/lumx-core/src/scss/core/state/_mixins.scss
- packages/lumx-core/style-dictionary/properties/components/text-field.json
Improve focus outline visibility on elements with keyboard focus.
https://user-images.githubusercontent.com/939567/199956949-ca0612cf-e513-44ea-9a6d-a4510b431b6a.mov
https://user-images.githubusercontent.com/939567/199956955-1018ba43-55da-48f2-84a0-f68730a33458.mov
> feat(state): a11y focus state

- CHANGELOG.md
- packages/lumx-react/src/components/radio-button/RadioButton.tsx
- packages/lumx-react/src/components/radio-button/__snapshots__/RadioButton.test.tsx.snap
- packages/lumx-react/src/components/switch/Switch.tsx
- packages/lumx-react/src/components/switch/__snapshots__/Switch.test.tsx.snap
- packages/site-demo/content/product/components/checkbox/index.mdx
- packages/site-demo/content/product/components/radio-button/index.mdx
- packages/site-demo/content/product/components/switch/index.mdx
- fix(radio-button): fix helper text accessibility
- feat(radio-button): add inputProps prop
- docs(radio-button): add accessibility concerns section
- fix(switch): fix helper text accessibility
- docs(switch): add accessibility concerns section
- docs(checkbox): reword accessibility concerns section
Minor a11y improvement
Document a11y concerns (make it homogenous too)
> chore: a11y improve & document checkbox, radiobutton & switch

- .github/actions/release-note/action.yml
- .github/actions/release-note/index.js
Fix release-note workflow bugs
- Properly format version name
- Fix syntax error
Tested here : https://github.com/lumapps/design-system/actions/runs/3541230291/jobs/5945239205
> chore(ci): fix release-note workflow

- packages/site-demo/content/menu.yml
Add missing "miscellaneous utilities" menu entry
> chore(demo-site): fix miscellaneous menu entry

- .github/workflows/release.yml
Fix typo in the `release.yml` file, should fix the chromatic deploy in the release.
> chore(release): update chromatic deploy variables

- .github/workflows/release.yml
Add the version reference into the chromatic workflow in order to try to fix this error from the deployment build.
> fix(chromatic): add the ref into the chromatic workflow

- .github/actions/remove-label/action.yml
- .github/workflows/deploy-chromatic-pull-request.yaml
- .github/workflows/deploy-chromatic-release.yaml
- .github/workflows/release.yml
- chore(workflow): fix release publish dir
- chore(workflow): check latest version on release
- chore(workflow): remove chromatic deploy on release
> chore(workflow): fix release workflow

- packages/lumx-core/package.json
- packages/lumx-react/package.json
- packages/site-demo/package.json
- yarn.lock
Update moment (peerDependencies for the libs, dependency for the demo site) to patch security vulnerabilities.
> chore(deps): update moment to patch security vulnerability

- .github/workflows/release.yml
> chore(release): fix prerelease version increment

- .github/workflows/release-build-site.yml
- .github/workflows/validate-pull-request.yml
targetting master can prevent merge on this repo therefore targetting a ref to avoid this issue
> chore(actions): targetting a version of actions validator

- CHANGELOG.md
- packages/lumx-react/src/components/popover/Popover.tsx
- packages/lumx-react/src/hooks/useFocusTrap.ts
- fix(focus-trap): remove unnecessary scroll on focus trap activation
- fix(popover): remove unnecessary scroll on close
> fix(popover): fix scroll on open/close

- .dockerignore
- .github/workflows/release-build-site.yml
- .github/workflows/release-deploy-chromatic.yaml
- .github/workflows/release-github-release-note.yml
- Dockerfile
- chore(ci): improve release workflow tag pattern
- chore(demo): fix docker config
> chore(demo): fix docker config

- packages/site-demo/content/product/components/skeleton/index.mdx
docs(skeleton): document accessibility concerns
> docs(skeleton): document accessibility concerns ARCH-49

- CHANGELOG.md
- packages/lumx-react/src/components/comment-block/CommentBlock.tsx
- packages/site-demo/content/product/components/comment-block/index.mdx
- feat(comment-block): make name & date optional
- feat(comment-block): deprecate inaccessible mouse event props
- docs(comment-block): document accessibility concerns
> fix(comment-block): improve a11y & doc ARCH-26

- CHANGELOG.md
- packages/lumx-core/src/scss/components/table/_index.scss
- packages/lumx-core/src/scss/components/table/_mixins.scss
- packages/lumx-react/src/components/table/TableCell.test.tsx
- packages/lumx-react/src/components/table/TableCell.tsx
- packages/site-demo/content/product/components/table/index.mdx
- packages/site-demo/content/product/components/table/react/default.tsx
- fix(table-cell): fix clickable & sortable table cell accessibility
- docs(table): document accessibility concerns
> chore(table): improve a11y & doc ARCH-53

- .github/actions/release-note/index.js
- .github/actions/update-pr-body/action.yml
- .github/actions/update-pr-body/index.js
- .github/actions/utils.js
- .github/workflows/deploy-chromatic-pull-request.yaml
- configs/chromatic.js
Update PR body when deploying storybook:
- When deploying:
`StoryBook: Deploying...` (linking to the deploy job execution page)
- When failed:
`StoryBook: ❌ Failed` (linking to the deploy job execution page)
- When deployed
`StoryBook: https://... (Chromatic build)` (linking to the storybook & the chromatic build)
- When outdated (commit sha not matching the URL)
`StoryBook: https://...  **⚠️ Outdated commit**`
StoryBook: https://045ce171--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=288))
> chore(ci): improve chromatic deploy

- CHANGELOG.md
- packages/lumx-core/package.json
- packages/lumx-react/package.json
- packages/site-demo/package.json
- yarn.lock
Upgrade `classnames` package to `2.3.2`
StoryBook: https://13894bc0--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=300)) **⚠️ Outdated commit**
> chore(classnames): upgrade classnames package to 2.3.2

- CHANGELOG.md
- packages/lumx-core/src/scss/components/list/_mixins.scss
- packages/lumx-core/src/scss/components/navigation/_index.scss
Implements [CF-690 ](https://lumapps.atlassian.net/browse/CF-690)
Improve focus accessibility on navigation item and list item : https://www.figma.com/file/fvnlLZmUQKJsyiKIrV49eF/Improve-contrast-on-list-item-and-navigation-focus-state?type=design&node-id=0%3A1&mode=design&t=k0LayL3Fqjy5qlhP-1
StoryBook: https://ec520a01--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=311)) **⚠️ Outdated commit**
> fix(navigation): improve hover accessibility for list item and navigation

- CHANGELOG.md
- packages/lumx-core/src/scss/components/dialog/_index.scss
- packages/lumx-core/src/scss/components/dialog/_variables.scss
> feat(dialog): make dialog full size on mobile

- package.json
- yarn.lock
Update semver dev dependency 
Check that the release workflow correclty generate a new version number (test an alpha release)
> chore(dependencies): update semver package version

- packages/lumx-icons/README.md
- packages/site-demo/content/product/components/icon/index.mdx
- packages/site-demo/content/product/foundations/iconography/index.mdx
- packages/site-demo/src/components/content/design-tokens/IconLibrary/IconBlock.tsx
- packages/site-demo/src/components/content/design-tokens/IconLibrary/IconLibrary.scss
- packages/site-demo/src/components/content/design-tokens/IconLibrary/IconLibrary.tsx
- packages/site-demo/src/components/content/design-tokens/IconLibrary/index.tsx
- packages/site-demo/src/components/content/design-tokens/IconLibrary/useIconLibrary.ts
- packages/site-demo/src/components/content/design-tokens/index.ts
- packages/site-demo/src/utils/formatSVGCode.ts
- packages/site-demo/src/utils/iterable.ts
- packages/site-demo/untypped-modules.d.ts
- tsconfig.json
https://lumapps.atlassian.net/browse/DSW-172
Add an icon library explorer with search and copy to clipboard shortcuts on the iconography page
https://github.com/lumapps/design-system/assets/939567/bb133707-6d93-4bf1-baba-9a447428e702
> chore(site-demo): add icon library with search

- CHANGELOG.md
- packages/lumx-react/src/components/chip/Chip.test.tsx
- packages/lumx-react/src/components/chip/Chip.tsx
DSW-191
Fix forwarding key down event on clickable chip
> fix(chip): forward key down event on clickable chip

- CHANGELOG.md
- packages/lumx-react/src/components/checkbox/Checkbox.stories.tsx
- packages/lumx-react/src/components/checkbox/Checkbox.test.tsx
- packages/lumx-react/src/components/checkbox/Checkbox.tsx
- packages/site-demo/content/product/components/checkbox/react/default.tsx
Implement: https://lumapps.atlassian.net/browse/CTRIB-4794
Add intermediate state to checkbox (we need it for Bulk management)
> feat(checkbox): add intermediate state

- .github/workflows/release-publish.yaml
> chore(workflow): fix demo site docker tags

- packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
> chore(data-picker): fix non alpha-numeric formatted year

- CHANGELOG.md
- packages/lumx-react/src/components/text-field/TextField.tsx
> chore(text-field): add jsdoc of native input type prop

- CHANGELOG.md
- packages/lumx-react/src/components/image-lightbox/internal/usePointerZoom.ts
> fix(image-lightbox): windows 10 reporting incorrect pointer device

- CHANGELOG.md
- packages/lumx-react/src/components/date-picker/DatePicker.stories.tsx
- packages/lumx-react/src/components/date-picker/DatePickerControlled.test.tsx
- packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
StoryBook: https://e4110dd9--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=408))
Before | After
--- | ---
Testable here: https://e4110dd9--5fbfb1d508c0520021560f10.chromatic.com/?path=/story/lumx-components-date-picker-datepicker-demos--default
> feat(date-picker): update day buttons to use standard button styles

- CHANGELOG.md
- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/src/scss/components/chip/_index.scss
- packages/lumx-core/src/scss/core/state/_mixins.scss
- packages/lumx-core/style-dictionary/properties/components/chip.json
- packages/lumx-react/src/components/chip/Chip.stories.tsx
DSW-226
Testable in StoryBook: https://77788479--5fbfb1d508c0520021560f10.chromatic.com/?path=/story/lumx-components-chip-chip--theming
StoryBook: https://dbb0a9d3--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=411)) **⚠️ Outdated commit**
> feat(chip): add border CSS theming variable on selected state

- CHANGELOG.md
- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/src/scss/core/state/_mixins.scss
- packages/lumx-core/style-dictionary/properties/components/chip.json
- packages/lumx-react/src/components/chip/Chip.stories.tsx
StoryBook: https://c3ae74b6--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=412)) **⚠️ Outdated commit**
> feat(chip): add background color css variable theming on selected state

- CHANGELOG.md
- packages/lumx-core/src/scss/components/navigation/_index.scss
- packages/lumx-react/src/components/navigation/Navigation.stories.tsx
- packages/lumx-react/src/components/navigation/NavigationSection.test.tsx
- packages/lumx-react/src/components/navigation/NavigationSection.tsx
- packages/lumx-react/src/stories/decorators/withCombinations.tsx
- Refactor styles using `@each` to avoid manual repetitions
- Fix focus outline color in dark theme (was black instead of white)
- Add variants and theming stories
> chore(navigation): refactor styles and add theming story

- CHANGELOG.md
- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/src/scss/components/list/_mixins.scss
- packages/lumx-core/src/scss/components/side-navigation/_index.scss
- packages/lumx-core/style-dictionary/properties/components/side-navigation.json
- packages/lumx-react/src/components/side-navigation/SideNavigationItem.stories.tsx
https://lumapps.atlassian.net/browse/DSW-227
> feat(side-navigation): add border CSS theming variable on selected state

- CHANGELOG.md
- packages/lumx-core/src/scss/components/tabs/_index.scss
- packages/lumx-react/src/components/tabs/Tab.tsx
- packages/lumx-react/src/components/tabs/Tabs.stories.tsx
- packages/lumx-react/src/stories/utils/concatPath.tsx
- packages/lumx-react/src/stories/utils/toFlattenProps.ts
- packages/lumx-react/src/stories/utils/withCategory.ts
Add tab label truncate on constrained width
StoryBook: https://91744138--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=422))
> feat(tabs): add tab label truncate on constrained width

- CHANGELOG.md
- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/style-dictionary/properties/components/text-field.json
Update the theme light border color for better
contrast.
CMS-549
StoryBook: https://262c7ee1--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=424)) **⚠️ Outdated commit**
> feat(text-field): change border color for contrast

- CHANGELOG.md
- packages/lumx-core/src/css/design-tokens.css
- packages/lumx-core/src/js/constants/design-tokens.ts
- packages/lumx-core/src/scss/_design-tokens.scss
- packages/lumx-core/src/scss/components/button/_index.scss
- packages/lumx-core/src/scss/components/slideshow/_index.scss
- packages/lumx-core/style-dictionary/properties/components/button.json
- packages/lumx-core/style-dictionary/properties/components/chip.json
- packages/lumx-core/style-dictionary/properties/components/navigation.json
- packages/lumx-core/style-dictionary/properties/components/side-navigation.json
- packages/lumx-core/style-dictionary/properties/components/text-field.json
- packages/lumx-react/src/components/button/ButtonGroup.stories.tsx
> [A11Y] Color contrast fixes (release R1)

- packages/lumx-react/.storybook/story-block/StoryBlock.tsx
- packages/lumx-react/src/components/autocomplete/Autocomplete.stories.tsx
- packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.stories.tsx
- packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx
- packages/lumx-react/src/components/navigation/Navigation.stories.tsx
- packages/lumx-react/src/components/popover/Popover.stories.tsx
- packages/lumx-react/src/components/radio-button/RadioGroup.stories.tsx
- packages/lumx-react/src/components/select/Select.stories.tsx
- packages/lumx-react/src/components/select/SelectMultiple.stories.tsx
- packages/lumx-react/src/components/skeleton/SkeletonTypography.stories.tsx
- packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx
- packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx
- packages/lumx-react/src/components/tabs/Tabs.stories.tsx
Use the theme context in the SB theme switcher
StoryBook: https://9bb2d9a8--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=432))
> chore(storybook): use theme context in storybook theme switcher

- CHANGELOG.md
- packages/lumx-react/src/components/popover/Popover.stories.tsx
- packages/lumx-react/src/components/popover/Popover.tsx
- packages/lumx-react/src/components/popover/usePopoverStyle.tsx
Update popover placement on both anchor and popoverr resize
> fix(popover): auto update on anchor and popover resize

- CHANGELOG.md
- packages/lumx-react/src/components/tooltip/Tooltip.test.tsx
- packages/lumx-react/src/components/tooltip/Tooltip.tsx
- packages/lumx-react/src/hooks/usePopper.ts
Remove Tooltip placement style when hidden (closeMode=hide) to fix overflow issue
> fix(tooltip): fix overflow issue on closeMode hide

- CHANGELOG.md
- packages/lumx-react/src/components/popover/usePopoverStyle.tsx
limit popover placement update on element resize
> fix(popover): limit popover placement update on element resize

- CHANGELOG.md
- packages/lumx-core/src/scss/components/input-label/_index.scss
- packages/lumx-react/src/components/input-label/InputLabel.stories.tsx
- packages/lumx-react/src/components/input-label/InputLabel.test.tsx
- packages/lumx-react/src/components/input-label/InputLabel.tsx
- packages/lumx-react/src/components/text-field/TextField.stories.tsx
Add a typo prop to `InputLabel`
StoryBook: https://f223bfce--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=444))
> chore(input-label): add typo prop

- CHANGELOG.md
- packages/lumx-react/src/components/tabs/TabProvider.tsx
Fix tabs state update loop on React 18
> fix(tabs): fix state update loop on React 18

- CHANGELOG.md
- packages/lumx-react/src/hooks/useClickAway.tsx
- packages/lumx-react/src/stories/utils/initDemoShadowDOMPortal.ts
- packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.stories.jsx
- packages/lumx-react/src/utils/Portal/PortalProvider.stories.jsx
Fix click away detection inside a shadow DOM
> fix(click-away): fix click away detection inside shadow DOM
