lumapps/design-system

src/core/utils.js
By passing camelCased properties to the `handleBasicClasses` function (https://github.com/lumapps/design-system/blob/master/src/core/utils.js#L39), className was computed as is.
This PR always transforms computed css properties to match BEM naming standards.
=> fix(util): always use kebab-case for basic computed css properties

demo/react/components/popover/tooltip.tsx, src/components/popover/react/Popover.tsx
When using the `popover` tooltip mode, an arrow is now pointing toward the reference element.
=> Added arrow on tooltip

src/components/table/angularjs/table-cell-head.html, src/components/table/react/TableCell.tsx, src/components/table/style/lumapps/_index.scss
En cas de long label, les icons doivent rester au niveau du texte. Ils doivent être wrappés dans la même div.
Un header non sortable (donc non cliquable) ne doit pas avoir de tabindex
=> fix(table): avoid bad style on header with long label

src/core/angularjs/constants/theme_constant.js, src/core/angularjs/lumx.js, src/core/angularjs/utils/depth_service.js, src/core/angularjs/utils/enter-keypress_directive.js, src/core/angularjs/utils/event-scheduler_service.js, src/core/angularjs/utils/focus-on-init_directive.js, src/core/angularjs/utils/focus-trap_service.js, src/core/angularjs/utils/utils_service.js
Webpack aliases are not tolerated by eslint inside `core` folder due to the presence of multiple `package.json` files (one for each package).
=> fix(config): fix failing imports due to multiple package.json files

src/components/icon/angularjs/icon_directive.js, src/components/icon/react/Icon.test.tsx, src/components/icon/react/Icon.tsx, src/components/icon/react/__snapshots__/Icon.test.tsx.snap, src/components/icon/style/lumapps/_index.scss, src/components/icon/style/lumapps/_mixins.scss, src/components/index.ts
Add color variant parameter
To do in React version :
Add color-variant prop (no default value = if no prop, no class)
Associated class: lumx-icon--color-variant-{colorVariant} (N, L2, L5...)
=> feat(icon): add color variant parameter

demo/react/doc/product/components/list.mdx, demo/react/doc/product/components/select.mdx, src/components/expansion-panel/react/ExpansionPanel.tsx, src/components/list/react/List.tsx, src/components/side-navigation/react/SideNavigation.tsx, src/components/side-navigation/react/SideNavigationItem.tsx
When a List contained only one ListItem (not from a Array.map), the component was crashing.
It was due to the fact that the List component only accept an array as children. 
To avoid crashes, I cast the children as an array if it is not.
=> fix(react-list): cast children as array when unique child

demo/react/doc/product/components/chip.mdx, demo/react/doc/product/components/dropdown.mdx, demo/react/doc/product/components/expansion-panel.mdx, demo/react/doc/product/components/popover.mdx, demo/react/doc/product/components/select.mdx, demo/react/doc/product/components/side-navigation.mdx, demo/react/layout/PropTable.tsx, demo/style/layout/main/_main.scss, webpack/react/mdx-demo-code-extractor/index.js
This PR removes the automatic insertion of the component properties tables in favor of manually inserting the prop table on the demo.
=> feat(demo-react): manual prop table section (instead of the automatic one)

src/components/expansion-panel/react/ExpansionPanel.tsx, src/components/select/react/Select.tsx, src/components/thumbnail/react/Thumbnail.tsx, src/react.index.ts, tslint.json
Some `enum` where declared as `const enum` which would compile await and thus could not be imported in demos or even in lumsites.
Ex: The `ThumbnailAspectRatio` enum could not be used in react demos
Remove `const`. If the error persist on your machine, delete the `.awcache` directory and rebuild
**:warning: Warning**: non-const enum **have** to be defined before their use. Here I moved the `Thumbnail` import/export before the `ImageBlock` in the `react.index.ts` because the `ThumbnailAspectRatio` enum is used by the `ImageBlock`
=> fix(react): removed const enum so they can be imported as object

src/components/dropdown/react/Dropdown.tsx
**Bug**
Fix https://lumapps.atlassian.net/browse/LUM-5350
**Fix**
- Add a condition to prevent clickAway from calling onClose when the dropdown is already closed.
- Fix the eventListener removal on the Escape press handler.
=> fix(dropdown): fix onClose unnecessary calls

demo/react/doc/product/components/popover.mdx, demo/react/doc/product/components/progress-tracker.mdx, demo/react/doc/product/components/thumbnail.mdx, webpack/react/mdx-demo-code-extractor/index.js
The use of template string in MDX demo would break the demo.
Better escape the character when injecting the demo code in the DemoBlock (used for the "show code")
=> fix(demo): fix bug when using template string in React MDX demo block

CHANGELOG.react.md, demo/react/doc/product/components/post-block.mdx, src/components/post-block/style/lumapps/_index.scss
Add the missing theme variant for the "meta" and "text" block in the react PostBlock.
=> feat(post-block): add light and dark theme variant for post-block meta and text

demo/react/layout/AssetBlock.tsx, demo/style/layout/_asset-block.scss, demo/style/lumapps.scss
Add an `AssetBlock` component for use in React demo site.
Zeplin mock-up: https://app.zeplin.io/project/5beed1207b5f913ebc61d14e/screen/5d8e26da4c9cce181197c1b8
Example of use:
```mdx
import { AssetBlock } from 'LumX/demo/react/layout/AssetBlock';
<AssetBlock downloadURL="foo.com/bar"/>
<AssetBlock downloadURL="foo.com/bar/981981" fileName="Toto.pdf"/>
<AssetBlock 
downloadURL="foo.com/bar" 
fileName="Doodle-grandparent-day.jpg"
thumbnailURL="https://www.google.com/logos/doodles/2019/grandparents-day-2019-uk-ie-5839152682631168-2x.jpg"
/>
```
=> feat(doc): add asset block for React doc site

CHANGELOG.react.md, demo/react/doc/product/components/text-field.mdx, src/components/select/style/material/_index.scss, src/components/text-field/angularjs/text-field_directive.js, src/components/text-field/react/TextField.tsx, src/components/text-field/react/__snapshots__/TextField.test.tsx.snap, src/components/text-field/style/lumapps/_index.scss, src/components/text-field/style/lumapps/_mixins.scss, src/components/text-field/style/material/_index.scss, src/components/text-field/style/material/_mixins.scss
All around fixes to Text Area component:
- Remove resizing from browsers that [support it](https://caniuse.com/#feat=css-resize) by using `resize` attribute. For the ones that do not support it, we can make the width fixed.
- Allow automatic resizing for the height when the user is writing (with a little bit of magic)
- Add valid and error css to the Text Area component for Material CSS
=> fix(textarea styles): Text area height and style fixes

CHANGELOG.react.md, demo/react/doc/product/components/chip.mdx, demo/react/doc/product/components/text-field.mdx, src/angularjs.index.js, src/components/button/style/lumapps/_mixins.scss, src/components/button/style/lumapps/_variables.scss, src/components/button/style/material/_variables.scss, src/components/chip/angularjs/chip-group_directive.js, src/components/chip/react/ChipGroup.test.tsx, src/components/chip/react/ChipGroup.tsx, src/components/chip/react/__snapshots__/ChipGroup.test.tsx.snap, src/components/chip/style/lumapps/_index.scss, src/components/chip/style/lumapps/_variables.scss, src/components/select/angularjs/select.html, src/components/select/react/Select.tsx, src/components/select/react/__snapshots__/Select.test.tsx.snap, src/components/select/style/lumapps/_index.scss, src/components/select/style/lumapps/_mixins.scss, src/components/select/style/material/_index.scss, src/components/text-field/angularjs/text-field.html, src/components/text-field/angularjs/text-field_directive.js, src/components/text-field/react/TextField.tsx, src/components/text-field/react/__snapshots__/TextField.test.tsx.snap, src/components/text-field/style/lumapps/_index.scss, src/components/text-field/style/lumapps/_mixins.scss, src/components/text-field/style/lumapps/_variables.scss, src/components/text-field/style/material/_index.scss, src/components/text-field/style/material/_mixins.scss, src/core/custom-colors.js, src/react.index.ts
Due to the upcoming feature `Autocomplete and Autocomplete multiple` there are some changes that we need on the Text Field:
- In order to have the possibility to show a list of chips before the Text Field, we add the props `chips` to the Text Field and show them before the native input.
- In order to have the ability to listen to the `focus` and `blur` events on the text field itself, it was necessary to add the props `onFocus` and `onBlur` and pass them on the native input, where they were overwritten. If these functions are passed on, they will be executed.
- Furthermore, in order to use this component in conjunction  with the Dropdown, we need to provide a `ref` to the Dropdown so it knows where to open. On the other hand, if we want to manually trigger the focus on the text field, we …
=> feat(textfield-enhancements): Text field enhancements

CHANGELOG.react.md, demo/react/doc/product/components/autocomplete.mdx, demo/react/layout/MainNav.tsx, src/components/autocomplete/react/Autocomplete.test.tsx, src/components/autocomplete/react/Autocomplete.tsx, src/components/autocomplete/react/__snapshots__/Autocomplete.test.tsx.snap, src/components/list/react/List.tsx, src/components/list/react/ListItem.tsx, src/components/list/style/lumapps/_index.scss, src/components/list/style/lumapps/_mixins.scss, src/components/text-field/react/TextField.tsx, src/core/react/hooks/index.tsx, src/core/react/hooks/useKeyboardListNavigation.tsx, src/react.index.ts
Created the first version of the autocomplete component. it supports:
- Filter options based on a given input
- Control over the value, options, and when the suggestions are displayed or not
- Navigate between options using the keyboard
- Selecting one option either by clicking or pressing Enter
**Simple usage**
**Keyboard navigation**
**No results**
**Note**: this variation may need css changes since the `no results` label is a little bit more gray on the mockups.
**Leave and come back**
Side effects:
- ListItem: in order to allow the keyboard navigation, it was necessary to add some sort of mechanism to ListItem in order to, from the outside, control which ListItem is highlighted. To do that, we can create a new prop called `isHighlighted` and control the boolean from the outside
- …
=> feat(autocomplete simple): react component for autocomplete - simple variation

CHANGELOG.react.md, demo/react/components/expansion-panel/complex.tsx, demo/react/components/select/multiSelectionWithSearch.tsx, demo/react/doc/product/components/autocomplete.mdx, demo/react/doc/product/components/dropdown.mdx, demo/react/doc/product/components/list.mdx, demo/react/doc/product/components/select.mdx, src/components/icon/react/Icon.tsx, src/components/list/react/ListItem.tsx
Uniformizes the use of the Size enum everywhere.
Deprecated `ListItemSize` in favor of `Size`
-   [x] Request a frontend review
=> chore: uniformize React component sizes

CHANGELOG.react.md, demo/react/doc/product/components/autocomplete.mdx, src/components/autocomplete/react/Autocomplete.tsx, src/components/chip/style/lumapps/_index.scss, src/components/chip/style/lumapps/_mixins.scss, src/components/popover/react/Popover.test.tsx, src/components/popover/react/Popover.tsx, src/components/popover/react/__snapshots__/Popover.test.tsx.snap, src/components/select/react/Select.tsx, src/core/react/hooks/index.tsx, src/core/react/hooks/useFocusOnClose.tsx
- Fixes a bug related to the Popover component that made the content be displayed on the top left corner. (see screenshots section)
- Remove cursor pointer for chips
- Remove a selected chip by clicking on the entire Chip for Autocomplete multi.
Notice the dropdown appearing for a split second on the top left corner.
-   [X] (if has style) Request an integration review
-   [X] (if has docs) Request a doc review
-   [X] Request a frontend review
-   [X] (if fix or feature) Request a test …
=> feat(autocomplete-multi): change Chip deletion logic.

CHANGELOG.react.md, demo/react/doc/product/components/lightbox.mdx, src/components/dialog/style/lumapps/_index.scss, src/components/lightbox/react/Lightbox.tsx
* Remove children from useEffect dependencies, causing the effect to execute every time the children changes 
* Split useEffect into two separate effects (one for scroll management and one for focus management)
The dialog should still work as it did …
=> fix(lightbox): fix body scrollbar flickering when children updates

src/components/slideshow/react/SlideshowControls.tsx
Fix already tested, just needed to be cherry picked on the right branch
=> fix(slideshow-controls): put a setState func in a useEffect

packages/site-demo/webpack-loader/mdx-loader/index.js, packages/site-demo/webpack-loader/mdx-loader/mdx-break-line.js
This fix should correclty generate `<br/>` break line in MDX paragraph without error in the console
=> fix(demo): fix console error on break line in MDX

packages/lumx-react/.storybook/webpack.config.js, packages/lumx-react/src/components/avatar/Avatar.stories.tsx, packages/lumx-react/src/components/button/Button.stories.tsx, packages/lumx-react/src/story-block/StoryBlock.jsx, packages/lumx-react/src/story-block/decorators.js, packages/lumx-react/src/story-block/index.jsx, packages/lumx-react/src/story-block/styles.js
Added themes for storybook.
The basic idea comes from the `demo` site implementation, but with a little twist in order to adapt it to storybook:
- Created a base Story Block component in order to abstract the functionality and apply the theme selector to all stories
- Upon clicking on the theme switcher, we remove the stylesheet associated with a specific theme and apply the other one.
- I also added a specific identifier to each injected style in order to make sure that we are only manipulating the styles added by the loader and nothing else.
- …
=> feat(storybook): Added themes

packages/site-demo/package.json, packages/site-demo/src/index.tsx, packages/site-demo/src/layout/DemoBlock.tsx, packages/site-demo/src/layout/utils/useHighlightedCode.ts, packages/site-demo/src/style/demo/_demo-block.scss, packages/site-demo/webpack.config.js, yarn.lock
Replace highlight.js with prism for better TSX code highlighting and a lighter JS bundle
=> chore(demo): replace highlight.js with prism

CHANGELOG.react.md, lerna.json, package.json, packages/lumx-angularjs/package.json, packages/lumx-core/package.json, packages/lumx-icons/package.json, packages/lumx-react/package.json, packages/site-demo/package.json, packages/yo-generators/package.json
Release v0.18.0
Minor tooling fixes: 
- Fixed automatic changelog version script to act **after** the version bump
- Removed `changelog-verify` on CHANGELOG.react.md: 
`changelog-verify` checks that every versions in the changelog contains
changes.
But since we now have a monorepo with a single version system, the
@lumx/react package will sometimes have new version without changes.
=> Release v0.18.0

CHANGELOG.react.md, packages/lumx-react/src/components/autocomplete/Autocomplete.stories.tsx, packages/lumx-react/src/components/autocomplete/Autocomplete.tsx, packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.stories.tsx, packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.tsx, packages/lumx-react/src/hooks/useComputePosition.tsx, packages/lumx-react/src/hooks/useFocusOnClose.tsx, packages/lumx-react/src/hooks/useKeyboardListNavigation.tsx, packages/site-demo/content/product/components/autocomplete/react/multiple.tsx
In this PR, the following changes were introduced:
- Autocomplete and AutocompleteMultiple stories
- When we are using the AutocompleteMultiple, there is a necessity to just display the suggestions with the same size as the input. This implies two changes:
- Tell the Autocomplete component that sometimes we want to anchor the suggestions to the input rather than the wrapper
- `useComputePosition` ignored the `hasParentWidth` parameter when setting the minimum width for the dropdown. This PR changes that in order to ensure that the minimum width is not set when we want to have the same width as the parent
- For the Autocomplete simple, we do not want to focus upon close, so we pass down a prop in order to signal that we do not want to apply the `useFocusOnClose` hook.
- This is all …
=> feat(autocomplete): stories and fixes

packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx
Date picker failed to navigate before March 2019. It was because of the use of hook inside a loop.
=> fix(date-picker): remove hook in loop

packages/lumx-core/src/scss/core/theme/lumapps/_color-palette.scss, packages/lumx-core/src/scss/core/theme/material/_color-palette.scss
Update of yellow color in both theme palette in order to achieve better contrast ratios
=> fix(color palettes): updated yellows for both themes

CHANGELOG.react.md, packages/lumx-react/src/components/autocomplete/Autocomplete.tsx, packages/lumx-react/src/components/autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/lumx-react/src/components/text-field/TextField.test.tsx, packages/lumx-react/src/components/text-field/TextField.tsx, packages/lumx-react/src/index.ts, packages/site-demo/content/product/components/text-field/react/text-area-invalid.tsx, packages/site-demo/content/product/components/text-field/react/text-area-valid.tsx, packages/site-demo/content/product/components/text-field/react/text-area.tsx
The previously defined `type` prop on the `TextField` component prevented the access to the native `type` prop on the input element.
This PR removes the custom `type` prop and add the `multiline` flag prop instead.
=> fix(text-field): fix access to native input type prop

CHANGELOG.md, packages/lumx-react/src/components/list/List.tsx
Remove List component  auto-focus on mount if is clickable.
List focus is handled according the context with the hook.
=> fix(list): remove useless auto-focus on mount if is clickable (LUM-7678)

CHANGELOG.md, packages/lumx-angularjs/src/components/dialog/dialog_directive.js, packages/lumx-angularjs/src/components/notification/notification_service.js, packages/lumx-core/src/js/constants.ts, packages/lumx-react/src/components/dialog/Dialog.tsx, packages/lumx-react/src/components/notification/Notification.test.tsx, packages/lumx-react/src/components/notification/Notification.tsx, packages/lumx-react/src/components/notification/Notifications.stories.tsx, packages/lumx-react/src/components/notification/__snapshots__/Notification.test.tsx.snap, packages/lumx-react/src/components/notification/constants.ts, packages/lumx-react/src/constants.ts, packages/lumx-react/src/hooks/index.tsx, packages/lumx-react/src/hooks/useDelayedVisibility.tsx, packages/site-demo/content/product/components/notification/react/default.tsx
The notification component is visible for a split second even if `isOpen = false`. In order to prevent that, we render `null` when `isOpen = false`
Before:
After:
-   [X] (if fix or feature) Add `need: test` label
=> feat(notification): prevent showing notification when !isOpen

CHANGELOG.md, packages/lumx-react/src/components/link/Link.stories.tsx, packages/lumx-react/src/components/link/Link.test.tsx, packages/lumx-react/src/components/link/Link.tsx, packages/lumx-react/src/components/link/__snapshots__/Link.test.tsx.snap, packages/lumx-react/src/index.ts
Add the React version of the `Link` component.
Only takes a color and a colorVariant, every other props is passed to the `a` tag.
=> feat(link): add React version of Link component

CHANGELOG.md, packages/lumx-react/src/components/avatar/Avatar.tsx, packages/lumx-react/src/components/select/Select.stories.tsx, packages/lumx-react/src/components/select/Select.test.tsx, packages/lumx-react/src/components/select/Select.tsx, packages/lumx-react/src/components/select/__snapshots__/Select.test.tsx.snap, packages/lumx-react/src/index.ts
Added the possibility to detect whether the `Select` component was blurred or not:
- Since the Select is actually not an input, we need to fake the `blur` with a click away
- Updated the main story since it did not change the option selected upon clicking the option …
=> feat(select): allow on Blur

CHANGELOG.md, packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx
Add ReactNode as an allowed type for SideNavigationItem to allow for component as labels.
This is only for typescript support to avoid hacky workarounds.
=> Add ReactNode as an allowed type for SideNavigationItem

CHANGELOG.md, packages/lumx-react/src/components/tabs/Tab.tsx
Add ReactNode as allowed type to Tab label
This is only for typescript support to avoid hacky workarounds.
=> Add ReactNode as allowed type to Tab label

CHANGELOG.md, packages/lumx-react/src/components/text-field/TextField.stories.tsx, packages/lumx-react/src/components/text-field/TextField.test.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
The idea is to be able to handle number type in the TextField component
The onChange accept `any` as a type because it's more simple for the moment.
Maybe we can create a TextFieldValue type that will be string | number
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#r …
=> fix(textfield-value): add the number as the value type

CHANGELOG.md, packages/lumx-react/src/components/tooltip/Tooltip.tsx
Fix blurry Tooltip by rounding the coordinates to the nearest integers.
=> fix(tooltip): rounding coordinates in integer for sharper display

CHANGELOG.md, packages/lumx-react/src/components/side-navigation/SideNavigationItem.test.tsx, packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx
- Added a prop `linkProps` for the `SideNavigationItem` in order to provide additional props to the `a`, more importantly the `href` prop
- The prop was created in order to avoid confusions and mix up with the props related to the `li` on the top level, and differentiate where we want those props to go.
- For some reason I could not add a DEFAULT_PROP for this component, since tests were broken when I added to the `DEFAULT_PROPS` object a prop `linkProps: {}`. See photo in screenshots section …
=> feat(side-navigation-item-link): add props to link in side nav item

CHANGELOG.md, packages/lumx-react/src/components/select/Select.stories.tsx, packages/lumx-react/src/hooks/useInfiniteScroll.tsx
For autocompletes and select with infinite scroll, when there is enough place on screen to display the first batch of results, making the container unscrollable, it becomes impossible to trigger the infinite scroll.
The fix : When the container is displayed we check if the last item is visible, if so, we call the infinite scroll callback.  …
=> fix(infinite-scroll): trigger infinite when container is fully displayed

CHANGELOG.md, packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
- From the new Search UI, we want to add fallbacks to our images, since we have several scenarios where the images that we show are broken/not found.
- Therefore, we want to add a prop to Thumbnail that passes additional attributes to the `img` tag, so we can add, for example, an `onError`.
[react dev check …
=> feat(thumbnail): Img props

CHANGELOG.md, packages/lumx-react/src/components/link-preview/LinkPreview.tsx
Added the `thumbnailProps`  prop to the `LinkPreview` component to be able to control the thumbnail's props.
=> feat(link-preview): added isThumbnailCrossOriginEnabled prop

packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.stories.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
In autocomplete, chips were put before the right icon.
=> fix(textfield): put chips after icon

CHANGELOG.md, packages/lumx-react/src/components/mosaic/Mosaic.stories.tsx, packages/lumx-react/src/components/mosaic/Mosaic.test.tsx, packages/lumx-react/src/components/mosaic/Mosaic.tsx, packages/lumx-react/src/components/mosaic/__snapshots__/Mosaic.test.tsx.snap
Fixed Mosaic elements showing as clickable even though `onClick` wasn't defined
**Before**
**Now**
=> fix(mosaic): fix thumbnails showing as clickable

CHANGELOG.md, packages/lumx-react/src/components/autocomplete/Autocomplete.tsx, packages/lumx-react/src/components/dropdown/Dropdown.tsx
Autocomplete and Dropdown's interfaces had the prop called `onInfinite` but in the components themselves, the prop was called `onInfiniteScroll`.
[In the Interface](https://github.com/lumapps/design-system/blob/master/packages/lumx-react/src/components/autocomplete/Autocomplete.tsx#L147) 
[In the Component props](https://github.com/lumapps/design-system/blob/master/packages/lumx-react/src/components/autocomplete/Autocomplete.tsx#L224)
(Same for Dropdown Component)
Fixed issue described above. …
=> fix Interface typo onInfinite to onInfiniteScroll for Autocomplete and Dropdown

CHANGELOG.md, packages/lumx-react/src/components/text-field/TextField.tsx
When `TextField` had `isClearable` set at `true` and is the only field of a form without another submit button, pressing enter triggered the `onClear` action.
Fixed by setting the button type to "button".
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react-developpme …
=> fix(text-field): fix clear button type

CHANGELOG.md, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx, packages/lumx-react/src/components/thumbnail/useFocusedImage.tsx, packages/lumx-react/src/hooks/index.tsx, packages/lumx-react/src/hooks/useFocusedImage.tsx, packages/lumx-react/src/hooks/useImage.tsx
-   Added optional `fallback` prop (svg string or react node) to component `Thumbnail`.
-   Added `useImage` hook to preload an image and get states from it (isLoaded and hasError).
-   Moved `useFocusedImage` to `hooks` folder.
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBU …
=> feat(react-thumbnail): add fallback to images

CHANGELOG.md, packages/lumx-react/src/components/text-field/TextField.stories.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
Fix https://lumapps.atlassian.net/browse/LUM-9878
When we have a TextField multiple with content in many lines, the component only displays the `minimum rows`.
This PR call the function used to compute the number of rows directly instead of waiting for change. …
=> Fix/LUM-9878 Textarea nb rows

CHANGELOG.md, packages/lumx-react/src/components/date-picker/DatePicker.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.stories.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.test.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.tsx, packages/lumx-react/src/components/date-picker/DatePickerValueProp.ts, packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerField.test.tsx.snap
Allow `<DatePicker />` and `<DatePickerField />` to accept a javascript Date object as property.
=> DatePicker and DPField accept a Date object

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/lumapps/_index.scss, packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
-   Fix centering issue on fallback icon in `Thumbnail` component when using `fillHeight`prop.
-   Handle default size on fallback icon in `Thumbnail` component (Size.m).
=> fix(react-thumbnail): fix centering issue on fallback and add a default size 

packages/lumx-react/src/components/text-field/TextField.stories.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
In the previous PR https://github.com/lumapps/design-system/pull/403
We have fixed the UI for the TextField multiline.
But a side-effect was found in the sa-programs form component in the product.
This PR resolve this error by using the `minimumRows` as fallback
Moreover we recompute the number of rows every-time that the value change.
So we removed the function call from the "handleChange" since the effect is applied when necessary 
Check out the [contribution guide] for general guidelines for …
=> fix(textfield): check computation result

CHANGELOG.md, packages/lumx-react/src/components/date-picker/DatePickerField.tsx, packages/lumx-react/src/components/dialog/Dialog.stories.tsx, packages/lumx-react/src/components/dialog/Dialog.tsx, packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap, packages/lumx-react/src/components/dropdown/Dropdown.tsx, packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/lumx-react/src/hooks/useClickAway.tsx, packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.stories.tsx, packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.tsx, packages/lumx-react/src/utils/ClickAwayProvider/index.ts, packages/lumx-react/src/utils/type.ts
Fix nested click away
This fixes the dialog automatically closing when clicking on a nested select or dropdown.
1. run `yarn && yarn storybook:react`
2. Go to http://localhost:9000/?path=/story/lumx-components-dialog--dialog-with-focusable-elements
3. Click in the select at the bottom of the dialog
=> A value should be selected and the dialog should not close
5. Click outside the dialog
=> The dialog should close normally
=> fix nested click away

CHANGELOG.md, packages/lumx-react/src/components/select/Select.tsx
Fix position of the dropdown arrow icon when the select has no value
1. run `yarn && yarn storybook:react`
2. Go to http://localhost:9000/?path=/story/lumx-components-dialog--dialog-with-focusable-elements
3. The select should like the screenshot below (screenshots > after)
**Before**
**After**
=> fix(select): fix arrow icon on empty selection

packages/lumx-react/.storybook/story-block/useInjectTheme.ts
Fix lumapps/material theme switcher on storybook.
1. run `yarn && yarn storybook:react`
2. Go to localhost:9000
3. Make sure the default theme is lumapps and when you switch to material, the theme is correclty applied
=> fix(storybook): fix lumapps/material theme switcher

CHANGELOG.md, packages/lumx-core/src/scss/core/generated/lumapps/_variables.scss, packages/lumx-core/src/scss/core/generated/material/_variables.scss, packages/lumx-core/style-dictionary/config/gen-scss-variables.js, packages/lumx-core/style-dictionary/config/gen-ts-variables.js, packages/lumx-core/style-dictionary/config/utils/_genHeader.js
The default generated SCSS color map generated by the style dictionary lib could be overridden and thus the grey color (existing in the material theme only) could not be accessed.
This resulted in the material grey icon not being correctly colored. 
This PR fixes this by creating a custom style dictionary SCSS format identical to the `scss/map-deep` format but with an extra `!default` tag added on the generated SCSS map variable.
=> fix: create custom SCSS format to fix grey icon style on material

CHANGELOG.md, packages/lumx-react/src/components/link-preview/LinkPreview.tsx
Typescript threw an error when the `thumbnailProps` prop from the `LinkPreview` component didn't have an `image` value.
This could be fixed by setting the `image` field with any value, but that's not very pretty :sweat_smile: 
```
<LinkPreview
size={Size.big}
url={url}
thumbnail={images[0]}
title={title}
description={description}
thumbnailProps={{
isCrossOriginEnabled: false,
image: '',
}}
/>
```
This PR fixes the typing by omitting all thumbnail props that are already set by the component.
This will however break any component that used the `image: ''` hack, since it is now an omitted value... 
-   [x] (if …
=> fix(link-preview): fix thumbnailProps typing

CHANGELOG.md, packages/lumx-react/src/components/chip/Chip.stories.tsx, packages/lumx-react/src/components/chip/Chip.test.tsx, packages/lumx-react/src/components/chip/Chip.tsx
Fix https://lumapps.atlassian.net/browse/LUM-9356
1. run `yarn && yarn storybook:react`
2. Go to http://localhost:9000/?path=/story/lumx-components-chip--with-after-and-before
3. Click on the list icon before the chip text (=> you should see "Clicked on chip")
4. Click on the chip text (=> you should see "Clicked on chip")
5. Click on the close icon after the chip text (=> you should see "Clicked on close")
=> fix(chip): fix click propagation on after/before

CHANGELOG.md, packages/lumx-core/src/js/date-picker.ts, packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.stories.tsx, packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerControlled.test.tsx.snap
fix the display of the calendar. 
Number of weeks were not well compute by `moment-range` 
=> FIX/LUM-10327: Date picker weeks display

CHANGELOG.md, packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx, packages/lumx-react/src/components/tooltip/Tooltip.tsx
- Handle multiline in tooltip
- Tooltip with empty/undefined/null label is not displayed
=> feat(tooltip): handle multiline and empty cases

packages/lumx-core/src/scss/core/border-radius/lumapps/_variables.scss
In material design theme, default border radius should be 2px and was 4px
Correct border radius (2px) shown on the button component 
=> fix(material default border-radius): border radius in material design theme

CHANGELOG.md, packages/lumx-react/src/components/autocomplete/Autocomplete.stories.tsx, packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.stories.tsx, packages/lumx-react/src/components/autocomplete/Demos.stories.tsx, packages/lumx-react/src/components/autocomplete/demos, packages/lumx-react/src/components/list/useInteractiveList.tsx, packages/site-demo/content/product/components/autocomplete/react/default.tsx
`ListItem` now properly keep the given `isHighligthed` prop value when controlled from a parent component. (Fixes `Autocomplete` & `AutocompleteMultiple` keyboard arrow navigation in the completed suggestions)
=> fix: list controlled highlighted state

packages/site-demo/webpack-loader/props-loader/convertPropTable.js
A little fix to render the components props on the demo site 
**Before**
****
**After**
=> fix demo site script to render props correctly

packages/site-demo/content/product/components/button/index.mdx, packages/site-demo/webpack-loader/props-loader/convertPropTable.js
Do not filter components based on name in demo site build to have buttonRoot component available and be able to add it to the button doc as it contains most of the usefull button props.
Also add IconButton doc
Title in the button doc may have to be updated for clarity sake ?
**Before**
**After**
=> docs(build): do not filter component based on name

CHANGELOG.md, packages/lumx-core/src/scss/components/tooltip/lumapps/_index.scss, packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx, packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/__snapshots__/Tooltip.test.tsx.snap, packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
Fix tooltip on disabled anchor element.
=> fix(tooltip): make tooltip work on disabled anchor

CHANGELOG.md, packages/lumx-react/src/components/mosaic/Mosaic.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
Added `ThumbnailProps` props to the `MosaicElement` interface to be able to forward those props to the `Thumbnail` component inside the `Mosaic`component.
=> fix(mosaic): fix missing CORS props for Thumbnails

CHANGELOG.md, packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
In order to improve the accessibility, I propose to add this behavior.
When a keyboard user is focusing an icon, the tooltip is displayed.
-   [] (if has style) Add `need: review-integration` label
=> Tooltip a11y - display the tooltip on focus

CHANGELOG.md, packages/lumx-react/src/components/dropdown/Dropdown.tsx
Added `fitWithinViewportHeight` prop on the `Dropdown` to disable the height shrinking
=> feat(dropdown): add fitWithinViewportHeight prop

CHANGELOG.md, packages/lumx-react/src/components/side-navigation/SideNavigation.stories.tsx, packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx, packages/lumx-react/src/components/side-navigation/__snapshots__/SideNavigationItem.test.tsx.snap
LUM-11702
The goal of this PR is to provide a dedicated click on the `IconButton` and still have an onClick action on the item.
Why?
In the new react app, I need to have a `linkProps` in order to redirect the user to the proper page. AND also an `onClick` action to close the drawer. 
If in this scenario my item have children, I need an action to only open/close the children wrapper.
The new prop is called `onActionClick` but feel free to change the name.
Check out the [contribution guide] for …
=> Fix SideNavigationItem split-actions

packages/site-demo/src/index.tsx
Fix inclusion of the 'focus-visible' lib in the demo site.
=> chore(site-demo): fix focus visible lib import

.eslintrc.js, CHANGELOG.md, packages/lumx-icons/font.scss, packages/lumx-icons/index.d.ts, packages/lumx-icons/index.js, packages/lumx-icons/package.json, yarn.lock
Upgrade to mdi 5.6.55 and handle breaking changes.
To remember when upgrading into LumApps product:
- mdiFacebookBox (to remove from icon picker)
- mdiGithubFace (to remove from icon picker)
- mdiLinkedinBox (to remove from icon picker)
- mdiTwitterBox (to remove from icon picker)
- mdiGooglePlusBox (don't exists anymore) …
=> Chore/upgrade mdi 5.6.55

packages/site-demo/src/components/LumxVersion.tsx, packages/site-demo/src/components/layout/Main.tsx, packages/site-demo/src/index.html.ejs, packages/site-demo/webpack.config.js
Add the lumx version on the component demo pages.
It also links to the CHANGELOG of this version on github.
=> chore(site-demo): display the lumx version on component demo pages

CHANGELOG.md, packages/lumx-react/src/components/link/Link.stories.tsx, packages/lumx-react/src/components/link/Link.tsx, packages/lumx-react/src/components/list/ListItem.stories.tsx, packages/lumx-react/src/components/list/ListItem.tsx, packages/lumx-react/src/components/list/__snapshots__/ListItem.test.tsx.snap, packages/lumx-react/src/components/side-navigation/SideNavigation.stories.tsx, packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx, packages/lumx-react/src/utils/renderLink.tsx
Having `<a>` internallized in our components makes it difficult to implement good a11y with frontend routed link (i.e. using `Link` component from `react-router`).
This PR adds a `linkAs` prop on `SideNavigationItem`, `ListItem` and `Link` to customize the link component.
This can be used with `react-router` like this:
```jsx
<Link linkAs={ReactRouter.Link} to="/" ... >
<ListItem linkAs={ReactRouter.Link} linkProps={{ to: '/' }} ... >
<SubNavigationItem linkAs={ReactRouter.Link} linkProps={{ to: '/' }} ... >
```
=> chore(link-a11y): add `linkAs` prop on component with links

packages/site-demo/content/product/components/link-preview/index.mdx
Added the theme switcher on the demo block to see the dark themed link-preview.
=> docs(link-preview): added theme switcher on demo

packages/site-demo/content/product/components/link/index.mdx, packages/site-demo/content/product/components/link/react/default.tsx, packages/site-demo/content/product/components/link/react/implicit.tsx, packages/site-demo/content/product/components/link/react/sizes.tsx
Fixed text, added icon size explanation
=> docs(link): updated text and demo blocks

packages/site-demo/content/product/components/link-preview/index.mdx, packages/site-demo/content/product/components/link-preview/react/big.tsx
Changed text and added demo for the size `big`
=> docs(link-preview): added big size docs

CHANGELOG.md, packages/lumx-react/src/components/list/List.stories.tsx, packages/lumx-react/src/components/list/__snapshots__/List.test.tsx.snap, packages/lumx-react/src/components/list/useInteractiveList.tsx
LUM-12841
Fix `List` component triggering an infinite loop when using keyboard navigation an custom children. 
To test : 
* Launch storybook
* Go to http://localhost:9000/?path=/story/lumx-components-list-list--with-custom-children
* Focus first element
* Use down / up arrows to try to navigate.
* Browser tab should not freeze. …
=> fix(list): fix infinite loop on keyboard navigation

CHANGELOG.md, packages/lumx-react/src/utils/ClickAwayProvider/ClickAwayProvider.tsx
Delay click away provider init to remove the error appearing since the last React update.
=> chore(click-away): fix ClickAwayProvider initialization error

CHANGELOG.md, packages/lumx-core/src/scss/components/link/lumapps/_mixins.scss, packages/lumx-react/src/components/button/Button.stories.tsx, packages/lumx-react/src/components/button/ButtonRoot.tsx, packages/lumx-react/src/components/index.ts, packages/lumx-react/src/components/link/Link.stories.tsx, packages/lumx-react/src/components/link/Link.test.tsx, packages/lumx-react/src/components/link/Link.tsx, packages/lumx-react/src/components/link/__snapshots__/Link.test.tsx.snap
- A `Link` component without an `href` would result in a button looking like a link instead of an anchor.
- Added `typography` prop to `Link` component.
=> refactor(link): add button alternative and typo prop LUM-11250

CHANGELOG.md, packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx, packages/lumx-react/src/components/image-block/ImageBlock.tsx, packages/lumx-react/src/components/mosaic/Mosaic.stories.tsx, packages/lumx-react/src/components/mosaic/Mosaic.test.tsx, packages/lumx-react/src/components/mosaic/Mosaic.tsx, packages/lumx-react/src/components/post-block/Demos.stories.tsx, packages/lumx-react/src/components/post-block/demos, packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx, packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx, packages/site-demo/content/product/components/image-block/react/default.tsx, packages/site-demo/content/product/components/image-block/react/image-block-above.tsx, packages/site-demo/content/product/components/image-block/react/image-block-alignment.tsx, packages/site-demo/content/product/components/image-block/react/image-block-padding.tsx, packages/site-demo/content/product/components/slideshow/react/auto.tsx, packages/site-demo/content/product/components/slideshow/react/default.tsx, packages/site-demo/content/product/components/slideshow/react/group.tsx
-   _[BREAKING]_ `onClick` prop for `Mosaic.thumbnail` prop is no longer automatically passing the index.
-   _[BREAKING]_ `align`, `aspectRatio`, `crossOrigin`, `fillHeight`, `focusPoint`, `isCrossOriginEnabled` and `onClick` props have been removed from `ImageBlock` component. These props will now be passed using the `ImageBlock.thumbnailProps` prop. …
=> refactor(image-block-and-mosaic): move thumbnail props

CHANGELOG.md, packages/lumx-react/src/components/date-picker/DatePicker.test.tsx, packages/lumx-react/src/components/date-picker/DatePicker.tsx, packages/lumx-react/src/components/date-picker/DatePickerControlled.test.tsx, packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.stories.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.test.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.tsx, packages/lumx-react/src/components/date-picker/DatePickerValueProp.ts, packages/lumx-react/src/components/date-picker/__snapshots__/DatePicker.test.tsx.snap, packages/lumx-react/src/components/date-picker/__snapshots__/DatePickerField.test.tsx.snap
-   _[BREAKING]_ `DatePicker` and `DatePickerField` `value` prop can no longer be a `Moment` object. This will allow us to remove `moment` dep in the future without generating breaking change later. The `value` prop can no longer be a `string` to avoid handling incompatible values. `value` can only be a `Date` (or `undefined` for non selectable values). …
=> refactor(date-picker): value prop should be a date LUM-13240

packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx, packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
=> fix(tooltip): tooltip now closes on escape LUM-12976

CHANGELOG.md, packages/lumx-core/src/scss/components/popover/lumapps/_index.scss, packages/lumx-react/package.json, packages/lumx-react/src/components/dropdown/Dropdown.tsx, packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/lumx-react/src/components/popover/Popover.stories.tsx, packages/lumx-react/src/components/popover/Popover.tsx, yarn.lock
=> Fix popover bugs

CHANGELOG.md, packages/lumx-core/src/js/utils.ts, packages/lumx-react/src/components/list/List.tsx, packages/lumx-react/src/components/list/ListItem.tsx, packages/lumx-react/src/components/list/useInteractiveList.tsx
Forward both on click and on enter key press event in the `onListItemSelected` (List component) callback and  `onItemSelected` callback (ListItem component)
=> fix(list): forward on item selected event

CHANGELOG.md, packages/lumx-angularjs/src/components/comment-block/comment-block.html, packages/lumx-core/src/scss/components/comment-block/lumapps/_index.scss, packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx, packages/lumx-react/src/components/comment-block/CommentBlock.tsx, packages/site-demo/content/product/components/comment-block/react/threaded.tsx
CMS-337
* Added `headerActions` prop to the `CommentBlock` component to make it possible to add a contextual menu to comments.
* Fixed `text` prop on the `CommentBlock` component to accept `ReactNode`.
-   [x] (if ha s code) Add `need: review-frontend` label
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react-developpment …
=> feat(comment-block): add header actions prop

.github/workflows/chromatic.yaml
Build chromatic on push version tag instead of on push branch
=> chore(ci): build chromatic on tag rather than on push branch

CHANGELOG.md, packages/lumx-react/src/components/select/Select.test.tsx, packages/lumx-react/src/components/select/Select.tsx
In the product I need to pass some additional data to the select, such as `data-id`
=> fix(select): forward-props

CHANGELOG.md, packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx, packages/lumx-react/src/components/comment-block/CommentBlock.tsx, packages/lumx-react/src/components/progress/Progress.tsx, packages/lumx-react/src/components/select/constants.ts, packages/lumx-react/src/components/skeleton/SkeletonRectangle.tsx, packages/lumx-react/src/components/table/TableCell.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx, packages/lumx-react/src/components/uploader/Uploader.tsx, packages/site-demo/content/product/components/comment-block/react/default.tsx, packages/site-demo/content/product/components/comment-block/react/relevant.tsx, packages/site-demo/content/product/components/comment-block/react/threaded.tsx
- Added `variant` prop for `CommentBlock` component (either `indented` by default or `linear`).
- _[BREAKING]_ `hasChildren` and `hasIndentedChildren` props for `CommentBlock` component have been removed.
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react-developpme …
=> refactor(comment-block): add variant and remove useless props LUM-13511

CHANGELOG.md, packages/lumx-icons/README-v4-to-v5-migration.md, packages/lumx-icons/font.scss, packages/lumx-icons/index.d.ts, packages/lumx-icons/index.js, packages/lumx-icons/package.json, packages/lumx-icons/v4-to-v5-aliases.d.ts, packages/lumx-icons/v4-to-v5-aliases.js, packages/lumx-icons/v4-to-v5-aliases.scss, packages/site-demo/content/product/components/uploader/react/default.tsx, yarn.lock
Upgrade `mdi` to 5.6.55 and handle backward compatibility.
`mdi` has been upgraded to v5x first in [v0.26.0](https://github.com/lumapps/design-system/releases/tag/v0.26.0) but then downgraded back to v4x in [v0.26.1](https://github.com/lumapps/design-system/releases/tag/v0.26.1) for stability purpose.
To remember when upgrading into LumApps product:
mdiFacebookBox (to remove from icon picker)
mdiGithubFace (to remove from icon picker)
mdiLinkedinBox (to remove from icon picker)
mdiTwitterBox (to remove from icon picker)
mdiGooglePlusBox (don't exists anymore)
-   [x] (if has react) Check through the [react …
=> chore: upgrade to mdi 5.8.55 and handle backward compatibility LUM-12974

CHANGELOG.md, packages/lumx-core/src/scss/components/avatar/_index.scss, packages/lumx-react/src/components/avatar/Avatar.stories.tsx, packages/lumx-react/src/components/avatar/Avatar.test.tsx, packages/lumx-react/src/components/avatar/Avatar.tsx, packages/lumx-react/src/components/avatar/__snapshots__/Avatar.test.tsx.snap, packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx, packages/lumx-react/src/components/comment-block/CommentBlock.tsx, packages/lumx-react/src/components/user-block/UserBlock.stories.tsx, packages/lumx-react/src/components/user-block/UserBlock.tsx, packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap, packages/site-demo/content/product/components/avatar/react/actions.tsx, packages/site-demo/content/product/components/avatar/react/default.tsx, packages/site-demo/content/product/components/badge/react/icon.tsx, packages/site-demo/content/product/components/badge/react/label.tsx, packages/site-demo/content/product/components/comment-block/react/default.tsx, packages/site-demo/content/product/components/comment-block/react/relevant.tsx, packages/site-demo/content/product/components/comment-block/react/threaded.tsx, packages/site-demo/content/product/components/list/react/big.tsx, packages/site-demo/content/product/components/list/react/huge.tsx, packages/site-demo/content/product/components/list/react/regular.tsx, packages/site-demo/content/product/components/list/react/tiny.tsx, packages/site-demo/content/product/components/post-block/react/default.tsx, packages/site-demo/content/product/components/user-block/react/extended.tsx, packages/site-demo/content/product/components/user-block/react/size-l.tsx, packages/site-demo/content/product/components/user-block/react/size-m.tsx, packages/site-demo/content/product/components/user-block/react/size-s.tsx, packages/site-demo/content/product/components/user-block/react/vertical.tsx
-   _[BREAKING]_ The alternative text is now required ([...], `alt` prop in `Avatar`, `avatarProps.alt` in `CommentBlock` and `avatarProps.alt` in `userBlock`).
-   `Avatar` component now uses `Thumbnail` component.
-   _[BREAKING]_ Since `alt` in now required for `Avatar`, `avatar` and `avatarProps` props have been merged into `avatarProps` for both `CommentBlock` and `UserBlock`.
[contribution …
=> refactor(avatar): use thumbnail inside avatar LUM-11237

packages/lumx-icons/v4-to-v5-aliases.d.ts, packages/lumx-icons/v4-to-v5-aliases.js, packages/lumx-icons/v4-to-v5-aliases.scss
Some icons appear to have changed content but still
have an equivalent in v5 so they don't need to be aliased.
=> chore(icons): fix v4 to v5 icon aliases

CHANGELOG.md, packages/lumx-react/src/components/dropdown/__snapshots__/Dropdown.test.tsx.snap, packages/lumx-react/src/components/popover/Popover.stories.tsx, packages/lumx-react/src/components/popover/Popover.tsx
Added `usePortal` prop to `Popover` component (default value is `true`) to be able to not use a portal in some cases
=> feat(popover): add usePortal prop to skip portal in some case

CHANGELOG.md, packages/lumx-react/src/components/table/__snapshots__/Table.test.tsx.snap, packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx, packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
`mouseenter`/`mouseleave` event on the tooltip anchor element do not trigger when an element appear between the anchor element and the mouse
The solution implemented here is to put a `mouseover` event listener on the `document` and check that the element currently being hovered is one of the anchors of the registered tooltips to open and close them.
=> fix(tooltip): fix closing on covered anchor

.docker/nginx.conf
Handle properly the prefix-based routing (`/lumapps-cp/`, `/lumapps-prod/` and `/`).
=> chore(demo): Handle prefix-based routing

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_index.scss, packages/lumx-react/src/components/badge/Badge.stories.tsx, packages/lumx-react/src/components/index.ts, packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx, packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap, packages/lumx-react/src/components/thumbnail/useFocusPoint.ts, packages/lumx-react/src/stories/knobs/sizeKnob.ts
- Add `badge` prop to `Thumbnail`
- Add style to create a transparent border around the thumbnail badge (only works on fixed size thumbnails)
<details>
<summary>Badge mask adapting to fixed size thumbnails</summary>
</details>
<details>
<summary>Badge mask transparency</summary>
</details>
=> feat(thumbnail): add thumbnail badge

CHANGELOG.md, packages/lumx-react/src/components/progress-tracker/ProgressTracker.stories.tsx, packages/lumx-react/src/components/progress-tracker/ProgressTrackerProvider.tsx, packages/lumx-react/src/components/tabs/TabProvider.tsx, packages/lumx-react/src/components/tabs/Tabs.stories.tsx
The default props for TabProvider and ProgressTrackerProvider was preventing the onChange to be called when the parent component doesn't update the `activeTabIndex` prop.
This PR removes the active index default prop (the reducer initial state already initializes the index correctly).
Test scenario:
- Check "Tabs > Not controlled" story.
- Clicking on any tabs should log it's index in the console.
- Repeat the test on "Progress tracker > Not controlled" story.
=> fix(tabs): remove default props preventing onChange from being called

CHANGELOG.md, packages/lumx-react/src/components/checkbox/Checkbox.test.tsx, packages/lumx-react/src/components/checkbox/Checkbox.tsx, packages/lumx-react/src/components/checkbox/__snapshots__/Checkbox.test.tsx.snap, packages/lumx-react/src/components/radio-button/RadioButton.test.tsx, packages/lumx-react/src/components/radio-button/RadioButton.tsx, packages/lumx-react/src/components/radio-button/__snapshots__/RadioButton.test.tsx.snap, packages/lumx-react/src/components/table/TableRow.tsx
-   Make `TableRow` component's `tabIndex` controllable
-   Use `uid` instead of `uniqueid` for `Checkbox` default id.
-   Use `uid` instead of `uniqueid` for `RadioButton` default id.
=> fix(table-row): move tabIndex above forward props spread

CHANGELOG.md, packages/lumx-react/src/components/popover/Popover.stories.tsx, packages/lumx-react/src/components/popover/Popover.tsx
Make it possible to give a custom element reference to the Popover element to change boundary element.
**Before**
**After**
=> feat(popover): add boundaryRef prop to change overflow boundary

CHANGELOG.md, packages/lumx-react/src/components/button/IconButton.tsx
LUM-13715
-   Added `showTooltip` prop to `IconButton` component to control whether the tooltip should be displayed or not. 
Default at `true`.
- Changed `IconButton` jsdoc.
=> feat(icon-button): add showTooltip prop

CHANGELOG.md, packages/lumx-react/src/components/select/WithSelectContext.tsx, packages/lumx-react/src/hooks/useListenFocus.tsx
The focus state of the select was not activating using keyboard navigation and would not deactivate when clinking outside the select. 
I'm refactoring the hook used to listen to this state using a correct element reference.
**Tests:**
Example page: https://5fbfb1d508c0520021560f10-tyxrbjhdfg.chromatic.com/?path=/story/lumx-components-dialog-dialog--dialog-with-focusable-elements
1. Check the select get the focus correctly using Tab key nav or directly clicking on it
2. Check the select looses the focus when clicking outside or navigating to another focusable element
=> fix(select): fix focus state not updating properly

CHANGELOG.md, packages/lumx-core/src/scss/components/input-label/_index.scss, packages/lumx-react/src/components/autocomplete/Autocomplete.test.tsx, packages/lumx-react/src/components/autocomplete/Autocomplete.tsx, packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.test.tsx, packages/lumx-react/src/components/autocomplete/AutocompleteMultiple.tsx, packages/lumx-react/src/components/autocomplete/__snapshots__/Autocomplete.test.tsx.snap, packages/lumx-react/src/components/autocomplete/__snapshots__/AutocompleteMultiple.test.tsx.snap
The asterisk of a required label was too close to the label. So we add a tiny space.
And the props was not supported by the `Autocomplete` and `AutocompleteMultiple` components so we add the support of the props.
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react-de …
=> fix(input-field): fix isRequired props ui and support

CHANGELOG.md, packages/lumx-react/package.json, packages/lumx-react/src/hooks/useDisableBodyScroll.ts, yarn.lock
Fix bug in which the window would scroll to top when opening a dialog or lightbox (if the `<html>` element has an overflow style).
Fixing it by changing the overflow style temporarly while the dialog/lightbox is open.
=> fix(modal): fix unexpected scroll to top on dialog/lightbox open

CHANGELOG.md, packages/lumx-react/src/components/switch/Switch.tsx, packages/lumx-react/src/components/switch/__snapshots__/Switch.test.tsx.snap
This PR adds a role to the switch input element (checkbox) to enable screen readers to know that's a switch.
This will make is so the screen reader will tell `switch` instead of `checkbox`
Idea comes from this video: https://youtu.be/_KqccADghcA?t=176
Or this article: https://web.dev/building-a-switch-component/
-   [] (if has style) Add `need: review-integration` label …
=> feat(switch): add role switch for screen readers behavior

CHANGELOG.md, packages/lumx-react/src/components/message/Message.stories.tsx, packages/lumx-react/src/components/message/Message.tsx
Add `icon` prop to the `Message` component to make the icon customizable.
=> feat(message): add icon prop to cutomize the icon

CHANGELOG.md, packages/lumx-react/src/hooks/useInfiniteScroll.tsx
Add a margin of error to trigger the infinite scroll, so that it work on every browser resolution/zoom
Trigger the scroll when the difference is <= 5px
-   [X] (if fix or feature) Add `need: test` label
=> fix(use-infinite-scroll): add error margin to trigger the scroll

CHANGELOG.md, packages/lumx-react/src/components/dialog/Dialog.tsx
SUP-452
Use the content div as reference of `useDisableBodyScroll` instead of the wrapper.
This will fix the scrolling issues noticed on IOS devices that made it impossible to scroll inside dialogs using one finger.
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react …
=> fix(dialog): set disable scroll on content

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_variables.scss, packages/lumx-react/src/components/index.ts, packages/lumx-react/src/components/skeleton/SkeletonRectangle.stories.tsx, packages/lumx-react/src/components/skeleton/SkeletonRectangle.tsx, packages/lumx-react/src/components/skeleton/__snapshots__/SkeletonRectangle.test.tsx.snap
Add `wide` 16/9 aspect ratio for `Thumbnail`, `Uploader` and `SkeletonRectangle`.
=> feat(aspect-ratio): add wide aspect ratio

CHANGELOG.md, packages/lumx-react/src/components/button/IconButton.test.tsx, packages/lumx-react/src/components/button/IconButton.tsx, packages/lumx-react/src/components/button/__snapshots__/IconButton.test.tsx.snap
Fixed `IconButton` typing by making both `icon` and `image` props conditional.
This fixes an issue that would occur when extending the interface and forwarding parent props to a children `IconButton`.
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react-developpment-c …
=> fix(icon-button): simplify typing

CHANGELOG.md, packages/lumx-core/src/scss/components/button/_index.scss, packages/lumx-core/src/scss/components/button/_mixins.scss, packages/lumx-react/src/components/button/Button.stories.tsx, packages/lumx-react/src/components/button/Button.tsx, packages/lumx-react/src/components/button/ButtonRoot.test.tsx, packages/lumx-react/src/components/button/ButtonRoot.tsx, packages/lumx-react/src/components/button/__snapshots__/ButtonRoot.test.tsx.snap, packages/lumx-react/src/stories/generated/Button/Demos.stories.tsx, packages/lumx-react/src/stories/generated/Button/full-width.tsx, packages/site-demo/content/product/components/button/index.mdx, packages/site-demo/content/product/components/button/react/full-width.tsx
Add a `fullWidth` prop on `Button` to make it as big as available
<details>
<summary>Bonus: added stories for all button/icon button variations</summary>
</details>
-   [X] (if has style) Add `need: review-integration` label
-   [X] (if has textual documentation) Add `need: review-doc` label
-   [X] (if fix or feature) Add `need: test` label
=> feat(button): allow button to take available width

CHANGELOG.md, packages/lumx-core/src/scss/components/text-field/_index.scss, packages/lumx-core/src/scss/components/text-field/_mixins.scss, packages/lumx-react/src/components/avatar/Avatar.stories.tsx, packages/lumx-react/src/components/button/Button.stories.tsx, packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx, packages/lumx-react/src/components/dialog/Dialog.stories.tsx, packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx, packages/lumx-react/src/components/link-preview/LinkPreview.stories.tsx, packages/lumx-react/src/components/skeleton/SkeletonRectangle.stories.tsx, packages/lumx-react/src/components/text-field/TextField.stories.tsx, packages/lumx-react/src/components/text-field/TextField.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx, packages/lumx-react/src/components/user-block/UserBlock.stories.tsx, packages/lumx-react/src/stories/knobs/buttonKnob.ts, packages/lumx-react/src/stories/knobs/emphasisKnob.ts, packages/lumx-react/src/stories/knobs/index.ts
Add an `afterElement` prop on the `TextField` to add custom elements at the end of a textfield.
https://www.figma.com/file/oBsCET5MB3dQMDkBAc214t/DS%3A-LumApps?node-id=1853%3A27
| Material theme | Lumapps theme |
| --- | --- |
| ![localhost_9000_iframe html_id=lumx-components-text-field-textfield--with-after-element](https://user-images.githubusercontent.com/939567/140938712-d5bb544b-281c-445b-acae-96e7c5f622d1.png) | ![localhost_9000_iframe html_id=lumx-components-text-field-textfield--with-after-element (1)](https://user-images.githubusercontent.com/939567/140938721-4b24075d-5cc7-45bf-a599-6b46d54dffb5.png) |
=> feat(text-field): add `afterElement` prop

CHANGELOG.md, packages/lumx-core/src/js/utils.ts, packages/lumx-react/src/components/list/List.stories.tsx, packages/lumx-react/src/components/list/ListItem.stories.tsx, packages/lumx-react/src/components/list/ListItem.tsx, packages/lumx-react/src/components/list/__snapshots__/List.test.tsx.snap, packages/lumx-react/src/components/list/__snapshots__/ListItem.test.tsx.snap
Improve a11y role and keyboard activation on link list item (with `linkProps.href` or `linkAs` prop) and button list item (with `onItemSelected` prop)
=> fix(list-item): improve a11y on button vs link behavior

CHANGELOG.md, packages/lumx-react/src/components/dialog/Dialog.stories.tsx, packages/lumx-react/src/components/dialog/Dialog.tsx, packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
Changed the method of focusing the dialog's parent element (the element that triggered the dialog to open) to trigger focus every time the dialog is closed and not only when user presses escape or clicks away.
[react dev check list]: https://github.com/lumapps/design-system/blob/master/CONTRIBUTING.md#react-devel …
=> fix(dialog): focus parent on dialog close

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_index.scss, packages/lumx-core/src/scss/components/user-block/_index.scss, packages/lumx-react/src/components/avatar/Avatar.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx, packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap, packages/lumx-react/src/components/user-block/UserBlock.stories.tsx, packages/lumx-react/src/components/user-block/UserBlock.tsx, packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
This PR aims to resolve accessibility issues on UserBlock components. We needed to let Thumbnail handle the clickable behaviour. 
Also add a `linkProps` prop to UserBlock, Avatar and Thumbnail, in order to handle accessible links, before we were forced to use `onClick` which is not good for accessibility.
[react …
=> [a11y] Add linkProps to Thumbnail/Avatar/UserBlock

CHANGELOG.md, packages/lumx-react/src/components/lightbox/Lightbox.stories.tsx, packages/lumx-react/src/components/lightbox/Lightbox.tsx
The Lightbox component was focusing a parent element even if the lightbox was not open previously.
- Test the Lightbox component on storybook on lightbox/Lightbox/Focus ([local url](http://localhost:9000/?path=/story/lumx-components-lightbox-lightbox--focus))
- Write a letter on the textfield
- Check that the focus stay on the textfield instead of going on the list last element …
=> fix(lightbox): fix wrong focus parent behavior

CHANGELOG.md, packages/lumx-core/src/scss/components/text-field/_index.scss, packages/lumx-react/src/components/text-field/TextField.stories.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
CMS-2064
When a textfield has a max content but no label, the counter was not shown. I changed the conditions in order to show the counter even when there is no label. I also added a story in order to test the behavior, and changed some style. …
=> fix(textfield): show maxlength counter  when there is no label

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_index.scss, packages/lumx-core/src/scss/components/user-block/_index.scss, packages/lumx-react/src/components/avatar/Avatar.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.test.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx, packages/lumx-react/src/components/thumbnail/__snapshots__/Thumbnail.test.tsx.snap, packages/lumx-react/src/components/user-block/UserBlock.stories.tsx, packages/lumx-react/src/components/user-block/UserBlock.tsx, packages/lumx-react/src/components/user-block/__snapshots__/UserBlock.test.tsx.snap
- Revert "fix(user-block): fix linkAs on Avatar"
- Revert "feat(thumbnail): fix thumbnail avatar and userblock a11y"
Reverts https://github.com/lumapps/design-system/pull/736
Reverts https://github.com/lumapps/design-system/pull/744
Changes on the Thumbnail markup (use of `<button>`) is breaking the style in specific use case so we are reverting these changes temporarly to [rework the Thumbnail style](https://github.com/lumapps/design-system/pull/713).
=> Revert: thumbnail, avatar, userblock improved link a11y

CHANGELOG.md, packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx, packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
Fix tooltip on element using function ref instead of object ref (createRef/useRef)
=> fix(tooltip): fix tooltip on element using function ref

packages/site-demo/content/product/patterns/form-validation/index.mdx
Fix wrong images and text for Stepper behavior section
=> docs(form-validation): fix wrong text and image

packages/site-demo/content/product/components/flag/index.mdx, packages/site-demo/content/product/components/flag/react/flag.tsx
Documentation page for `flag` component
=> docs(flag): added documentation page

packages/site-demo/content/product/components/badge/index.mdx, packages/site-demo/content/product/components/badge/react/colors.tsx
A new section about color usage for badges and a demo block according.
=> Docs/badge : added section about colors

CHANGELOG.md, packages/lumx-core/src/js/constants/index.ts, packages/lumx-core/src/scss/components/tooltip/_index.scss, packages/lumx-react/src/components/button/__snapshots__/IconButton.test.tsx.snap, packages/lumx-react/src/components/tooltip/Tooltip.tsx, packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx, packages/lumx-react/src/constants.ts, packages/lumx-react/src/utils/browserDoesNotSupportHover.test.js, packages/lumx-react/src/utils/browserDoesNotSupportHover.ts
-   On device with touch screen:
-   The Tooltip shows when the tooltip's anchor is pressed for more than 250 ms (long press).
This disables the default anchor's `click`/`touchend` event.
-   The tooltip hides 3 seconds after the long press is ended.
-   The tooltip is not activated on a short `click`/`tap`.
-   On devices supporting pointer hovering:
-   The tooltip shows when hovering the anchor (500 ms delay).
-   The tooltip hides when moving the pointer outside the anchor or clicking the anchor.
-   On every device:
-   The tooltip shows when focusing the anchor.
-   The tooltip hides when loosing focus on the anchor.
-   The tooltip hides when the escape key is pressed.
On desktop 
https://user-images.githubusercontent.com/939567/153460473-d16c7151-30ed-4507-befa-eb80911234c5.mp4 …
=> feat(tooltip): improve tooltip activation on touch devices

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_index.scss, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
Fix height/width ratio on aspect ratio original on iOS Safari
| Before | After |
| --- | --- |
| ![IMG_1852](https://user-images.githubusercontent.com/939567/155327152-651206ea-ec6c-4462-bfe6-180da75ca705.PNG) | ![IMG_1851](https://user-images.githubusercontent.com/939567/155327158-9c4c4b15-4a1c-485c-b90b-d553755222b0.PNG) |
=> fix(thumbnail): fix original aspect ratio on ios safari

CHANGELOG.md, packages/lumx-react/src/components/icon/Icon.tsx
Add alt attribute to svg element.
If set, the svg element will have a `role="img"` attribute added to it + `aria-label={alt}`
If omitted, the svg keeps a `aria-hidden="true"` attribute.
=> chore(icon): add alt attribute

CHANGELOG.md, packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx, packages/lumx-react/src/components/slideshow/Slideshow.tsx, packages/lumx-react/src/components/slideshow/SlideshowControls.tsx, packages/lumx-react/src/components/slideshow/SlideshowItem.tsx, packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap
First batch of fixes for the slideshow when it comes to accessibility:
- Make controls focusable
- Add several aria roles and description
- Stop autoplay on mouse enter and on focus
=> chore(slideshow): improve aria labels and focusable elements

CHANGELOG.md, packages/lumx-core/src/js/constants/index.ts, packages/lumx-core/src/scss/components/slideshow/_index.scss, packages/lumx-react/src/components/slideshow/Slides.tsx, packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx, packages/lumx-react/src/components/slideshow/Slideshow.test.tsx, packages/lumx-react/src/components/slideshow/Slideshow.tsx, packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx, packages/lumx-react/src/components/slideshow/SlideshowControls.tsx, packages/lumx-react/src/components/slideshow/SlideshowItem.tsx, packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap, packages/lumx-react/src/components/slideshow/index.ts, packages/lumx-react/src/hooks/useFocusWithin.ts, packages/lumx-react/src/hooks/useSlideshowControls.ts
This PR adds the following enhancements to the Slideshow component:
- Adds the Play/Pause button
- Adds focus to the bullets
- Refactors the slideshow component in order to avoid multiple hooks managing the same state
- Fixes an issue when the slide would go blank while transitioning.
=> chore(slideshow): added play buttton and other enhancements

CHANGELOG.md, packages/lumx-core/src/scss/components/icon/_index.scss, packages/lumx-core/src/scss/components/icon/_mixins.scss, packages/lumx-react/src/components/icon/Icon.stories.tsx, packages/lumx-react/src/components/icon/Icon.tsx, packages/lumx-react/storybook/story-block/StoryBlock.tsx, packages/lumx-react/storybook/story-block/index.scss, packages/site-demo/content/product/components/icon/index.mdx, packages/site-demo/content/product/components/icon/react/colors.tsx, packages/site-demo/content/product/components/icon/react/shape.tsx, packages/site-demo/content/product/components/icon/react/simple.tsx
Icon component do not currently support dark theme, this work is my attempt to make icon with "hasShape" parameter supports dark theme.
What I'm trying to achieve:
I'm available to discuss the case.
=> feat(icon): add dark theme compatibility

packages/site-demo/content/product/components/toolbar/index.mdx, packages/site-demo/content/product/components/toolbar/react/file-widget.tsx, packages/site-demo/src/style/layout/main/_main.scss
Added a demo block for illustrating file list widget toolbar example
=> docs(toolbar): added file list toolbar example

CHANGELOG.md, packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
Removed unecessary closing of tooltip (react set state) on unmount that can cause warnings in the React dev tools
=> chore(tooltip): remove unecessary set state on unmount

CHANGELOG.md, packages/lumx-react/src/components/comment-block/CommentBlock.stories.tsx, packages/lumx-react/src/components/comment-block/CommentBlock.tsx, packages/lumx-react/src/components/comment-block/__snapshots__/CommentBlock.test.tsx.snap, packages/site-demo/content/product/components/comment-block/react/default.tsx, packages/site-demo/content/product/components/comment-block/react/relevant.tsx, packages/site-demo/content/product/components/comment-block/react/threaded.tsx
Move the block comment date to below comment text and add a tooltip to display the new full date prop because the date will used the new timestamp format displaying the minimal information needed according to the current date
=> chore(comment-block): change date position and add tooltip for date

CHANGELOG.md, packages/lumx-core/src/scss/components/text-field/_mixins.scss
Fix select vertical margin calculation
In v2.2.12 https://5fbfb1d508c0520021560f10-mtwabgggwo.chromatic.com/?path=/story/lumx-components-select-select-multiple--default-select-multiple
With this PR https://5fbfb1d508c0520021560f10-bihmedrrjf.chromatic.com/?path=/story/lumx-components-select-select-multiple--default-select-multiple
=> chore(select): fix select vertical margin

CHANGELOG.md, packages/lumx-react/src/components/select/SelectMultiple.test.tsx, packages/lumx-react/src/components/select/SelectMultiple.tsx
Forward props to the wrapper component of the SelectMultiple.
This can be useful to add additionnal data such as `data-id`.
=> chore(select-multiple): forward props to wrapper

CHANGELOG.md, packages/lumx-react/src/components/dialog/Dialog.stories.tsx, packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap, packages/lumx-react/src/hooks/useFocusTrap.ts
2 focus trap issues fixed in this PR:
- Having disabled elements inside dialogs and lightbox could break the focus trap.
- Also coming in focus from outside the browser window could escape the focus trap.
Test on storybook: https://5fbfb1d508c0520021560f10-xzwarxjqom.chromatic.com/iframe.html?id=lumx-components-dialog-dialog--dialog-with-focusable-elements&args=&viewMode=story
The dialog should trap the focus
- Using Tab or using shift+Tab should circle through all focusable elemnts in the dialog without leaving the dialog
- Starting the focus in the browser search bar and focusing in the window should focus inside the dialog
=> chore(a11y): fix focus trap not ignoring disabled elements

packages/site-demo/content/product/components/skeleton/index.mdx
Fixed some broken link on skeleton demo page
=> docs(skeleton): fixed broken links

CHANGELOG.md, packages/lumx-core/src/scss/components/side-navigation/_index.scss, packages/lumx-react/src/components/side-navigation/SideNavigation.stories.tsx, packages/lumx-react/src/components/side-navigation/SideNavigationItem.test.tsx, packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx, packages/lumx-react/src/components/side-navigation/__snapshots__/SideNavigationItem.test.tsx.snap, packages/site-demo/gatsby-config.js, packages/site-demo/package.json, packages/site-demo/src/components/layout/MainNav/MainNav.tsx
- SideNavigationItem: added `closeMode` to `"unmount"` or `"hide"` children when the item is closed.
- Improve demo site side navigation SSR (nav fully generated in HTML now)
- Improve demo site side navigation automatically opening and closing sections on navigation (also scrolling the nav to put the current page link in the viewport)
Test on storybook
- Check side nav items open/close like before
- Check side nav items with `closeMode=hide` open/close keeping the children in the DOM
=> feat(side-nav): add closeMode to hide or unmount children when closed

CHANGELOG.md, packages/lumx-react/src/components/dialog/Dialog.stories.tsx, packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap, packages/lumx-react/src/hooks/useFocusTrap.ts, packages/lumx-react/src/stories/generated/Dialog/Demos.stories.tsx, packages/lumx-react/src/stories/generated/Dialog/isloading.tsx, packages/lumx-react/src/utils/focus/getFirstAndLastFocusable.test.ts, packages/lumx-react/src/utils/focus/getFirstAndLastFocusable.ts
Elements with `disabled=false` or `aria-disabled=false` at the end or start of a dialog or lightbox were skipped in the focus trap.
This PR fixes that and adds tests on the code detecting the first and last focusable elements in dialogs and lightbox.
- [Go to the dialog focus trap story
](https://5fbfb1d508c0520021560f10-efpjqlzlmv.chromatic.com/?path=/story/lumx-components-dialog-dialog--dialog-focus-trap)
- Check that the focus is contained inside the dialog
- Every focusable item is reachable
- Every non focusable item are skipped
=> fix(a11y): fix focus trap ignoring element with disabled=false

CHANGELOG.md, packages/lumx-react/src/components/generic-block/GenericBlock.stories.tsx, packages/lumx-react/src/components/generic-block/GenericBlock.test.tsx, packages/lumx-react/src/components/generic-block/GenericBlock.tsx, packages/lumx-react/src/components/generic-block/__snapshots__/GenericBlock.test.tsx.snap, packages/lumx-react/src/components/generic-block/index.ts, packages/lumx-react/src/index.ts, packages/lumx-react/src/stories/generated/GenericBlock/Demos.stories.tsx, packages/lumx-react/src/stories/generated/GenericBlock/default.tsx, packages/site-demo/content/product/components/generic-block/index.mdx, packages/site-demo/content/product/components/generic-block/react/default.tsx
Creating the `GenericBlock` component providing a reusable layout for the common pattern of "blocks" (site block, user block, etc.)
=> feat(component): create generic block

CHANGELOG.md, packages/lumx-react/src/components/date-picker/DatePickerField.tsx, packages/lumx-react/src/components/date-picker/types.ts, packages/lumx-react/src/components/dialog/Dialog.stories.tsx, packages/lumx-react/src/components/dialog/Dialog.tsx, packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap, packages/lumx-react/src/components/lightbox/Lightbox.tsx, packages/lumx-react/src/components/popover/Popover.tsx, packages/lumx-react/src/hooks/useCallbackOnEscape.ts, packages/lumx-react/src/hooks/useFocusTrap.ts, packages/lumx-react/src/utils/makeListenerTowerContext.ts
- fix(focus-trap): fix reset focus trap
- fix(focus-trap): fix nested focus traps
- fix(focus-trap): fix close nested components on escape key pressed
- chore(popover): focus first focusable element inside anchor on close
- fix(date-picker-field): fixed focus element on open
Scenario:
1. Go to the story ["Dialog Focus Trap"](https://5fbfb1d508c0520021560f10-enyqcdxplj.chromatic.com/?path=/story/lumx-components-dialog-dialog--dialog-focus-trap)
1. Navigate with `Tab` to the "Open date picker" button
1. Open by pressing `Enter`
1. Navigate with `Tab` to the date picker field
1. Open by pressing `Enter`
1. Navigate dates with `Tab` (this navigation could be improved upon)
1. Close the date picker with `Escape`
1. Close the date picker dialog with `Escape`
1. Close the main dialog with …
=> chore(focus-trap): fix & improve the focus trap

packages/lumx-react/src/components/button/Button.test.tsx, packages/lumx-react/src/components/button/IconButton.test.tsx, packages/lumx-react/src/components/slideshow/Slides.tsx, packages/lumx-react/src/testing/utils/commonTestsSuite.ts, packages/lumx-react/src/utils/type.ts
Document class name forwarding across all components
All component having `className` forwarding now have their props extend the `HasClassName` interface on which the `className` prop is documented with JSDoc.
On the documentation site, the `className` prop will show in all component prop tables
=> chore(doc): improve class name forwarding documentation

CHANGELOG.md, packages/lumx-react/src/components/autocomplete/Autocomplete.tsx, packages/lumx-react/src/components/dialog/Dialog.tsx, packages/lumx-react/src/components/dropdown/Dropdown.tsx, packages/lumx-react/src/components/text-field/TextField.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
Minor TS type improvements to broaden prop types making them usable on more use cases. 
**Their is no functional change**
-   Thumbnail: broaden `badge` prop TS type from `ReactElement` to `ReactElement | Falsy`.
Useful to display badge conditionally (ex: ` <Thumbnail badge={icon && <Badge>...`)
-   Dialog: broaden `contentRef` prop TS type from `RefObject` to `Ref`.
-   TextField: broaden `inputRef` prop TS type from `RefObject` to `Ref`.
-   Autocomplete: broaden `inputRef` prop TS type from `RefObject` to `Ref`.
=> chore: improve component prop types

CHANGELOG.md, packages/lumx-core/src/scss/components/flex-box/_index.scss, packages/lumx-react/src/components/flex-box/FlexBox.stories.tsx, packages/lumx-react/src/components/flex-box/FlexBox.tsx
FlexBox: add `tiny` to the possible `gap` sizes.
=> feat(flexbox): add tiny size to flexbox gap

CHANGELOG.md, packages/lumx-icons/package.json, packages/lumx-icons/rollup.config.js, yarn.lock
Add a build step to the `@lumx/icons` to flatten all icons from mdi into one ESM module so tree shaking can be more effective
=> chore(icons): build module for better tree shaking

CHANGELOG.md, packages/lumx-react/src/components/thumbnail/useFocusPointStyle.test.ts, packages/lumx-react/src/components/thumbnail/useFocusPointStyle.tsx
When the container and the image size were equal, it caused a division by 0. 
It wasn't a big problem when the focusPoint is not equal to 0, because the result of a `x/0 === Infinity` if x !== 0, so it was translated to 100%. But `0/0 === NaN`, so when the focusPoint is 0, the computed CSS was invalid, so the focus point was not applied. 
Now we just early return a 0 if `containerSize === imageSize`. 
This PR also adds some tests on this function.
=> fix(thumbnail): fix shift calculation when focusY is 0

CHANGELOG.md, dev-packages/eslint-plugin-lumapps/package.json, dev-packages/ga-remove-label/package.json, lerna.json, packages/lumx-angularjs/package.json, packages/lumx-core/package.json, packages/lumx-icons/package.json, packages/lumx-icons/rollup.config.js, packages/lumx-react/package.json, packages/site-demo/package.json, packages/yo-generators/package.json, yarn.lock
Current ESM version of `@lumw/icons` can have trouble being processed by Jest (compiling with babel in `NODE_ENV=test` [triggers an `Infinite cycle detected` error](https://github.com/babel/babel/blob/e498bee10f0123bb208baa228ce6417542a2c3c4/packages/babel-traverse/src/context.js#L56)) 
To counter that, we'll export both an ESM version for build tools and better tree shaking and a CJS version for Jest tests.
=> chore(icons): bundle both CJS and ESM module

CHANGELOG.md, packages/lumx-react/src/components/heading/Heading.stories.tsx, packages/lumx-react/src/components/heading/Heading.test.tsx, packages/lumx-react/src/components/heading/Heading.tsx, packages/lumx-react/src/components/heading/HeadingLevelProvider.tsx, packages/lumx-react/src/components/heading/constants.ts, packages/lumx-react/src/components/heading/context.tsx, packages/lumx-react/src/components/heading/index.ts, packages/lumx-react/src/components/heading/useHeadingLevel.tsx, packages/lumx-react/src/index.ts
CF-365
Create a `Heading` component to manage html headings (h1 / h2 / h3 / h4 / h5 / h6).
The component extends the `Text` component for styling but only accepts `HeadingElement` as `as` prop.
It also comes with a `HeadingLevelProvider` to allow the `HeadingComponent` to automatically know what level to use by default. The correct typography based on this level will also be applied.
Both the level and the typography can be overridden if needed.
=> feat(heading): create heading component

CHANGELOG.md, packages/lumx-core/src/js/constants/index.ts, packages/lumx-core/src/scss/components/slideshow/_index.scss, packages/lumx-react/src/components/slideshow/Slides.tsx, packages/lumx-react/src/components/slideshow/Slideshow.stories.tsx, packages/lumx-react/src/components/slideshow/Slideshow.tsx, packages/lumx-react/src/components/slideshow/SlideshowControls.stories.tsx, packages/lumx-react/src/components/slideshow/SlideshowControls.tsx, packages/lumx-react/src/components/slideshow/SlideshowItem.tsx, packages/lumx-react/src/components/slideshow/SlideshowItemGroup.tsx, packages/lumx-react/src/components/slideshow/__snapshots__/Slideshow.test.tsx.snap, packages/lumx-react/src/components/slideshow/useSlideFocusManagement.tsx, packages/lumx-react/src/hooks/useRovingTabIndex.tsx, packages/lumx-react/src/utils/focus/constants.ts, packages/lumx-react/src/utils/focus/getFirstAndLastFocusable.ts, packages/lumx-react/src/utils/focus/getFocusableElements.test.ts, packages/lumx-react/src/utils/focus/getFocusableElements.ts
* Fixed keyboard navigation and screen reader compatibility for slideshows
* Non visible slides now can't be navigated to using the keyboard.
* Non visible slides are hidden from screen readers.
* When slides become visible, the focus is restored and so is their screen reader visibility.
* Added roving tab index to controls
* Slides grouped together are now wrapped inside individual divs.
* Added roles and attributes to improve a11y complience.
=> fix(slideshow): improve accessibility

CHANGELOG.md, packages/lumx-core/src/scss/components/flex-box/_index.scss, packages/lumx-react/src/components/flex-box/FlexBox.stories.tsx, packages/lumx-react/src/components/flex-box/FlexBox.tsx, packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap, packages/lumx-react/src/components/index.ts
It was not possible in the Flexbox component to use space-around/between/evenly css properties through props. 
This PR aims to modify this by providing more options to the `vAlign` and `hAlign` props for this component.
Add/Remove/Update the following check list depending on your submission:
-   [x] (if you need a storybook and/or visual diff) Add `need: deploy-chromatic` label
Chromatic builds are available here: https://www.chromatic.com/builds?appId=5fbfb1d508c0520021560f10
Check out the …
=> chore(flexbox): adding options to valign and halign props to handle spacing more precisely

CHANGELOG.md, packages/lumx-react/src/components/flex-box/FlexBox.stories.tsx, packages/lumx-react/src/components/flex-box/FlexBox.tsx, packages/lumx-react/src/components/flex-box/__snapshots__/FlexBox.test.tsx.snap, packages/lumx-react/src/components/generic-block/GenericBlock.stories.jsx
-   FlexBox: add `as` prop to customize the root element component render.
-   GenericBlock: add `as` prop to customize the root, the figure, the content and actions elements component render.
=> chore(flexbox): add as prop to cutomize component render

packages/lumx-react/src/stories/generated/Heading/Demos.stories.tsx, packages/lumx-react/src/stories/generated/Heading/automatic-heading-level.tsx, packages/lumx-react/storybook/story-block/StoryBlock.tsx, packages/site-demo/content/product/components/date-picker/react/default.tsx, packages/site-demo/content/product/components/date-picker/react/input.tsx, packages/site-demo/content/product/components/date-picker/react/restricted.tsx
When snapshoting stories in chromatic we need to inject the `today` Date so that it's always the same.
Previously this was injected in stories args but it can cause problems for stories that just sread the `args` as props. 
To improve the situation, the `today` value will be injected in the storybook `context.parameters`.
**Non regression tests**
- Check date picker [SB stories show the same default date as before](https://5fbfb1d508c0520021560f10-apdillnpmd.chromatic.com/?path=/story/lumx-components-date-picker-datepickerfield--simple)
- Check date picker demos (on the demo site) show the same default date as before
- Check chromatic snapshots still show the same date
=> chore(storybook): improve stories `today` param handling

CHANGELOG.md, packages/lumx-core/src/scss/components/text/_index.scss, packages/lumx-react/src/components/text/Text.stories.jsx, packages/lumx-react/src/components/text/Text.test.tsx, packages/lumx-react/src/components/text/Text.tsx, packages/lumx-react/src/stories/withResizableBox.tsx, packages/site-demo/content/product/components/text/index.mdx, packages/site-demo/plugins/utils/rewriteJSXComponent.spec.js, packages/site-demo/plugins/utils/rewriteJSXComponents.js
- Fix `Icon` vertical align inside `Text`
- Add `noWrap` prop to prevent line wrap
- Improve doc on text wrap and overflow
Tests
- [Check text stories with icons](https://5fbfb1d508c0520021560f10-szoquuajox.chromatic.com/?path=/story/lumx-components-text-text--all-typography)
- [Check text story with noWrap](https://5fbfb1d508c0520021560f10-szoquuajox.chromatic.com/?path=/story/lumx-components-text-text--no-wrap)
=> feat(text): improve icon alignment and add noWrap prop

CHANGELOG.md, packages/lumx-core/src/scss/components/inline-list/_index.scss, packages/lumx-core/src/scss/lumx.scss, packages/lumx-react/src/components/inline-list/InlineList.stories.tsx, packages/lumx-react/src/components/inline-list/InlineList.test.tsx, packages/lumx-react/src/components/inline-list/InlineList.tsx, packages/lumx-react/src/components/inline-list/index.ts, packages/lumx-react/src/components/text/Text.tsx, packages/lumx-react/src/index.ts, packages/lumx-react/src/utils/className.ts, packages/lumx-react/src/utils/type.ts, packages/site-demo/content/product/components/inline-list/index.mdx
A component to display inline list of elements separated by dots.
StoryBook: https://5fbfb1d508c0520021560f10-gtrtbxgvqy.chromatic.com/?path=/story/lumx-components-inline-list-inlinelist--mixed-no-wrap-and-truncate
=> feat(inline-list): create InlineList component

CHANGELOG.md, packages/lumx-react/src/components/inline-list/InlineList.tsx, packages/site-demo/content/product/components/inline-list/index.mdx, packages/site-demo/content/product/components/text/index.mdx
Since each element of the `InlineList` component has a `display: contents` css attribute, it removes the semantic value of these items.
Added back a `listitem` role on each items to reset the semantics.
=> fix(inline-list): add listitem role to items

packages/lumx-react/src/components/dropdown/Dropdown.tsx, packages/site-demo/content/product/components/dropdown/index.mdx, packages/site-demo/content/product/components/dropdown/react/selects.tsx, packages/site-demo/src/components/content/DemoBlock/DemoBlock.tsx
Added an example section for showing that dropdown actions have states.
=> docs(dropdown): added example of actions states

CHANGELOG.md, packages/lumx-react/src/components/text/Text.test.tsx, packages/lumx-react/src/components/text/Text.tsx
Text: ignore empty children to make `dangerouslySetInnerHTML` work as expected.
=> fix(text): fix dangerouslySetInnerHTML

CHANGELOG.md, packages/lumx-react/src/components/autocomplete/Autocomplete.tsx
Forward TextField props explicitly in the autocomplete component to allow easier customization.
=> chore(autocomplete): forward textfield props

packages/site-demo/content/product/components/dropdown/index.mdx, packages/site-demo/content/product/components/flex-box/index.mdx, packages/site-demo/content/product/components/link-preview/index.mdx, packages/site-demo/content/product/components/popover/index.mdx, packages/site-demo/content/product/components/toolbar/index.mdx, packages/site-demo/content/product/components/tooltip/index.mdx, packages/site-demo/content/product/components/tooltip/react/placement.tsx, packages/site-demo/src/components/base/Link.tsx
- docs(flex-box): add accessibility concerns section
- docs(toolbar): add accessibility concerns section
- docs(popover): add accessibility concerns section
- docs(tooltip): add accessibility concerns section
- docs(dropdown): add accessibility concerns section
- chore(demo-site): fix internal link format with anchor
- docs(link-preview): add accessibility concerns section
=> docs: document several components on a11y concerns

CHANGELOG.md, packages/lumx-react/src/components/autocomplete/Autocomplete.tsx
Simple fix for the type of the textfieldProps property on the autocomplete component
=> chore(autocomplete): fix type for textfieldprops property

CHANGELOG.md, packages/lumx-react/src/components/autocomplete/Autocomplete.tsx, packages/lumx-react/src/components/dropdown/Dropdown.tsx, packages/lumx-react/src/components/popover/Popover.stories.tsx, packages/lumx-react/src/components/popover/Popover.tsx
Popover, Dropdown, Autocomplete: add `minWidth`, `maxWidth`, and `width` options to the `fitToAnchorWidth` property. This change allows managing popover size to not be bigger (width & maxWidth) or smaller (width, minWidth)  than the anchor.
=> feat(popover): add options to fitToAnchorWidth prop

CHANGELOG.md, packages/lumx-react/src/components/button/Button.stories.tsx, packages/lumx-react/src/components/button/Button.tsx
[CF-406](https://lumapps.atlassian.net/browse/CF-406)
Allow the Text component truncate to work with the Button component
=> feat(button): make text truncate work with the button component

.github/actions/setup/action.yml, .github/workflows/deploy-chromatic.yaml, .github/workflows/release.yml, README.md, package.json, packages/lumx-angularjs/package.json, packages/lumx-core/package.json, packages/lumx-icons/package.json, packages/lumx-react/package.json, yarn.lock
1. Remove old npm script setup (using prepublishOnly and version)
3. Create a fully automatic GH workflow for prerelease and release 
1. Assetions 
- assert we are on a branch
- (if release) assert we are on master
- (if release) assert changelog has unreleased changes
2. Prepare version (get latest version and increment)
4. Update versions in all packages
5. Update version in CHANGELOG
6. Build all libs
7. Publish on NPM
8. (if release) Git commit, tag & push
9. (if release) Create a pull request 
3. Move old post-release job to the new release workflow
=> Run the "release note", "build & push demo site" & "deploy chromatic" jobs after the release instead of running them after pushing a release tag to github
TODO:
- Test prerelease use case: …
=> chore(workflow): create automatic release workflow

CHANGELOG.md, packages/lumx-react/src/components/badge/Badge.tsx, packages/lumx-react/src/components/button/ButtonRoot.tsx, packages/lumx-react/src/components/chip/Chip.tsx, packages/lumx-react/src/components/icon/Icon.tsx, packages/lumx-react/src/components/link/Link.tsx
[CF-407](https://lumapps.atlassian.net/browse/CF-407)
Change the type of the color prop of the DS components to accept only ColorPalette values (instead of accepting string too)
=> fix(button): fix color props allowing string not in colorpalette

CHANGELOG.md, packages/lumx-react/src/components/expansion-panel/ExpansionPanel.stories.tsx, packages/lumx-react/src/components/expansion-panel/ExpansionPanel.test.tsx, packages/lumx-react/src/components/expansion-panel/ExpansionPanel.tsx
[CF-494](https://lumapps.atlassian.net/browse/CF-494)
When the expansion panel is used inside a dropdown, the click on the expansion panel closed the dropdown, we need to have the MouseEvent to prevent this behavior.
This PR pass the onClick event to the onOpen, onClose and onToggleOpen callbacks of the ExpansionPanel component.
[CF-494]: https://lumapps.atlassian.net/browse/CF-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(expansion-panel): pass event to the component callbacks

CHANGELOG.md, packages/lumx-core/src/scss/components/grid-column/_index.scss
GridColumn: fix error in SCSS variable interpolation (removing the `calc()` funciton)
=> fix(grid-column): fix scss variable interpolation

.github/workflows/release-build-site.yml, .github/workflows/release-deploy-chromatic.yaml, .github/workflows/release-github-release-note.yml, .github/workflows/release.yml
- Removing git tag creation from the release workflow (github-actions user cannot push git tags anymore :() 
- Split deploy chromatic into a workflow triggered on tag pushed
- Split build site into workflow triggered on tag pushed
Git tags will have to be created manually until we find a way to create a dedicated bot user that can be configured to push git tags in the release workflow.
=> chore(ci): disable git tag and split release jobs

CHANGELOG.md, packages/lumx-react/src/components/alert-dialog/__snapshots__/AlertDialog.test.tsx.snap, packages/lumx-react/src/components/dialog/Dialog.stories.tsx, packages/lumx-react/src/components/dialog/Dialog.test.tsx, packages/lumx-react/src/components/dialog/Dialog.tsx, packages/lumx-react/src/components/dialog/__snapshots__/Dialog.test.tsx.snap
Added 3 new props to the `Dialog` component to make it more customizable
- `disableBodyScroll`: defaults to true, allows to enable/disable the scroll on the body
- `preventCloseOnClick`: only prevents the close on click. Useful when we want to keep the close on `Escape`
- `preventCloseOnEscape`: only prevents the close on escape. Useful when we want to keep the close on `Click`
=> chore(dialog): new props for disabling scroll and events

CHANGELOG.md, packages/lumx-react/src/components/select/SelectMultiple.stories.tsx, packages/lumx-react/src/components/select/WithSelectContext.tsx
Fix select dropdown focus within a dialog not being trapped
This PR trap the focus on the Select dropdown like it is the case with a Dialog, you can test it with the story SelectWithinADialog https://www.chromatic.com/builds?appId=5fbfb1d508c0520021560f10
=> fix(select): fix select dropdown focus not being trapped

packages/lumx-core/src/scss/lumx.scss, packages/lumx-icons/font.scss, packages/lumx-react/storybook/story-block/index.scss, packages/site-demo/src/components/content/AssetBlock/AssetBlock.scss, packages/site-demo/src/components/content/CodeBlock/CodeBlock.scss, packages/site-demo/src/components/content/DemoBlock/DemoBlock.scss, packages/site-demo/src/components/content/DemoColor/DemoColor.scss, packages/site-demo/src/components/content/PropTable/PropTable.scss, packages/site-demo/src/components/content/design-tokens/DesignToken.scss, packages/site-demo/src/components/content/design-tokens/DesignTokenGroup.scss, packages/site-demo/src/components/layout/Layout.scss, packages/site-demo/src/components/layout/MainContent/MainContent.scss, packages/site-demo/src/components/layout/MainHeader/MainHeader.scss, packages/site-demo/src/components/layout/MainNav/HomeLogoLink/HomeLogoLink.scss, packages/site-demo/src/components/layout/MainNav/MainNav.scss, packages/site-demo/src/components/search/SearchButton.scss, packages/site-demo/src/components/search/dialog/SearchDialog.scss, packages/site-demo/src/style/index.scss
1. Remove `~` import in SCSS that are now deprecated (module import work fine without it)
2. Lint all SCSS files
=> chore(core): remove deprecated sass tilde imports

CHANGELOG.md, packages/lumx-react/src/components/text-field/TextField.test.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
This PR adds 2 `aria` attributes to the `TextField` component:
- `aria-describedby` added to the `input` in order to associate the input to the helpers and errors
- `aria-invalid` when the component has `hasError = true`
=> chore(a11y): added a11y attributes to text field

CHANGELOG.md, packages/lumx-react/src/components/text-field/TextField.stories.tsx, packages/lumx-react/src/components/text-field/TextField.test.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
Added a callback to be able to trigger some function when a user clicks on the clear button.
**There are no visual updates in this PR**
=> feat(textfield): add onClear callback to props

CHANGELOG.md, packages/lumx-react/src/components/button/IconButton.stories.tsx, packages/lumx-react/src/components/button/IconButton.tsx, packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
Screen reader was reading two time the icon button label on focus because of the label being present in aria-label and on aria-describedby (which read the tooltip label). 
This PR aim to remove the aria-describedby attribute on icon button when the aria-label and the tooltip label are the same
Tests steps:
- Go to the tooltip component and check that when you focus the button you have an aria-describedby attribute
- Go to the iconButton Tooltip component and check that when you focus the button you don't see the aria-describedby attribute
=> fix(iconbutton): remove ariadescribedby attribute when not needed

CHANGELOG.md, packages/lumx-react/src/components/text-field/TextField.stories.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
Clicking on the clear button of the textfield focus the previous element instead of the input
Tests steps:
- Go to the textfield component, on the Clearable story, focus the input with the keyboard, and focus the clear button with the keyboard, press enter and check that the focus is now on the input
=> fix(textfield): focus the input on clear button click

CHANGELOG.md, packages/lumx-core/src/scss/components/uploader/_index.scss, packages/lumx-react/src/components/uploader/Uploader.stories.tsx, packages/lumx-react/src/components/uploader/Uploader.test.tsx, packages/lumx-react/src/components/uploader/Uploader.tsx, packages/site-demo/content/product/components/uploader/index.mdx
- fix(uploader): use true button to improve accessibility
- feat(uploader): add native file input handler
- docs(uploader): add accessibility concerns section
Use a true `<button>` button by default to improve accessibility. 
Use `<input type=file>` and `<label>` if `fileInputProps` is provided to handle a native file picker and to support dropping a file onto the uploader.
=> fix(uploader): improve a11y & doc ARCH-59

CHANGELOG.md, packages/lumx-react/src/components/autocomplete/Autocomplete.stories.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
Since the autocomplete passes a `mergeRefs` function as inputRef and that the TextField didn't manage this case, the focus was not restored to the input field on clear.
Fixed by adding another "ref" locally to the TextField to manage the focus.
StoryBook: https://fc535bf8--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=289)) **⚠️ Outdated commit** **⚠️ Outdated commit**
=> fix(autocomplete): focus text field on clear button clicked

CHANGELOG.md, packages/lumx-core/src/scss/components/side-navigation/_mixins.scss, packages/lumx-react/src/components/side-navigation/SideNavigationItem.test.tsx, packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx, packages/lumx-react/src/utils/renderButtonOrLink.tsx, packages/lumx-react/src/utils/renderLink.tsx, packages/site-demo/content/product/components/side-navigation/index.mdx
- fix(side-navigation): fix open/close accessibility state
- fix(side-navigation): default to button when not explicitly a link
- docs(side-navigation): add accessibility concerns section
StoryBook: https://b7137fe3--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=292)) **⚠️ Outdated commit**
=> fix(side-navigation): improve and document a11y ARCH-48

.github/actions/update-pr-body/index.js, .github/workflows/deploy-chromatic-pull-request.yaml
- Fix CI job "Mark storybook URL as outdated" that would continue appending `**⚠️ Outdated commit**` even when the storybook URL was already marked as outdated.
- Improve logs
StoryBook: https://b9672b96--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=293)) **⚠️ Outdated commit**
=> chore(ci): fix mark outdated storybook URL

CHANGELOG.md, packages/lumx-react/src/components/tabs/Tab.test.tsx, packages/lumx-react/src/components/tabs/Tab.tsx, packages/site-demo/content/product/components/tabs/react/icon-tabs.tsx
CF-642
Add the Icon customisation with `iconProps` inside the Tab component.
=> feat(tab): add icon customisation with IconProps

CHANGELOG.md, packages/lumx-core/src/js/date-picker.ts, packages/lumx-react/.storybook/preview.ts, packages/lumx-react/package.json, packages/lumx-react/src/components/date-picker/DatePicker.stories.tsx, packages/lumx-react/src/components/date-picker/DatePicker.tsx, packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.stories.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.tsx, packages/lumx-react/src/components/date-picker/types.ts, packages/lumx-react/src/utils/date/addMonthResetDay.test.ts, packages/lumx-react/src/utils/date/addMonthResetDay.ts, packages/lumx-react/src/utils/date/getFirstDayOfWeek.test.ts, packages/lumx-react/src/utils/date/getFirstDayOfWeek.ts, packages/lumx-react/src/utils/date/getMonthCalendar.test.ts, packages/lumx-react/src/utils/date/getMonthCalendar.ts, packages/lumx-react/src/utils/date/getWeekDays.test.ts, packages/lumx-react/src/utils/date/getWeekDays.ts, packages/lumx-react/src/utils/date/isDateValid.test.ts, packages/lumx-react/src/utils/date/isDateValid.ts, packages/lumx-react/src/utils/date/isSameDay.test.ts, packages/lumx-react/src/utils/date/isSameDay.ts, packages/lumx-react/src/utils/locale/getCurrentLocale.ts, packages/lumx-react/src/utils/locale/parseLocale.test.ts, packages/lumx-react/src/utils/locale/parseLocale.ts, packages/lumx-react/src/utils/locale/types.ts, yarn.lock
Replacing moment with vanilla JS.
All the logic used to generate the month calendar is re-written in vanilla JS. The date utils from `@lumx/core` that used moment have been deprecated ([will have to remove them in the next major version as it is a breaking change](https://github.com/lumapps/design-system/pull/1016)). The DatePicker/DatePickerField components API do not change at all since we already do not reference moment.
The only challenging part for the implementation of the date picker was to get the **first day of the week** for a given locale (Monday in most of europe, Sunday in the US, etc.). The browser API `Intl.Local.getWeekInfo()` is still experimental (although partially implemented in Chrome & Safari via a `weekInfo` accessor property). I've choose to try this browser API …
=> feat(date-picker): replace moment with vanilla JS

CHANGELOG.md, packages/lumx-core/src/scss/components/list/_mixins.scss
[CF-486](https://lumapps.atlassian.net/browse/CF-486)
In order to fix insufficient contrast ratio with SubHeader component, changed color from `dark-L3` to `dark-L2`.
using dark L3:
using dark L2:
[CF-486]: https://lumapps.atlassian.net/browse/CF-486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
StoryBook: https://b59d5881--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=305)) **⚠️ Outdated commit**
=> fix(subheader): change color to dark-L2

packages/site-demo/src/components/content/CodeBlock/CodeBlock.scss, packages/site-demo/src/components/content/CodeBlock/CodeBlock.tsx, packages/site-demo/src/components/content/CodeBlock/renderJSXLinesWithCollapsedImports.tsx, packages/site-demo/src/components/content/CodeBlock/renderLines.tsx, packages/site-demo/src/components/content/DemoBlock/DemoBlock.scss, packages/site-demo/src/components/content/DemoBlock/DemoBlock.tsx
Render code block visually hidden instead of removed from the DOM
- Improve SEO, webscraping
- Improve semantic and a11y (using `<details><summary>` and `<code>`)
https://github.com/lumapps/design-system/assets/939567/3a5fb266-8175-4879-ac8c-4de1fbe5a153
=> chore(demo-site): render code hidden

CHANGELOG.md, packages/lumx-core/src/js/constants/index.ts, packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx, packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/Tooltip.tsx, packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx, packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
DSW-47
Make tooltip hoverable for better a11y
StoryBook: https://8b13cc9d--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=318)) **⚠️ Outdated commit**
=> fix(tooltip): fixed closing when mouse is hovering the tooltip text

.github/workflows/validate-pull-request.yml, package.json, packages/lumx-react/src/components/navigation/NavigationItem.tsx, packages/lumx-react/src/components/uploader/Uploader.test.tsx, packages/lumx-react/src/utils/forwardRefPolymorphic.ts, yarn.lock
Context: I recently, unknowingly merged with types error in the PR  https://github.com/lumapps/design-system/pull/1035 because the type checking is not checked in CI 😬 
In this PR:
1. Add code type check to the CI
2. Fix type errors (cause by the update of react types)
After this PR is merges, i'm making this CI check required in the repo configuration: https://github.com/lumapps/github-automation/pull/1680
=> chore(ci): add code type check

CHANGELOG.md, packages/lumx-core/src/scss/components/text/_index.scss, packages/lumx-react/src/components/index.ts, packages/lumx-react/src/components/text/Text.stories.tsx, packages/lumx-react/src/components/text/Text.test.tsx, packages/lumx-react/src/components/text/Text.tsx
Proposition to update the design-system `Text` component, and add a new `whiteSpace` property, to customise the `Text` CSS style.
This will let the user choose the CSS `white-space` property he want for the text. The use case that motivated this PR was to show the `Text` string, with it's formatting intact (line break, spaces, ...) using `white-space: pre-wrap`.
StoryBook: https://50cad0c2--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=322)) **⚠️ Outdated commit**
=> feat(text): add whiteSpace support

packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx
- chore(tooltip): make sure to only listen escape key on open
- chore(tooltip): add tests on close on escape
Not modifying the CHANGELOG because this fix is on a bug not yet releases
StoryBook: https://5991f7f4--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=323))
=> chore(tooltip): fix escape key handler only when open

packages/site-demo/src/components/base/Link.tsx
Relative path (ex: `../dropdown`) are broken on the demo site, this PR fixes this while still making sure to format the link paths (add trailing slash suffix and gatsby prefix)
=> chore(demo-site): fix relative link path formatting

CHANGELOG.md, packages/lumx-react/src/components/dialog/Dialog.tsx, packages/lumx-react/src/components/lightbox/Lightbox.tsx, packages/lumx-react/src/components/notification/Notification.tsx, packages/lumx-react/src/hooks/useTransitionVisibility.ts
Lightbox, Dialog, Notification: fix remove from DOM when closing while the opening transition isn't finished.
https://lumapps.atlassian.net/browse/DSW-107
StoryBook: https://0b59f5b0--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=325))
=> fix(transition-visibility): fix handling when closing prematurely

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_index.scss
When using object-fit:cover + ratio 1/1, Chrome switches to pixelated downsizing algo which makes the avatar pixelated, add css rules to make Chrome reuse the bilinear algo so it's smoother for Avatar component
SUP-4461
StoryBook: https://f132033c--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=326)) **⚠️ Outdated commit**
=> fix(avatar): fix Chrome behavior when downscaling avatar

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_index.scss
Fix warnings on the thumbnail image overflow style
StoryBook: https://cb433eca--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=329))
=> fix(thumbnail): fix warning on image overflow

CHANGELOG.md, packages/lumx-core/src/scss/components/popover/_index.scss, packages/lumx-core/src/scss/components/popover/_variables.scss, packages/lumx-core/src/scss/core/elevation/_mixins.scss, packages/lumx-core/src/scss/core/elevation/_variables.scss, packages/lumx-react/.storybook/story-block/StoryBlock.tsx, packages/lumx-react/src/components/popover/Popover.stories.tsx, packages/lumx-react/src/components/popover/Popover.tsx, packages/lumx-react/src/components/popover/constants.ts, packages/lumx-react/src/components/popover/usePopoverStyle.tsx, packages/lumx-react/src/stories/controls/selectArgType.ts
https://lumapps.atlassian.net/browse/DSW-43
- feat(popover): rework arrow style
Make arrow bigger and make the drop shadow fit better with the whole popover
| before | after |
| --- | --- |
| ![image](https://github.com/lumapps/design-system/assets/939567/b4fdee55-01a9-400a-8564-ea910cf91ee8) | ![image](https://github.com/lumapps/design-system/assets/939567/25f15d1b-abda-4fad-82fe-50d3681c4611) |
Test on: https://257497c2--5fbfb1d508c0520021560f10.chromatic.com/?path=/story/lumx-components-popover-popover--simple&args=hasArrow:true
- feat(popover): add dark theme
Add dark theme changing the popover and arrow background
Test on: https://257497c2--5fbfb1d508c0520021560f10.chromatic.com/?path=/story/lumx-components-popover-popover--dark-theme
StoryBook: …
=> feat(popover): rework arrow style and add dark theme

CHANGELOG.md, packages/lumx-react/src/components/input-helper/InputHelper.tsx
For a11y, improve the semantic of the inputHelper component by using a semantic `<p>` tag instead of a `<span>`.
No visual changes, only the markup changes.
=> fix(input-helper): replace span with p element to improve semantic

CHANGELOG.md, packages/lumx-react/src/components/expansion-panel/ExpansionPanel.test.tsx, packages/lumx-react/src/components/select/Select.test.tsx, packages/lumx-react/src/components/text-field/TextField.test.tsx, packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx, packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx, packages/lumx-react/src/utils/isFocusVisible.ts
Restrict opening Tooltip on anchor focus only when focus is visible (keyboard driven).
StoryBook: https://39ab6f3b--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=335)) **⚠️ Outdated commit**
=> feat(tooltip): restrict open on focus visible

CHANGELOG.md, packages/lumx-react/src/components/popover/Popover.tsx, packages/lumx-react/src/components/popover/useRestoreFocusOnClose.tsx, packages/lumx-react/src/utils/mergeRefs.ts, packages/lumx-react/src/utils/useBeforeUnmountSentinel.tsx
https://lumapps.atlassian.net/browse/DSW-36
Fix restore focus on trigger on closed externally and not just when closed with Escape or closed on click away
Before: https://55e3a19--5fbfb1d508c0520021560f10.chromatic.com/?path=/story/lumx-components-popover-dialog-popoverdialog--with-button-trigger
After: https://5fbfb1d508c0520021560f10-pylwvppsxi.chromatic.com/?path=/story/lumx-components-popover-dialog-popoverdialog--with-button-trigger
=> fix(popover): restore focus on trigger on closed externally

CHANGELOG.md, packages/lumx-react/src/components/button/IconButton.tsx, packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/Tooltip.tsx, packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
Avoid removing the anchor aria-describedby value:
- Concat with the tooltip id if the tooltip label is not the same as the anchor label
- Keep it as-is otherwise
=> fix(tooltip): avoid removing the anchor aria-describedby

CHANGELOG.md, packages/lumx-react/src/components/popover-dialog/PopoverDialog.stories.tsx, packages/lumx-react/src/components/popover-dialog/PopoverDialog.test.tsx, packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx, packages/lumx-react/src/utils/isFocusVisible.ts
Fixing unstable anchor ref due to ref merging. Adding memoization
Fixes improper focus restore on trigger when closing popover
=> fix(tooltip): fix unstable anchor ref with memoize

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_index.scss, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx
https://lumapps.atlassian.net/browse/DSW-135
Use `span` instead of `div` in children thumbnail elements to avoid semantic error on clickable thumbnails (button).
**Test scenario**: non-regression visual tests on thumbnails
- Check clickable and non clickable thumbnails
- Check with or without aspect ratio
- Check image fallback
StoryBook: https://5fbfb1d508c0520021560f10-lwksiktedo.chromatic.com/
=> fix(thumbnail): fix child DOM tag semantic

CHANGELOG.md, packages/lumx-core/src/scss/core/base/_helpers.scss, packages/lumx-react/src/components/date-picker/DatePickerControlled.test.tsx, packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.tsx, packages/lumx-react/src/components/popover-dialog/PopoverDialog.test.tsx, packages/lumx-react/src/components/popover-dialog/PopoverDialog.tsx, packages/lumx-react/src/components/text-field/TextField.tsx, packages/lumx-react/src/hooks/usePreviousValue.ts, packages/lumx-react/src/utils/date/getMonthCalendar.test.ts, packages/lumx-react/src/utils/date/getWeekDays.test.ts, packages/lumx-react/src/utils/date/getWeekDays.ts
https://lumapps.atlassian.net/browse/DSW-147
- Make the month+year announced by screen readers when changing month 
- Add visually hidden week day full name for screen readers
- Add visually hidden full date for screen readers
https://github.com/lumapps/design-system/assets/939567/aebdf738-7b25-4543-a33d-ebc47c45f897
- Replace Popover with PopoverDialog to use the proper aria dialog pattern
- On open > focus the selected date or today
**We can probably improve more on the date picker with a grid pattern and on the date picker field with an actual editable text field (combox dialog pattern)** 
StoryBook: https://2e283d9d--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=341))
=> feat(date-picker): improve a11y

CHANGELOG.md, packages/lumx-core/src/scss/components/chip/_index.scss, packages/lumx-core/src/scss/components/text-field/_index.scss, packages/lumx-core/src/scss/components/text-field/_mixins.scss, packages/lumx-react/src/components/chip/ChipGroup.stories.tsx, packages/lumx-react/src/components/chip/ChipGroup.test.tsx, packages/lumx-react/src/components/chip/ChipGroup.tsx
Replace the margin with a gap.
Depreciate the align property of the component since it's no more applicable.
StoryBook: https://fe16c477--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=345)) **⚠️ Outdated commit**
=> fix(chip-group): use gap instead of margin and depreciate the align property

CHANGELOG.md, packages/lumx-core/src/css/design-tokens.css, packages/lumx-core/src/js/constants/design-tokens.ts, packages/lumx-core/src/scss/_design-tokens.scss, packages/lumx-core/src/scss/core/state/_mixins.scss, packages/lumx-core/style-dictionary/properties/core/color.json
To fix a contrast issue on red and green buttons:
1. red/D2, red/N and green/N color values are changed.
2. Colored Low and medium button texts are now using the D2 color instead of N color.
StoryBook: https://e5f9ee1c--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=347)) **⚠️ Outdated commit**
=> fix(color-a11y): changed red and green, changed low and medium text color

CHANGELOG.md, packages/lumx-core/src/scss/components/date-picker/_index.scss, packages/lumx-react/src/components/date-picker/DatePicker.test.tsx, packages/lumx-react/src/components/date-picker/DatePicker.tsx, packages/lumx-react/src/components/date-picker/DatePickerControlled.test.tsx, packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx, packages/lumx-react/src/components/date-picker/DatePickerField.test.tsx, packages/lumx-react/src/utils/date/getYearDisplayName.test.ts, packages/lumx-react/src/utils/date/getYearDisplayName.ts
DSW-143
Add TextField for DatePicker to allow user to select year using keyboard.
Year is validated only when pressing enter or on blur.
It does not select a new date but set the month offset to the corresponding value.
Localization has been considered as well and TextField position is set based on the locale.  
Accessibility has been taken into account and month year is read when validating a new year.
StoryBook: https://91f6a16e--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=360))
=> feat(date-picker): add text field for year

CHANGELOG.md, packages/lumx-core/src/scss/components/message/_index.scss, packages/lumx-react/src/components/message/Message.stories.tsx, packages/lumx-react/src/components/message/Message.test.tsx, packages/lumx-react/src/components/message/Message.tsx, packages/lumx-react/src/stories/generated/Message/Demos.stories.tsx, packages/lumx-react/src/stories/generated/Message/closable.tsx, packages/site-demo/content/product/components/message/index.mdx, packages/site-demo/content/product/components/message/react/closable.tsx
https://lumapps.atlassian.net/browse/DSW-137
- Adds a new prop `closeButtonProps` to handle a new close button. Only the `info` kind with a background supports it. The button won't render for any other configuration. The label is required.
StoryBook: https://86b3eb90--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=359)) **⚠️ Outdated commit**
=> feat(message): add a close button to the message component

CHANGELOG.md, packages/lumx-react/src/components/popover/Popover.tsx, packages/lumx-react/src/hooks/useFocusTrap.ts, packages/lumx-react/src/utils/focus/getFirstAndLastFocusable.ts, packages/lumx-react/src/utils/focus/getFocusableElements.ts
Add a focusZoneElement prop on the Popover component allowing to specify the element in which the focus trap should be applied.
Make focus trap works with element with shadow root
=> chore(popover): allow to set the element to set a focus trap on

CHANGELOG.md, packages/lumx-react/src/components/chip/Chip.test.tsx, packages/lumx-react/src/components/chip/Chip.tsx
Make the `Chip` component focusable when used as `link` (with `href` prop).
1. Go on the `/story/lumx-components-chip-chip--chip-link` story
2. Make sure you can focus the chip using your keyboard (using Tab key)
3. Make sure you can trigger the link using your keyboard (user Enter key)
4. Make sure you open the link in a new tab using `ctrl + Enter`.
5. Make sure these behaviors still work properly using a mouse.
StoryBook: https://9baffa29--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=364)) **⚠️ Outdated commit**
=> fix(chip): fix tabindex when chip is a link

package.json, yarn.lock
Removing the eslint dev package from root package.json as it breaks the release workflow and it's not actually required
=> chore(dependencies): fix eslint dev package version requirement

CHANGELOG.md, packages/lumx-core/src/scss/core/color/_functions.scss
Fix an issue introduce in this PR https://github.com/lumapps/design-system/pull/1105, we have issues with the change introduce here : https://github.com/lumapps/design-system/pull/1105/files#diff-e9c65473a041d47079ec7b0eb7892fa6f29a0be893a1fa17138777d5a16f1ac5R87 that's trying to apply a `D2` variant, to colours that does not possess this variant (`light` / `dark`, ...). 
To fix this issue there is multiple solution, we could revert / condition the fixe that has been made, to only apply the D2 only to the "Green" / "Red" colour, like it was meant in the first change, but that does not seem to be a strong fix, to add specific if condition based on the colour.
I've opted to a more global solution, and patching the `lumx-color-variant` function, to add a fallback to the default "N" variant, …
=> fix(color): add fallback to default variant

CHANGELOG.md, packages/lumx-core/src/scss/components/inline-list/_index.scss, packages/lumx-react/src/components/inline-list/InlineList.stories.tsx, packages/lumx-react/src/components/inline-list/InlineList.tsx, packages/site-demo/content/product/components/inline-list/index.mdx
DSW-185
Add option to activate line wrap on parent overflow
StoryBook: https://abc2a6e5--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=370))
=> feat(inline-list): add `wrap` prop

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_index.scss, packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx, packages/lumx-react/src/components/thumbnail/types.ts, packages/site-demo/content/product/components/thumbnail/index.mdx
Added `objectFit` prop to adapt how the image should fit when it's aspect ratio is contained.
Defaults to `cover` to scale & crop the image (like before) but can be changed to `contain` to avoid cropping the
image (aka letterboxing)
StoryBook: https://6bde4117--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=372)) **⚠️ Outdated commit**
=> feat(thumbnail): add object fit prop

CHANGELOG.md, packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/Tooltip.tsx
Fix unstable tooltip children ref on rerender
=> fix(tooltip): fix unstable tooltip children on re-render

CHANGELOG.md, packages/lumx-react/src/components/text-field/TextField.test.tsx, packages/lumx-react/src/components/text-field/TextField.tsx
It was not possible to add an `aria-describedby` to a TextField without overriding those set by the error and helper.
Fixed by forwarding the prop and merging it with the error and helper.
=> fix(textfield): fix forward aria-describedby prop to input

CHANGELOG.md, packages/lumx-react/src/components/select/Select.tsx, packages/lumx-react/src/components/select/SelectMultiple.tsx
for forms and other controlled focus cases
DSW-208
Add `Select` and `SelectMultiple` input ref as a new `selectElementRef` prop
We need this ref to pass down React Hook Form focus control
=> feat(select): add select element ref

CHANGELOG.md, packages/lumx-core/src/scss/components/generic-block/_index.scss
Fix shrinking the generic block content instead of overflowing
=> fix(generic-block): fix shrinking of the content section

CHANGELOG.md, packages/lumx-core/src/scss/components/list/_mixins.scss
Make sure to display the keyboard focus ring on list item even when it is not marked with `isHighlighted`
=> fix(list-item): display focus ring even when not marked as highlighted

CHANGELOG.md, packages/lumx-core/src/scss/components/lightbox/_index.scss, packages/lumx-react/src/components/lightbox/Lightbox.tsx
Fix a11y color contrast on the Lightbox close button
DSW-198
Before | After
--- | ---
=> fix(lightbox): fix a11y color contrast on the close button

CHANGELOG.md, packages/lumx-core/src/scss/components/mosaic/_index.scss
Fix Mosaic thumbnail focus outline cropped by parent overflow
DSW-253
Before | After 
--- | ---
<video src=https://github.com/user-attachments/assets/8099f2de-0f86-43e1-83ad-ecafa3ac99fd /> | <video src=https://github.com/user-attachments/assets/b5f1df15-f6ac-4952-acf6-fbc1e8eb5d27 />
=> fix(mosaic): fix thumbnail focus outline cropped by parent overflow

CHANGELOG.md, packages/lumx-core/src/scss/components/slideshow/_index.scss
Fixed focus outline on slideshow pagination items cropped by the parent overflow style
| Before | After |
| --- | --- |
|![image](https://github.com/user-attachments/assets/cff9d885-819e-4f67-ae62-99a4f996a977)  | ![image](https://github.com/user-attachments/assets/2f95c88c-1fa4-4be3-833e-0c0787921b39) |
DSW-252
=> fix(slideshow): fix pagination item focus outline cut by overflow

CHANGELOG.md, packages/lumx-react/src/components/heading/Heading.test.tsx, packages/lumx-react/src/components/heading/Heading.tsx
When the `as` prop was set on `Heading` component, the default `typography` was not set correctly. It was only checking the calulated heading level, coming from an hypothetic HeadingLevelContext. If the context was not provided, it was using `h1` typography even for other levels.
|Before   |After   |
|---|---|
|  ![image](https://github.com/user-attachments/assets/d50a1aa2-fedc-473f-bdf9-2a354f1fe4dc) |![image](https://github.com/user-attachments/assets/75e80c07-4180-4f57-ab06-94bba36ff262) |
=> fix(heading): fix default typography when ̀`as` is set

CHANGELOG.md, packages/lumx-core/src/scss/components/image-block/_index.scss, packages/lumx-react/src/components/image-block/ImageBlock.stories.tsx, packages/lumx-react/src/components/image-block/ImageBlock.tsx, packages/lumx-react/src/components/image-block/ImageCaption.tsx
- Extract image caption rendering in an internal component (not exposed in the lib but will be reused in the ImageLightbox)
- Removing custom styles (use inline component styles from FlexBox, Text, etc.)
These changes should not impact usage or render of the existing ImageBlock
StoryBook: https://a010d7cc--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=381)) **⚠️ Outdated commit**
=> refactor(image-block): simplify caption styling

.github/workflows/release.yml
Add a step in release workflow to deprecate the older version of the prerelease after the new version has been uploaded
Testing:
1. Should not deprecate any version when using a prerelease tag that does not have an older version (ex: https://github.com/lumapps/design-system/actions/runs/10366047422/job/28694448631)
2. Should deprecate the old version when creating a new version for a prerelease tag (ex: https://github.com/lumapps/design-system/actions/runs/10366097796/job/28694607610)
=> chore(release): add step to deprecate older prerelease version

CHANGELOG.md, packages/lumx-core/src/scss/components/thumbnail/_index.scss, packages/lumx-react/src/components/thumbnail/Thumbnail.stories.tsx, packages/lumx-react/src/components/thumbnail/Thumbnail.tsx, packages/site-demo/content/product/components/thumbnail/index.mdx
Add `loadingPlaceholderImageRef` prop to re-use a loaded image as the loading placeholder.
If the given placeholder image is indeed already loaded, we use it as the background of the loading image.
This is useful when a small thumbnail is clicked to trigger the loading of a larger version of the same image
<details><summary>Demo</summary>
https://github.com/user-attachments/assets/5a55263f-98af-4976-933f-f225593e60e3
</details>
StoryBook: https://fd90435f--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=380)) **⚠️ Outdated commit**
=> feat(thumbnail): add loading placeholder image

.github/workflows/release-deploy-chromatic.yaml
Deploy chromatic when pushing the release commit on master rather than when pushing the release tag.
This should help chromatic know which reference to take (master) when comparing snapshots
=> chore(workflow): deploy chromatic on push master instead of tag

.github/workflows/release-deploy-chromatic.yaml
Skip steps rather than canceling the entire workflow to avoid cancellation notifications.
Use git command instead of GH API as it is more reliable (less server down time)
=> chore(workflow): skip step rather than cancel job is deploy chromatic

packages/lumx-core/src/scss/components/slideshow/_index.scss
Fixed a small oversight from https://github.com/lumapps/design-system/pull/1149 where the focus outline would still be cropped when selecting the right-most pagination item.
(not updating the CHANGELOG because there is already an entry talking about the fix from #1149)
=> chore(slideshow): fix small error in pagination items width

CHANGELOG.md, packages/lumx-react/src/components/image-block/ImageBlock.test.tsx, packages/lumx-react/src/components/image-block/ImageBlock.tsx, packages/lumx-react/src/components/image-block/ImageCaption.tsx
Restore old class names of iamge block caption elements.
Add title & description props forwarding.
=> fix(image-block): restore old caption classes and add props forwarding

CHANGELOG.md, packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx, packages/lumx-react/src/utils/date/formatDayNumber.test.ts, packages/lumx-react/src/utils/date/formatDayNumber.ts
Detect if the base translated day number contains some numerical character, in which case we only display them. Or if it doesn't, we display the base translated day number.
Example:
- English => 11
- Japanese => 11日 (original browser translation) => 11 (extracted numerical value)
- Arabic => ١١ (no numerical value)
StoryBook: https://df3a46be--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=387)) **⚠️ Outdated commit**
=> feat(date-picker): improve display of localized day number

CHANGELOG.md, packages/lumx-react/package.json, packages/lumx-react/src/components/alert-dialog/AlertDialog.test.tsx, packages/lumx-react/src/components/alert-dialog/AlertDialog.tsx, packages/lumx-react/src/components/checkbox/Checkbox.tsx, packages/lumx-react/src/components/navigation/NavigationSection.tsx, packages/lumx-react/src/components/radio-button/RadioButton.tsx, packages/lumx-react/src/components/select/Select.test.tsx, packages/lumx-react/src/components/select/SelectMultiple.test.tsx, packages/lumx-react/src/components/select/WithSelectContext.tsx, packages/lumx-react/src/components/side-navigation/SideNavigationItem.test.tsx, packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx, packages/lumx-react/src/components/slider/Slider.test.tsx, packages/lumx-react/src/components/slider/Slider.tsx, packages/lumx-react/src/components/switch/Switch.test.tsx, packages/lumx-react/src/components/switch/Switch.tsx, packages/lumx-react/src/components/tabs/state.ts, packages/lumx-react/src/components/text-field/TextField.tsx, packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/Tooltip.tsx, packages/lumx-react/src/components/uploader/Uploader.tsx, packages/lumx-react/src/hooks/useId.test.tsx, packages/lumx-react/src/hooks/useId.ts, packages/lumx-react/src/hooks/useSlideshowControls.ts, yarn.lock
- Refactor internal id generation (emulate react 18 useId)
- Remove uid lib & use of lodash uniqueId
StoryBook: https://afa3d84f--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=386)) **⚠️ Outdated commit**
=> refactor(utils): rework internal unique id generation

CHANGELOG.md, packages/lumx-core/src/scss/components/user-block/_index.scss, packages/lumx-react/src/components/user-block/UserBlock.stories.tsx, packages/lumx-react/src/components/user-block/UserBlock.tsx, packages/lumx-react/src/stories/generated/UserBlock/Demos.stories.tsx, packages/lumx-react/src/stories/generated/UserBlock/size-xs.tsx, packages/site-demo/content/product/components/user-block/index.mdx, packages/site-demo/content/product/components/user-block/react/size-xs.tsx
A new size for the user block that will better integrate in some designs.
Fix: https://lumapps.atlassian.net/browse/DSW-233
=> feat(user-block xs): added a size XS to usr block

CHANGELOG.md, packages/lumx-react/src/components/tooltip/Tooltip.tsx, packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx
Remove render short-circuit when label is falsy to avoid react hook re-render errors
=> fix(tooltip): fix re-render errors when removing the label

CHANGELOG.md, packages/lumx-react/src/components/image-lightbox/internal/ImageSlideshow.tsx, packages/lumx-react/src/components/image-lightbox/useImageLightbox.tsx
- fix(image-lightbox): update props each time the lightbox opens
- fix(image-lightbox): fix reset zoom scale when switching to the first item
StoryBook: https://ede04ee6--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=393))
=> fix(image-lightbox): minor fixes

CHANGELOG.md, packages/lumx-core/src/scss/components/button/_index.scss, packages/lumx-react/src/components/button/ButtonGroup.stories.tsx
Make sure that the border radius of the first button is only applied on the left and the border radius of the last button is only applied on the right.
Ignore .visually-hidden children (the border radius was applied to them if they were placed in first or last position)
Make it work with a signle button (the left border radius was removed)
StoryBook: https://70b28dd0--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=394)) **⚠️ Outdated commit**
=> fix(button-group): fixed border style with hidden or single child

CHANGELOG.md, packages/lumx-react/src/components/image-lightbox/internal/usePointerZoom.ts
pageY & pageX we used for the cursor position for the zoom center actually depended on the page scroll position but we wanted the cursor position in the window (since the image lightbox is always fullscreen)
=> fix(image-lightbox): fix zoom on mouse wheel cursor position

CHANGELOG.md, packages/lumx-core/src/scss/components/slideshow/_index.scss
Customer reported that only a change of color for pagination item was a bit weak for accessibility.
The fix increases the width of the active pagination item to have another way to distinguish the active item.
Fixes https://lumapps.atlassian.net/browse/DSW-276
=> fix(slideshow-a11y): Changed active pagination item width for a11y improvement

CHANGELOG.md, packages/lumx-core/src/scss/components/tooltip/_index.scss, packages/lumx-react/src/components/image-lightbox/ImageLightbox.test.tsx, packages/lumx-react/src/components/popover/usePopoverStyle.tsx, packages/lumx-react/src/components/side-navigation/SideNavigationItem.tsx, packages/lumx-react/src/components/tooltip/Tooltip.stories.tsx, packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/Tooltip.tsx, packages/lumx-react/src/components/tooltip/constants.ts, packages/lumx-react/src/components/tooltip/useInjectTooltipRef.tsx, packages/lumx-react/src/components/tooltip/useTooltipOpen.tsx, packages/lumx-react/src/constants.ts, packages/lumx-react/src/hooks/usePopper.ts, packages/lumx-react/src/utils/type.ts, packages/site-demo/content/product/components/tooltip/index.mdx
- **feat(tooltip): add `closeMode` to hide instead of unmount when closed**
- **chore(tooltip): skip async state updates in jsdom env**
- **feat(tooltip): add `ariaLinkMode` to use tooltip as label instead of description**
StoryBook: https://d9f4b170--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=396)) **⚠️ Outdated commit**
=> feat(tooltip): add `closeMode` and `ariaLinkMode` modes

packages/lumx-react/src/components/tooltip/Tooltip.tsx
We need to update the tooltip position on open for closeMode=hide
I'm not adding an entry in the CHANGELOG because it's technically a fix but for something that is not released yet
=> chore(tooltip): update tooltip position on open

CHANGELOG.md, packages/lumx-react/src/components/popover/Popover.tsx, packages/lumx-react/src/components/popover/constants.ts, packages/lumx-react/src/components/tooltip/Tooltip.tsx, packages/lumx-react/src/components/tooltip/constants.ts
With the new mode closeMode=hide, the tooltip can appear below popovers because it can mount before the parent popover in the DOM
Updating the tooltip z-index be just above the default popover z-index
=> feat(tooltip): increment z-index above popover default z-index

CHANGELOG.md, packages/lumx-core/src/scss/components/date-picker/_index.scss, packages/lumx-core/src/scss/components/text-field/_mixins.scss, packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx, packages/lumx-react/src/stories/generated/TextField/Demos.stories.tsx, packages/lumx-react/src/stories/generated/TextField/number.tsx, packages/site-demo/content/product/components/text-field/index.mdx, packages/site-demo/content/product/components/text-field/react/number.tsx
Display again buttons up and down for text-field with type="number" for accessibility.
Added "number" use case in text-field documentation
<br \>
https://lumapps.atlassian.net/browse/DSW-281
StoryBook: https://5991f059--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=400))
=> fix(text-field): Display buttons for type number, documentation for number use case

CHANGELOG.md, packages/lumx-core/src/scss/components/tooltip/_index.scss, packages/lumx-react/src/components/date-picker/DatePickerControlled.test.tsx, packages/lumx-react/src/components/date-picker/DatePickerControlled.tsx, packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/Tooltip.tsx, packages/lumx-react/src/constants.ts
Use the standard visually-hidden class on Tooltip closeMode=hide instead of a custom class
Tooltip closeMode=hide
- should correctly open/close on mouse hover or focus
- tooltip label should be announced by screen readers
StoryBook: https://4b71eb32--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=403)) **⚠️ Outdated commit**
=> feat(tooltip): use standard visually-hidden class in closeMode=hide

CHANGELOG.md, packages/lumx-react/src/stories/generated/Mosaic/Demos.stories.tsx, packages/lumx-react/src/stories/generated/Mosaic/clickable.tsx, packages/site-demo/content/product/components/image-lightbox/react/default.tsx, packages/site-demo/content/product/components/mosaic/index.mdx, packages/site-demo/content/product/components/mosaic/react/clickable.tsx, packages/site-demo/content/product/components/mosaic/react/four-images.tsx, packages/site-demo/content/product/components/mosaic/react/more-images.tsx, packages/site-demo/content/product/components/mosaic/react/three-images.tsx, packages/site-demo/content/product/components/mosaic/react/two-images.tsx
With recent improvements on Lightbox the Mosaic demos were broken (no more Slideshow controls in the demos Lightboxes), we decided to remove the Lightboxes from the demo as the Mosaic do not provide automatically a Lightbox component.
The "Click on thumbnail" part of the documentation is also changed to reflect that having a Lightbox on Mosaic is a possibility not a obligation. 
Fix https://lumapps.atlassian.net/browse/DSW-285
=> docs(mosaic): removed broken lightboxes on mosaic demos.

CHANGELOG.md, packages/lumx-core/src/scss/components/badge/_index.scss, packages/lumx-react/src/components/badge/BadgeWrapper.stories.tsx, packages/lumx-react/src/components/badge/BadgeWrapper.test.tsx, packages/lumx-react/src/components/badge/BadgeWrapper.tsx, packages/lumx-react/src/components/badge/index.ts
Add a new component `BadgeWrapper` which allows to wrap any other component to add a badge on it. 
It may be used as follows: 
let's say for instance that I want to display a badge over a chip:
```typescript
<BadgeWrapper
badge={(
<Badge color={ColorPalette.red}>
<Icon icon={mdiHeart} />
</Badge>
)}
>
<Chip>Some chip</Chip>
</BadgeWrapper>
```
**NB: We will add a documentation page later after further discussion with Corgui and Flodi, the task is created in Jira: [DSW-292](https://lumapps.atlassian.net/browse/DSW-292)**
Example on a chip
Example on an icon
Example on a button
[DSW-292]: https://lumapps.atlassian.net/browse/DSW-292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(badge): add a wrapper to enable adding a badge to any component

CHANGELOG.md, packages/lumx-react/src/components/chip/Chip.test.tsx, packages/lumx-react/src/components/chip/Chip.tsx
DSW-295
The "onClick" prop is never triggered when pressing the `Enter` key while focused on the button.
This is because the event wasn't properly forwarded to the prop.
=> fix(chip): trigger onClick event on Enter key

CHANGELOG.md, packages/lumx-core/src/js/constants/index.ts, packages/lumx-react/src/components/expansion-panel/ExpansionPanel.test.tsx, packages/lumx-react/src/components/expansion-panel/ExpansionPanel.tsx, packages/site-demo/content/product/components/expansion-panel/react/examples.tsx
DSW-294
Due to a recent change, the `ExpansionPanel` was only removing the children from the DOM when clicking on the header/toggle button.
However, we have some cases where the panel closes without the header receiving a click (ex: when another panel is opened).
In these cases, the children remained in the DOM.
Fixed by using the `useVisibilityTransition` hook.
A `Close all` button has been added on a story to properly test it.
=> fix(expansion-panel): fix children remaining in DOM when isOpen changes

CHANGELOG.md, packages/lumx-core/src/css/design-tokens.css, packages/lumx-core/src/js/constants/design-tokens.ts, packages/lumx-core/src/scss/_design-tokens.scss, packages/lumx-core/src/scss/components/navigation/_index.scss, packages/lumx-core/src/scss/components/navigation/_mixins.scss, packages/lumx-core/style-dictionary/config/utils/_format-stylelint-disable.js, packages/lumx-core/style-dictionary/properties/components/navigation.json
Rework the navigation item styles to make sure the border left & right does not affect the width
- Refactor navigation item styles to use "private" css variables to indirectly apply the public variables (design tokens)
- Calculate the left padding by removing the current border left width
- Calculate the right padding by removing the current border right width
- Make sure the border width default to `0px` and not `0` (or else it breaks the `calc()`)
StoryBook: https://3ec7fb6e--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=414))
=> fix(navigation-item): fix border left & right impacting the width

packages/lumx-core/src/scss/components/side-navigation/_index.scss
Fix a bug where all the children of a selected side navigation would get the selected style
(Not adding in the changelog since it does not appear in the current release of lumx)
StoryBook: [Deploying...](https://github.com/lumapps/design-system/actions/runs/12237776357?pr=1226)
=> fix(side-navigation): fix selected style rule no constrained enough

CHANGELOG.md, packages/lumx-core/src/css/design-tokens.css, packages/lumx-core/src/js/constants/design-tokens.ts, packages/lumx-core/src/scss/_design-tokens.scss, packages/lumx-core/src/scss/components/button/_index.scss, packages/lumx-core/src/scss/components/button/_mixins.scss, packages/lumx-core/src/scss/components/date-picker/_index.scss, packages/lumx-core/style-dictionary/properties/components/button.json, packages/lumx-react/src/components/button/Button.stories.tsx, packages/lumx-react/src/components/button/ButtonRoot.tsx, packages/lumx-react/src/stories/utils/theming.tsx
- Reworked button styles so that the selected state can apply on top of both `medium` and `low` emphasis
- Deprecate selected state padding variables as we prefer to keep the base emphasis style for sizing
Selected state in low and medium emphasis is testable here: https://4436b6bb--5fbfb1d508c0520021560f10.chromatic.com/?path=/story/lumx-components-button-button--state-variations
StoryBook: https://1e0d3d2e--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=416)) **⚠️ Outdated commit**
=> feat(button): add support for `isSelected` in `low` emphasis

CHANGELOG.md, packages/lumx-core/src/scss/components/slideshow/_index.scss
User reported non-suffisant contrast ratio on non-active bullet of the slide show controller.
This work improve the contrast by changing the style of non-selected bullets.
Fix https://lumapps.atlassian.net/browse/DSW-333
StoryBook: https://babbb781--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=426)) **⚠️ Outdated commit**
=> fix(slideshow-contrast): improve contrast of non-selected bullets

packages/lumx-react/src/utils/className/getBasicClass.test.ts, packages/lumx-react/src/utils/className/getFontColorClassName.test.ts, packages/lumx-react/src/utils/className/getFontColorClassName.ts, packages/lumx-react/src/utils/className/getRootClassName.test.ts, packages/lumx-react/src/utils/className/getRootClassName.ts, packages/lumx-react/src/utils/className/getTypographyClassName.test.ts, packages/lumx-react/src/utils/className/getTypographyClassName.ts, packages/lumx-react/src/utils/className/handleBasicClasses.test.ts, packages/lumx-react/src/utils/className/index.ts
Split the className utils into multiple modules and add unit test for the core className utils
=> refactor(utils): split className utils in modules

CHANGELOG.md, packages/lumx-core/src/scss/components/popover/_index.scss, packages/lumx-react/src/components/popover/Popover.test.tsx, packages/lumx-react/src/components/popover/Popover.tsx, packages/site-demo/content/product/foundations/light-dark-theme/index.mdx
Since the dark popover is very rare I think it's safe change a bit how it functions to automatically progagate the dark theme to the children via the theme context to simplify our theme handling
=> feat(popover): propagate the theme props to its children

CHANGELOG.md, packages/lumx-react/src/components/button/Button.tsx, packages/lumx-react/src/components/button/ButtonRoot.tsx
Remove the children prop type from IconButton as it's not supported
=> fix(icon-button): remove unsupported children prop type

CHANGELOG.md, packages/lumx-react/src/components/popover/Popover.tsx, packages/lumx-react/src/components/popover/usePopoverStyle.tsx
Fix improper placement of the Popover on open on React 18
StoryBook: https://8740bee3--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=436)) **⚠️ Outdated commit**
=> fix(popover): fix improper first placement on React 18

CHANGELOG.md, packages/lumx-react/src/components/tooltip/Tooltip.test.tsx, packages/lumx-react/src/components/tooltip/Tooltip.tsx
Fix "labelled by" link broken because of the aria label on the tooltip
=> fix(tooltip): remove aria-label that breaks labelled by link

CHANGELOG.md, packages/lumx-core/src/scss/components/mosaic/_index.scss
remove negative inset that could break overflow of parent element
StoryBook: https://e197ae44--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=440))
=> fix(mosaic): fix parent overflow issue caused by negative inset

CHANGELOG.md, packages/lumx-react/src/components/dialog/Dialog.test.tsx, packages/lumx-react/src/components/dialog/Dialog.tsx, packages/lumx-react/src/components/lightbox/Lightbox.test.tsx, packages/lumx-react/src/components/lightbox/Lightbox.tsx, packages/lumx-react/src/components/popover-dialog/PopoverDialog.stories.tsx, packages/lumx-react/src/components/popover-dialog/PopoverDialog.test.tsx, packages/lumx-react/src/components/popover-dialog/PopoverDialog.tsx
DSW-393
- **feat(dialog): set default heading level context to `h2`**
- **feat(lightbox): set default heading level context to `h2`**
- **feat(popover-dialogg): set default heading level context to `h2`**
=> feat: set default heading level context to all dialogs to h2

CHANGELOG.md, packages/lumx-react/src/components/button/Button.test.tsx, packages/lumx-react/src/components/button/Button.tsx, packages/lumx-react/src/testing/utils/commonTestsSuiteRTL.tsx
fix button icons color inside a theme context
StoryBook: https://ed9f99c3--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=445))
=> fix(button): fix icon color inside a theme context

CHANGELOG.md, packages/lumx-core/src/scss/components/link/_index.scss
Fix weird warping of the link focus outline around nested icons
| Before | After |
| --- | --- |
| <img width="284" alt="before" src="https://github.com/user-attachments/assets/7e4b85a6-a137-4aec-9b74-0f353d35f4f7" /> | <img width="284" alt="after" src="https://github.com/user-attachments/assets/35ac5f8b-cd6f-4c92-8618-5ea84b866950" /> |
=> fix(link): fix focus outline warping around nested icons

CHANGELOG.md, packages/lumx-core/src/scss/components/link/_index.scss, packages/lumx-react/src/components/link/Link.stories.tsx
DSW-401
Before | After
--- | ---
StoryBook: https://738a0e66--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=452))
=> fix(link): fix icon alignment with nested `hasShape` icons

CHANGELOG.md, packages/lumx-react/src/components/avatar/Avatar.stories.tsx, packages/lumx-react/src/components/avatar/Avatar.tsx
Add `xxs` size to avatar  
(ideal size to nest inside chips after/before)
=> feat(chip): add `xxs` size

CHANGELOG.md, packages/lumx-core/src/scss/components/button/_mixins.scss, packages/lumx-core/src/scss/core/state/_mixins.scss, packages/lumx-react/src/components/button/Button.stories.tsx, packages/lumx-react/src/components/button/Button.test.tsx, packages/lumx-react/src/components/button/ButtonRoot.tsx
Make the button disableable with only the `aria-disabled` prop. 
If `aria-disabled` is set to `true`, the button will have all disabled behavior (prevent click, disabled styles, no hover or active styles) but displays the tooltip on hover correctly.
=> feat(button): add disabled behavior with aria-disabled only

CHANGELOG.md, packages/lumx-react/src/components/thumbnail/useFocusPointStyle.tsx
Since `0 ` is a falsey value, fcal points equalling 0 in Thumnbail component were handled like null or undefined and skipped. But we actually need `0` to be handled like any other numeric value. This fix aims to avoid skipping 0, only `null` and `undefined` are now skipped.
(other falsey values should be avoided thx to Typescript)
=> fix(thumbnail): handle 0 in focalPoint properly

CHANGELOG.md, packages/lumx-core/src/scss/components/user-block/_index.scss, packages/lumx-react/src/components/user-block/UserBlock.stories.tsx, packages/lumx-react/src/stories/decorators/withResizableBox.tsx, packages/lumx-react/src/stories/decorators/withWrapper.tsx
| Before | After |
| --- | --- |
StoryBook: https://aa3e4d82--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=463)) **⚠️ Outdated commit**
=> fix(user-block): fix fields wrapping in horizontal mode

CHANGELOG.md, packages/lumx-core/src/scss/components/progress/_index.scss, packages/lumx-react/src/components/progress/ProgressCircular.stories.tsx, packages/lumx-react/src/components/progress/ProgressCircular.test.tsx, packages/lumx-react/src/components/progress/ProgressCircular.tsx
Add display inline variant to the ProgressCircular to use inside of text elements
StoryBook: https://6e5ccca1--5fbfb1d508c0520021560f10.chromatic.com/ ([Chromatic build](https://www.chromatic.com/build?appId=5fbfb1d508c0520021560f10&number=464))
=> feat(progress): add display inline variant to ProgressCircular

CHANGELOG.md, packages/lumx-react/src/components/expansion-panel/ExpansionPanel.stories.tsx, packages/lumx-react/src/components/expansion-panel/ExpansionPanel.test.tsx, packages/lumx-react/src/components/expansion-panel/ExpansionPanel.tsx
As discussed a few weeks ago with @gcornut, I updated the `ExpansionPanel` component to add a new prop `closeMode?: 'hide' | 'unmount'`
This prop should condition whether the children components of the panel should just be hidden or unmounted when the panel gets closed. It defaults to `unmount` for the sake of compatibility with prior versions.
NB: This prop also exists in the `Tooltip` and `SideNavigation` components.
N/A
Add/Remove/Update the following check list depending on your submission: …
=> feat(expansion-panel): add closeMode so children are unmounted/hidden
